// Original file: exa/cortex_pb/cortex.proto

export const ActionStatus = {
  ACTION_STATUS_UNSPECIFIED: 'ACTION_STATUS_UNSPECIFIED',
  ACTION_STATUS_ERROR: 'ACTION_STATUS_ERROR',
  ACTION_STATUS_INITIALIZED: 'ACTION_STATUS_INITIALIZED',
  ACTION_STATUS_PREPARING: 'ACTION_STATUS_PREPARING',
  ACTION_STATUS_PREPARED: 'ACTION_STATUS_PREPARED',
  ACTION_STATUS_APPLYING: 'ACTION_STATUS_APPLYING',
  ACTION_STATUS_APPLIED: 'ACTION_STATUS_APPLIED',
  ACTION_STATUS_REJECTED: 'ACTION_STATUS_REJECTED',
} as const;

export type ActionStatus =
  | 'ACTION_STATUS_UNSPECIFIED'
  | 0
  | 'ACTION_STATUS_ERROR'
  | 1
  | 'ACTION_STATUS_INITIALIZED'
  | 2
  | 'ACTION_STATUS_PREPARING'
  | 3
  | 'ACTION_STATUS_PREPARED'
  | 4
  | 'ACTION_STATUS_APPLYING'
  | 5
  | 'ACTION_STATUS_APPLIED'
  | 6
  | 'ACTION_STATUS_REJECTED'
  | 7

export type ActionStatus__Output = typeof ActionStatus[keyof typeof ActionStatus]
