// Original file: exa/cortex_pb/cortex.proto

export const AutoRunDecision = {
  AUTO_RUN_DECISION_UNSPECIFIED: 'AUTO_RUN_DECISION_UNSPECIFIED',
  AUTO_RUN_DECISION_USER_ALLOW: 'AUTO_RUN_DECISION_USER_ALLOW',
  AUTO_RUN_DECISION_USER_DENY: 'AUTO_RUN_DECISION_USER_DENY',
  AUTO_RUN_DECISION_SYSTEM_ALLOW: 'AUTO_RUN_DECISION_SYSTEM_ALLOW',
  AUTO_RUN_DECISION_SYSTEM_DENY: 'AUTO_RUN_DECISION_SYSTEM_DENY',
  AUTO_RUN_DECISION_MODEL_ALLOW: 'AUTO_RUN_DECISION_MODEL_ALLOW',
  AUTO_RUN_DECISION_MODEL_DENY: 'AUTO_RUN_DECISION_MODEL_DENY',
  AUTO_RUN_DECISION_DEFAULT_ALLOW: 'AUTO_RUN_DECISION_DEFAULT_ALLOW',
  AUTO_RUN_DECISION_DEFAULT_DENY: 'AUTO_RUN_DECISION_DEFAULT_DENY',
  AUTO_RUN_DECISION_USER_SKIP: 'AUTO_RUN_DECISION_USER_SKIP',
} as const;

export type AutoRunDecision =
  | 'AUTO_RUN_DECISION_UNSPECIFIED'
  | 0
  | 'AUTO_RUN_DECISION_USER_ALLOW'
  | 1
  | 'AUTO_RUN_DECISION_USER_DENY'
  | 2
  | 'AUTO_RUN_DECISION_SYSTEM_ALLOW'
  | 3
  | 'AUTO_RUN_DECISION_SYSTEM_DENY'
  | 4
  | 'AUTO_RUN_DECISION_MODEL_ALLOW'
  | 5
  | 'AUTO_RUN_DECISION_MODEL_DENY'
  | 6
  | 'AUTO_RUN_DECISION_DEFAULT_ALLOW'
  | 7
  | 'AUTO_RUN_DECISION_DEFAULT_DENY'
  | 8
  | 'AUTO_RUN_DECISION_USER_SKIP'
  | 9

export type AutoRunDecision__Output = typeof AutoRunDecision[keyof typeof AutoRunDecision]
