// Original file: exa/cortex_pb/cortex.proto

export const BrainUpdateTrigger = {
  BRAIN_UPDATE_TRIGGER_UNSPECIFIED: 'BRAIN_UPDATE_TRIGGER_UNSPECIFIED',
  BRAIN_UPDATE_TRIGGER_SYSTEM_FORCED: 'BRAIN_UPDATE_TRIGGER_SYSTEM_FORCED',
  BRAIN_UPDATE_TRIGGER_USER_REQUESTED: 'BRAIN_UPDATE_TRIGGER_USER_REQUESTED',
  BRAIN_UPDATE_TRIGGER_USER_NEW_INFO: 'BRAIN_UPDATE_TRIGGER_USER_NEW_INFO',
  BRAIN_UPDATE_TRIGGER_RESEARCH_NEW_INFO: 'BRAIN_UPDATE_TRIGGER_RESEARCH_NEW_INFO',
} as const;

export type BrainUpdateTrigger =
  | 'BRAIN_UPDATE_TRIGGER_UNSPECIFIED'
  | 0
  | 'BRAIN_UPDATE_TRIGGER_SYSTEM_FORCED'
  | 1
  | 'BRAIN_UPDATE_TRIGGER_USER_REQUESTED'
  | 2
  | 'BRAIN_UPDATE_TRIGGER_USER_NEW_INFO'
  | 3
  | 'BRAIN_UPDATE_TRIGGER_RESEARCH_NEW_INFO'
  | 4

export type BrainUpdateTrigger__Output = typeof BrainUpdateTrigger[keyof typeof BrainUpdateTrigger]
