// Original file: exa/cortex_pb/cortex.proto

export const CascadeAgentToolSet = {
  CASCADE_AGENT_TOOL_SET_UNSPECIFIED: 'CASCADE_AGENT_TOOL_SET_UNSPECIFIED',
  CASCADE_AGENT_TOOL_SET_ONLY_COMMAND: 'CASCADE_AGENT_TOOL_SET_ONLY_COMMAND',
  CASCADE_AGENT_TOOL_SET_COMMAND_AND_EDITS: 'CASCADE_AGENT_TOOL_SET_COMMAND_AND_EDITS',
  CASCADE_AGENT_TOOL_SET_NO_SEARCH: 'CASCADE_AGENT_TOOL_SET_NO_SEARCH',
} as const;

export type CascadeAgentToolSet =
  | 'CASCADE_AGENT_TOOL_SET_UNSPECIFIED'
  | 0
  | 'CASCADE_AGENT_TOOL_SET_ONLY_COMMAND'
  | 1
  | 'CASCADE_AGENT_TOOL_SET_COMMAND_AND_EDITS'
  | 2
  | 'CASCADE_AGENT_TOOL_SET_NO_SEARCH'
  | 3

export type CascadeAgentToolSet__Output = typeof CascadeAgentToolSet[keyof typeof CascadeAgentToolSet]
