// Original file: exa/cortex_pb/cortex.proto

export const CortexTrajectorySource = {
  CORTEX_TRAJECTORY_SOURCE_UNSPECIFIED: 'CORTEX_TRAJECTORY_SOURCE_UNSPECIFIED',
  CORTEX_TRAJECTORY_SOURCE_CASCADE_CLIENT: 'CORTEX_TRAJECTORY_SOURCE_CASCADE_CLIENT',
  CORTEX_TRAJECTORY_SOURCE_EXPLAIN_PROBLEM: 'CORTEX_TRAJECTORY_SOURCE_EXPLAIN_PROBLEM',
  CORTEX_TRAJECTORY_SOURCE_REFACTOR_FUNCTION: 'CORTEX_TRAJECTORY_SOURCE_REFACTOR_FUNCTION',
  CORTEX_TRAJECTORY_SOURCE_EVAL: 'CORTEX_TRAJECTORY_SOURCE_EVAL',
  CORTEX_TRAJECTORY_SOURCE_EVAL_TASK: 'CORTEX_TRAJECTORY_SOURCE_EVAL_TASK',
  CORTEX_TRAJECTORY_SOURCE_ASYNC_PRR: 'CORTEX_TRAJECTORY_SOURCE_ASYNC_PRR',
  CORTEX_TRAJECTORY_SOURCE_ASYNC_CF: 'CORTEX_TRAJECTORY_SOURCE_ASYNC_CF',
  CORTEX_TRAJECTORY_SOURCE_ASYNC_SL: 'CORTEX_TRAJECTORY_SOURCE_ASYNC_SL',
  CORTEX_TRAJECTORY_SOURCE_ASYNC_PRD: 'CORTEX_TRAJECTORY_SOURCE_ASYNC_PRD',
  CORTEX_TRAJECTORY_SOURCE_ASYNC_CM: 'CORTEX_TRAJECTORY_SOURCE_ASYNC_CM',
  CORTEX_TRAJECTORY_SOURCE_PASSIVE_CODER: 'CORTEX_TRAJECTORY_SOURCE_PASSIVE_CODER',
  CORTEX_TRAJECTORY_SOURCE_CODE_MAP: 'CORTEX_TRAJECTORY_SOURCE_CODE_MAP',
  CORTEX_TRAJECTORY_SOURCE_LIFEGUARD: 'CORTEX_TRAJECTORY_SOURCE_LIFEGUARD',
} as const;

export type CortexTrajectorySource =
  | 'CORTEX_TRAJECTORY_SOURCE_UNSPECIFIED'
  | 0
  | 'CORTEX_TRAJECTORY_SOURCE_CASCADE_CLIENT'
  | 1
  | 'CORTEX_TRAJECTORY_SOURCE_EXPLAIN_PROBLEM'
  | 2
  | 'CORTEX_TRAJECTORY_SOURCE_REFACTOR_FUNCTION'
  | 3
  | 'CORTEX_TRAJECTORY_SOURCE_EVAL'
  | 4
  | 'CORTEX_TRAJECTORY_SOURCE_EVAL_TASK'
  | 5
  | 'CORTEX_TRAJECTORY_SOURCE_ASYNC_PRR'
  | 6
  | 'CORTEX_TRAJECTORY_SOURCE_ASYNC_CF'
  | 7
  | 'CORTEX_TRAJECTORY_SOURCE_ASYNC_SL'
  | 8
  | 'CORTEX_TRAJECTORY_SOURCE_ASYNC_PRD'
  | 9
  | 'CORTEX_TRAJECTORY_SOURCE_ASYNC_CM'
  | 10
  | 'CORTEX_TRAJECTORY_SOURCE_PASSIVE_CODER'
  | 11
  | 'CORTEX_TRAJECTORY_SOURCE_CODE_MAP'
  | 13
  | 'CORTEX_TRAJECTORY_SOURCE_LIFEGUARD'
  | 15

export type CortexTrajectorySource__Output = typeof CortexTrajectorySource[keyof typeof CortexTrajectorySource]
