// Original file: exa/cortex_pb/cortex.proto

export const CortexTodoListItemStatus = {
  CORTEX_TODO_LIST_ITEM_STATUS_UNSPECIFIED: 'CORTEX_TODO_LIST_ITEM_STATUS_UNSPECIFIED',
  CORTEX_TODO_LIST_ITEM_STATUS_PENDING: 'CORTEX_TODO_LIST_ITEM_STATUS_PENDING',
  CORTEX_TODO_LIST_ITEM_STATUS_IN_PROGRESS: 'CORTEX_TODO_LIST_ITEM_STATUS_IN_PROGRESS',
  CORTEX_TODO_LIST_ITEM_STATUS_COMPLETED: 'CORTEX_TODO_LIST_ITEM_STATUS_COMPLETED',
} as const;

export type CortexTodoListItemStatus =
  | 'CORTEX_TODO_LIST_ITEM_STATUS_UNSPECIFIED'
  | 0
  | 'CORTEX_TODO_LIST_ITEM_STATUS_PENDING'
  | 1
  | 'CORTEX_TODO_LIST_ITEM_STATUS_IN_PROGRESS'
  | 2
  | 'CORTEX_TODO_LIST_ITEM_STATUS_COMPLETED'
  | 3

export type CortexTodoListItemStatus__Output = typeof CortexTodoListItemStatus[keyof typeof CortexTodoListItemStatus]
