// Original file: exa/cortex_pb/cortex.proto

export const CortexTrajectoryType = {
  CORTEX_TRAJECTORY_TYPE_UNSPECIFIED: 'CORTEX_TRAJECTORY_TYPE_UNSPECIFIED',
  CORTEX_TRAJECTORY_TYPE_USER_MAINLINE: 'CORTEX_TRAJECTORY_TYPE_USER_MAINLINE',
  CORTEX_TRAJECTORY_TYPE_USER_GRANULAR: 'CORTEX_TRAJECTORY_TYPE_USER_GRANULAR',
  CORTEX_TRAJECTORY_TYPE_SUPERCOMPLETE: 'CORTEX_TRAJECTORY_TYPE_SUPERCOMPLETE',
  CORTEX_TRAJECTORY_TYPE_CASCADE: 'CORTEX_TRAJECTORY_TYPE_CASCADE',
  CORTEX_TRAJECTORY_TYPE_BACKGROUND_RESEARCH: 'CORTEX_TRAJECTORY_TYPE_BACKGROUND_RESEARCH',
  CORTEX_TRAJECTORY_TYPE_CHECKPOINT: 'CORTEX_TRAJECTORY_TYPE_CHECKPOINT',
  CORTEX_TRAJECTORY_TYPE_RETRIEVE_MEMORY: 'CORTEX_TRAJECTORY_TYPE_RETRIEVE_MEMORY',
  CORTEX_TRAJECTORY_TYPE_CUSTOM_TOOL: 'CORTEX_TRAJECTORY_TYPE_CUSTOM_TOOL',
  CORTEX_TRAJECTORY_TYPE_AUTO_CASCADE: 'CORTEX_TRAJECTORY_TYPE_AUTO_CASCADE',
  CORTEX_TRAJECTORY_TYPE_AUTO_CASCADE_MANAGER: 'CORTEX_TRAJECTORY_TYPE_AUTO_CASCADE_MANAGER',
  CORTEX_TRAJECTORY_TYPE_APPLIER: 'CORTEX_TRAJECTORY_TYPE_APPLIER',
  CORTEX_TRAJECTORY_TYPE_TOOL_CALL_PROPOSAL: 'CORTEX_TRAJECTORY_TYPE_TOOL_CALL_PROPOSAL',
  CORTEX_TRAJECTORY_TYPE_TRAJECTORY_CHOICE: 'CORTEX_TRAJECTORY_TYPE_TRAJECTORY_CHOICE',
  CORTEX_TRAJECTORY_TYPE_LLM_JUDGE: 'CORTEX_TRAJECTORY_TYPE_LLM_JUDGE',
  CORTEX_TRAJECTORY_TYPE_ARTIFACT_SUMMARY: 'CORTEX_TRAJECTORY_TYPE_ARTIFACT_SUMMARY',
  CORTEX_TRAJECTORY_TYPE_PASSIVE_CODER: 'CORTEX_TRAJECTORY_TYPE_PASSIVE_CODER',
  CORTEX_TRAJECTORY_TYPE_INTERACTIVE_CASCADE: 'CORTEX_TRAJECTORY_TYPE_INTERACTIVE_CASCADE',
  CORTEX_TRAJECTORY_TYPE_BRAIN_UPDATE: 'CORTEX_TRAJECTORY_TYPE_BRAIN_UPDATE',
} as const;

export type CortexTrajectoryType =
  | 'CORTEX_TRAJECTORY_TYPE_UNSPECIFIED'
  | 0
  | 'CORTEX_TRAJECTORY_TYPE_USER_MAINLINE'
  | 1
  | 'CORTEX_TRAJECTORY_TYPE_USER_GRANULAR'
  | 2
  | 'CORTEX_TRAJECTORY_TYPE_SUPERCOMPLETE'
  | 3
  | 'CORTEX_TRAJECTORY_TYPE_CASCADE'
  | 4
  | 'CORTEX_TRAJECTORY_TYPE_BACKGROUND_RESEARCH'
  | 5
  | 'CORTEX_TRAJECTORY_TYPE_CHECKPOINT'
  | 6
  | 'CORTEX_TRAJECTORY_TYPE_RETRIEVE_MEMORY'
  | 7
  | 'CORTEX_TRAJECTORY_TYPE_CUSTOM_TOOL'
  | 8
  | 'CORTEX_TRAJECTORY_TYPE_AUTO_CASCADE'
  | 9
  | 'CORTEX_TRAJECTORY_TYPE_AUTO_CASCADE_MANAGER'
  | 10
  | 'CORTEX_TRAJECTORY_TYPE_APPLIER'
  | 11
  | 'CORTEX_TRAJECTORY_TYPE_TOOL_CALL_PROPOSAL'
  | 12
  | 'CORTEX_TRAJECTORY_TYPE_TRAJECTORY_CHOICE'
  | 13
  | 'CORTEX_TRAJECTORY_TYPE_LLM_JUDGE'
  | 14
  | 'CORTEX_TRAJECTORY_TYPE_ARTIFACT_SUMMARY'
  | 19
  | 'CORTEX_TRAJECTORY_TYPE_PASSIVE_CODER'
  | 15
  | 'CORTEX_TRAJECTORY_TYPE_INTERACTIVE_CASCADE'
  | 17
  | 'CORTEX_TRAJECTORY_TYPE_BRAIN_UPDATE'
  | 16

export type CortexTrajectoryType__Output = typeof CortexTrajectoryType[keyof typeof CortexTrajectoryType]
