// Original file: exa/cortex_pb/cortex.proto

export const CortexStepManagerFeedbackStatus = {
  CORTEX_STEP_MANAGER_FEEDBACK_STATUS_UNSPECIFIED: 'CORTEX_STEP_MANAGER_FEEDBACK_STATUS_UNSPECIFIED',
  CORTEX_STEP_MANAGER_FEEDBACK_STATUS_APPROVED: 'CORTEX_STEP_MANAGER_FEEDBACK_STATUS_APPROVED',
  CORTEX_STEP_MANAGER_FEEDBACK_STATUS_DENIED: 'CORTEX_STEP_MANAGER_FEEDBACK_STATUS_DENIED',
  CORTEX_STEP_MANAGER_FEEDBACK_STATUS_ERROR: 'CORTEX_STEP_MANAGER_FEEDBACK_STATUS_ERROR',
} as const;

export type CortexStepManagerFeedbackStatus =
  | 'CORTEX_STEP_MANAGER_FEEDBACK_STATUS_UNSPECIFIED'
  | 0
  | 'CORTEX_STEP_MANAGER_FEEDBACK_STATUS_APPROVED'
  | 1
  | 'CORTEX_STEP_MANAGER_FEEDBACK_STATUS_DENIED'
  | 2
  | 'CORTEX_STEP_MANAGER_FEEDBACK_STATUS_ERROR'
  | 3

export type CortexStepManagerFeedbackStatus__Output = typeof CortexStepManagerFeedbackStatus[keyof typeof CortexStepManagerFeedbackStatus]
