// Original file: exa/cortex_pb/cortex.proto

export const CortexStepStatus = {
  CORTEX_STEP_STATUS_UNSPECIFIED: 'CORTEX_STEP_STATUS_UNSPECIFIED',
  CORTEX_STEP_STATUS_GENERATING: 'CORTEX_STEP_STATUS_GENERATING',
  CORTEX_STEP_STATUS_HALTED: 'CORTEX_STEP_STATUS_HALTED',
  CORTEX_STEP_STATUS_PENDING: 'CORTEX_STEP_STATUS_PENDING',
  CORTEX_STEP_STATUS_RUNNING: 'CORTEX_STEP_STATUS_RUNNING',
  CORTEX_STEP_STATUS_WAITING: 'CORTEX_STEP_STATUS_WAITING',
  CORTEX_STEP_STATUS_DONE: 'CORTEX_STEP_STATUS_DONE',
  CORTEX_STEP_STATUS_INVALID: 'CORTEX_STEP_STATUS_INVALID',
  CORTEX_STEP_STATUS_CLEARED: 'CORTEX_STEP_STATUS_CLEARED',
  CORTEX_STEP_STATUS_CANCELED: 'CORTEX_STEP_STATUS_CANCELED',
  CORTEX_STEP_STATUS_ERROR: 'CORTEX_STEP_STATUS_ERROR',
  CORTEX_STEP_STATUS_SKIPPING: 'CORTEX_STEP_STATUS_SKIPPING',
} as const;

export type CortexStepStatus =
  | 'CORTEX_STEP_STATUS_UNSPECIFIED'
  | 0
  | 'CORTEX_STEP_STATUS_GENERATING'
  | 8
  | 'CORTEX_STEP_STATUS_HALTED'
  | 10
  | 'CORTEX_STEP_STATUS_PENDING'
  | 1
  | 'CORTEX_STEP_STATUS_RUNNING'
  | 2
  | 'CORTEX_STEP_STATUS_WAITING'
  | 9
  | 'CORTEX_STEP_STATUS_DONE'
  | 3
  | 'CORTEX_STEP_STATUS_INVALID'
  | 4
  | 'CORTEX_STEP_STATUS_CLEARED'
  | 5
  | 'CORTEX_STEP_STATUS_CANCELED'
  | 6
  | 'CORTEX_STEP_STATUS_ERROR'
  | 7
  | 'CORTEX_STEP_STATUS_SKIPPING'
  | 11

export type CortexStepStatus__Output = typeof CortexStepStatus[keyof typeof CortexStepStatus]
