// Original file: exa/cortex_pb/cortex.proto

import type { CortexStepType as _exa_cortex_pb_CortexStepType, CortexStepType__Output as _exa_cortex_pb_CortexStepType__Output } from '../../exa/cortex_pb/CortexStepType';
import type { CortexStepStatus as _exa_cortex_pb_CortexStepStatus, CortexStepStatus__Output as _exa_cortex_pb_CortexStepStatus__Output } from '../../exa/cortex_pb/CortexStepStatus';
import type { CortexStepMetadata as _exa_cortex_pb_CortexStepMetadata, CortexStepMetadata__Output as _exa_cortex_pb_CortexStepMetadata__Output } from '../../exa/cortex_pb/CortexStepMetadata';
import type { CortexTrajectory as _exa_cortex_pb_CortexTrajectory, CortexTrajectory__Output as _exa_cortex_pb_CortexTrajectory__Output } from '../../exa/cortex_pb/CortexTrajectory';
import type { CortexStepDummy as _exa_cortex_pb_CortexStepDummy, CortexStepDummy__Output as _exa_cortex_pb_CortexStepDummy__Output } from '../../exa/cortex_pb/CortexStepDummy';
import type { CortexStepPlanInput as _exa_cortex_pb_CortexStepPlanInput, CortexStepPlanInput__Output as _exa_cortex_pb_CortexStepPlanInput__Output } from '../../exa/cortex_pb/CortexStepPlanInput';
import type { CortexStepMquery as _exa_cortex_pb_CortexStepMquery, CortexStepMquery__Output as _exa_cortex_pb_CortexStepMquery__Output } from '../../exa/cortex_pb/CortexStepMquery';
import type { CortexStepCodeAction as _exa_cortex_pb_CortexStepCodeAction, CortexStepCodeAction__Output as _exa_cortex_pb_CortexStepCodeAction__Output } from '../../exa/cortex_pb/CortexStepCodeAction';
import type { CortexStepGitCommit as _exa_cortex_pb_CortexStepGitCommit, CortexStepGitCommit__Output as _exa_cortex_pb_CortexStepGitCommit__Output } from '../../exa/cortex_pb/CortexStepGitCommit';
import type { CortexStepFinish as _exa_cortex_pb_CortexStepFinish, CortexStepFinish__Output as _exa_cortex_pb_CortexStepFinish__Output } from '../../exa/cortex_pb/CortexStepFinish';
import type { CortexStepGrepSearch as _exa_cortex_pb_CortexStepGrepSearch, CortexStepGrepSearch__Output as _exa_cortex_pb_CortexStepGrepSearch__Output } from '../../exa/cortex_pb/CortexStepGrepSearch';
import type { CortexStepViewFile as _exa_cortex_pb_CortexStepViewFile, CortexStepViewFile__Output as _exa_cortex_pb_CortexStepViewFile__Output } from '../../exa/cortex_pb/CortexStepViewFile';
import type { CortexStepListDirectory as _exa_cortex_pb_CortexStepListDirectory, CortexStepListDirectory__Output as _exa_cortex_pb_CortexStepListDirectory__Output } from '../../exa/cortex_pb/CortexStepListDirectory';
import type { CortexStepCompile as _exa_cortex_pb_CortexStepCompile, CortexStepCompile__Output as _exa_cortex_pb_CortexStepCompile__Output } from '../../exa/cortex_pb/CortexStepCompile';
import type { CortexStepInformPlanner as _exa_cortex_pb_CortexStepInformPlanner, CortexStepInformPlanner__Output as _exa_cortex_pb_CortexStepInformPlanner__Output } from '../../exa/cortex_pb/CortexStepInformPlanner';
import type { CortexStepUserInput as _exa_cortex_pb_CortexStepUserInput, CortexStepUserInput__Output as _exa_cortex_pb_CortexStepUserInput__Output } from '../../exa/cortex_pb/CortexStepUserInput';
import type { CortexStepPlannerResponse as _exa_cortex_pb_CortexStepPlannerResponse, CortexStepPlannerResponse__Output as _exa_cortex_pb_CortexStepPlannerResponse__Output } from '../../exa/cortex_pb/CortexStepPlannerResponse';
import type { CortexStepFileBreakdown as _exa_cortex_pb_CortexStepFileBreakdown, CortexStepFileBreakdown__Output as _exa_cortex_pb_CortexStepFileBreakdown__Output } from '../../exa/cortex_pb/CortexStepFileBreakdown';
import type { CortexStepViewCodeItem as _exa_cortex_pb_CortexStepViewCodeItem, CortexStepViewCodeItem__Output as _exa_cortex_pb_CortexStepViewCodeItem__Output } from '../../exa/cortex_pb/CortexStepViewCodeItem';
import type { CortexStepWriteToFile as _exa_cortex_pb_CortexStepWriteToFile, CortexStepWriteToFile__Output as _exa_cortex_pb_CortexStepWriteToFile__Output } from '../../exa/cortex_pb/CortexStepWriteToFile';
import type { CortexStepErrorMessage as _exa_cortex_pb_CortexStepErrorMessage, CortexStepErrorMessage__Output as _exa_cortex_pb_CortexStepErrorMessage__Output } from '../../exa/cortex_pb/CortexStepErrorMessage';
import type { CortexStepClusterQuery as _exa_cortex_pb_CortexStepClusterQuery, CortexStepClusterQuery__Output as _exa_cortex_pb_CortexStepClusterQuery__Output } from '../../exa/cortex_pb/CortexStepClusterQuery';
import type { CortexStepListClusters as _exa_cortex_pb_CortexStepListClusters, CortexStepListClusters__Output as _exa_cortex_pb_CortexStepListClusters__Output } from '../../exa/cortex_pb/CortexStepListClusters';
import type { CortexStepInspectCluster as _exa_cortex_pb_CortexStepInspectCluster, CortexStepInspectCluster__Output as _exa_cortex_pb_CortexStepInspectCluster__Output } from '../../exa/cortex_pb/CortexStepInspectCluster';
import type { CortexStepRunCommand as _exa_cortex_pb_CortexStepRunCommand, CortexStepRunCommand__Output as _exa_cortex_pb_CortexStepRunCommand__Output } from '../../exa/cortex_pb/CortexStepRunCommand';
import type { CortexStepRelatedFiles as _exa_cortex_pb_CortexStepRelatedFiles, CortexStepRelatedFiles__Output as _exa_cortex_pb_CortexStepRelatedFiles__Output } from '../../exa/cortex_pb/CortexStepRelatedFiles';
import type { CortexStepCheckpoint as _exa_cortex_pb_CortexStepCheckpoint, CortexStepCheckpoint__Output as _exa_cortex_pb_CortexStepCheckpoint__Output } from '../../exa/cortex_pb/CortexStepCheckpoint';
import type { CortexErrorDetails as _exa_cortex_pb_CortexErrorDetails, CortexErrorDetails__Output as _exa_cortex_pb_CortexErrorDetails__Output } from '../../exa/cortex_pb/CortexErrorDetails';
import type { CortexStepProposeCode as _exa_cortex_pb_CortexStepProposeCode, CortexStepProposeCode__Output as _exa_cortex_pb_CortexStepProposeCode__Output } from '../../exa/cortex_pb/CortexStepProposeCode';
import type { ExecutionAsyncLevel as _exa_cortex_pb_ExecutionAsyncLevel, ExecutionAsyncLevel__Output as _exa_cortex_pb_ExecutionAsyncLevel__Output } from '../../exa/cortex_pb/ExecutionAsyncLevel';
import type { CortexStepFind as _exa_cortex_pb_CortexStepFind, CortexStepFind__Output as _exa_cortex_pb_CortexStepFind__Output } from '../../exa/cortex_pb/CortexStepFind';
import type { CortexStepSearchKnowledgeBase as _exa_cortex_pb_CortexStepSearchKnowledgeBase, CortexStepSearchKnowledgeBase__Output as _exa_cortex_pb_CortexStepSearchKnowledgeBase__Output } from '../../exa/cortex_pb/CortexStepSearchKnowledgeBase';
import type { CortexStepSuggestedResponses as _exa_cortex_pb_CortexStepSuggestedResponses, CortexStepSuggestedResponses__Output as _exa_cortex_pb_CortexStepSuggestedResponses__Output } from '../../exa/cortex_pb/CortexStepSuggestedResponses';
import type { CortexStepCommandStatus as _exa_cortex_pb_CortexStepCommandStatus, CortexStepCommandStatus__Output as _exa_cortex_pb_CortexStepCommandStatus__Output } from '../../exa/cortex_pb/CortexStepCommandStatus';
import type { CortexStepMemory as _exa_cortex_pb_CortexStepMemory, CortexStepMemory__Output as _exa_cortex_pb_CortexStepMemory__Output } from '../../exa/cortex_pb/CortexStepMemory';
import type { CortexStepLookupKnowledgeBase as _exa_cortex_pb_CortexStepLookupKnowledgeBase, CortexStepLookupKnowledgeBase__Output as _exa_cortex_pb_CortexStepLookupKnowledgeBase__Output } from '../../exa/cortex_pb/CortexStepLookupKnowledgeBase';
import type { CortexStepReadUrlContent as _exa_cortex_pb_CortexStepReadUrlContent, CortexStepReadUrlContent__Output as _exa_cortex_pb_CortexStepReadUrlContent__Output } from '../../exa/cortex_pb/CortexStepReadUrlContent';
import type { CortexStepViewContentChunk as _exa_cortex_pb_CortexStepViewContentChunk, CortexStepViewContentChunk__Output as _exa_cortex_pb_CortexStepViewContentChunk__Output } from '../../exa/cortex_pb/CortexStepViewContentChunk';
import type { CortexStepSearchWeb as _exa_cortex_pb_CortexStepSearchWeb, CortexStepSearchWeb__Output as _exa_cortex_pb_CortexStepSearchWeb__Output } from '../../exa/cortex_pb/CortexStepSearchWeb';
import type { CortexStepRetrieveMemory as _exa_cortex_pb_CortexStepRetrieveMemory, CortexStepRetrieveMemory__Output as _exa_cortex_pb_CortexStepRetrieveMemory__Output } from '../../exa/cortex_pb/CortexStepRetrieveMemory';
import type { CortexStepAutoCascadeBroadcast as _exa_cortex_pb_CortexStepAutoCascadeBroadcast, CortexStepAutoCascadeBroadcast__Output as _exa_cortex_pb_CortexStepAutoCascadeBroadcast__Output } from '../../exa/cortex_pb/CortexStepAutoCascadeBroadcast';
import type { CortexStepCustomTool as _exa_cortex_pb_CortexStepCustomTool, CortexStepCustomTool__Output as _exa_cortex_pb_CortexStepCustomTool__Output } from '../../exa/cortex_pb/CortexStepCustomTool';
import type { CortexStepCreateRecipe as _exa_cortex_pb_CortexStepCreateRecipe, CortexStepCreateRecipe__Output as _exa_cortex_pb_CortexStepCreateRecipe__Output } from '../../exa/cortex_pb/CortexStepCreateRecipe';
import type { CortexStepMcpTool as _exa_cortex_pb_CortexStepMcpTool, CortexStepMcpTool__Output as _exa_cortex_pb_CortexStepMcpTool__Output } from '../../exa/cortex_pb/CortexStepMcpTool';
import type { CortexStepManagerFeedback as _exa_cortex_pb_CortexStepManagerFeedback, CortexStepManagerFeedback__Output as _exa_cortex_pb_CortexStepManagerFeedback__Output } from '../../exa/cortex_pb/CortexStepManagerFeedback';
import type { CortexStepToolCallProposal as _exa_cortex_pb_CortexStepToolCallProposal, CortexStepToolCallProposal__Output as _exa_cortex_pb_CortexStepToolCallProposal__Output } from '../../exa/cortex_pb/CortexStepToolCallProposal';
import type { CortexStepToolCallChoice as _exa_cortex_pb_CortexStepToolCallChoice, CortexStepToolCallChoice__Output as _exa_cortex_pb_CortexStepToolCallChoice__Output } from '../../exa/cortex_pb/CortexStepToolCallChoice';
import type { CortexStepTrajectoryChoice as _exa_cortex_pb_CortexStepTrajectoryChoice, CortexStepTrajectoryChoice__Output as _exa_cortex_pb_CortexStepTrajectoryChoice__Output } from '../../exa/cortex_pb/CortexStepTrajectoryChoice';
import type { CortexStepProxyWebServer as _exa_cortex_pb_CortexStepProxyWebServer, CortexStepProxyWebServer__Output as _exa_cortex_pb_CortexStepProxyWebServer__Output } from '../../exa/cortex_pb/CortexStepProxyWebServer';
import type { CortexStepDeployWebApp as _exa_cortex_pb_CortexStepDeployWebApp, CortexStepDeployWebApp__Output as _exa_cortex_pb_CortexStepDeployWebApp__Output } from '../../exa/cortex_pb/CortexStepDeployWebApp';
import type { CortexStepClipboard as _exa_cortex_pb_CortexStepClipboard, CortexStepClipboard__Output as _exa_cortex_pb_CortexStepClipboard__Output } from '../../exa/cortex_pb/CortexStepClipboard';
import type { RequestedInteraction as _exa_cortex_pb_RequestedInteraction, RequestedInteraction__Output as _exa_cortex_pb_RequestedInteraction__Output } from '../../exa/cortex_pb/RequestedInteraction';
import type { CortexStepReadDeploymentConfig as _exa_cortex_pb_CortexStepReadDeploymentConfig, CortexStepReadDeploymentConfig__Output as _exa_cortex_pb_CortexStepReadDeploymentConfig__Output } from '../../exa/cortex_pb/CortexStepReadDeploymentConfig';
import type { CortexStepViewFileOutline as _exa_cortex_pb_CortexStepViewFileOutline, CortexStepViewFileOutline__Output as _exa_cortex_pb_CortexStepViewFileOutline__Output } from '../../exa/cortex_pb/CortexStepViewFileOutline';
import type { CortexStepCheckDeployStatus as _exa_cortex_pb_CortexStepCheckDeployStatus, CortexStepCheckDeployStatus__Output as _exa_cortex_pb_CortexStepCheckDeployStatus__Output } from '../../exa/cortex_pb/CortexStepCheckDeployStatus';
import type { CortexStepPostPrReview as _exa_cortex_pb_CortexStepPostPrReview, CortexStepPostPrReview__Output as _exa_cortex_pb_CortexStepPostPrReview__Output } from '../../exa/cortex_pb/CortexStepPostPrReview';
import type { CortexStepReadKnowledgeBaseItem as _exa_cortex_pb_CortexStepReadKnowledgeBaseItem, CortexStepReadKnowledgeBaseItem__Output as _exa_cortex_pb_CortexStepReadKnowledgeBaseItem__Output } from '../../exa/cortex_pb/CortexStepReadKnowledgeBaseItem';
import type { CortexStepListResources as _exa_cortex_pb_CortexStepListResources, CortexStepListResources__Output as _exa_cortex_pb_CortexStepListResources__Output } from '../../exa/cortex_pb/CortexStepListResources';
import type { CortexStepReadResource as _exa_cortex_pb_CortexStepReadResource, CortexStepReadResource__Output as _exa_cortex_pb_CortexStepReadResource__Output } from '../../exa/cortex_pb/CortexStepReadResource';
import type { CortexStepLintDiff as _exa_cortex_pb_CortexStepLintDiff, CortexStepLintDiff__Output as _exa_cortex_pb_CortexStepLintDiff__Output } from '../../exa/cortex_pb/CortexStepLintDiff';
import type { CortexStepFindAllReferences as _exa_cortex_pb_CortexStepFindAllReferences, CortexStepFindAllReferences__Output as _exa_cortex_pb_CortexStepFindAllReferences__Output } from '../../exa/cortex_pb/CortexStepFindAllReferences';
import type { CortexStepBrainUpdate as _exa_cortex_pb_CortexStepBrainUpdate, CortexStepBrainUpdate__Output as _exa_cortex_pb_CortexStepBrainUpdate__Output } from '../../exa/cortex_pb/CortexStepBrainUpdate';
import type { CortexStepRunExtensionCode as _exa_cortex_pb_CortexStepRunExtensionCode, CortexStepRunExtensionCode__Output as _exa_cortex_pb_CortexStepRunExtensionCode__Output } from '../../exa/cortex_pb/CortexStepRunExtensionCode';
import type { UserStepAnnotations as _exa_cortex_pb_UserStepAnnotations, UserStepAnnotations__Output as _exa_cortex_pb_UserStepAnnotations__Output } from '../../exa/cortex_pb/UserStepAnnotations';
import type { CortexStepAddAnnotation as _exa_cortex_pb_CortexStepAddAnnotation, CortexStepAddAnnotation__Output as _exa_cortex_pb_CortexStepAddAnnotation__Output } from '../../exa/cortex_pb/CortexStepAddAnnotation';
import type { CortexStepProposalFeedback as _exa_cortex_pb_CortexStepProposalFeedback, CortexStepProposalFeedback__Output as _exa_cortex_pb_CortexStepProposalFeedback__Output } from '../../exa/cortex_pb/CortexStepProposalFeedback';
import type { CortexStepTrajectorySearch as _exa_cortex_pb_CortexStepTrajectorySearch, CortexStepTrajectorySearch__Output as _exa_cortex_pb_CortexStepTrajectorySearch__Output } from '../../exa/cortex_pb/CortexStepTrajectorySearch';
import type { CortexStepReadTerminal as _exa_cortex_pb_CortexStepReadTerminal, CortexStepReadTerminal__Output as _exa_cortex_pb_CortexStepReadTerminal__Output } from '../../exa/cortex_pb/CortexStepReadTerminal';
import type { CortexStepArtifactSummary as _exa_cortex_pb_CortexStepArtifactSummary, CortexStepArtifactSummary__Output as _exa_cortex_pb_CortexStepArtifactSummary__Output } from '../../exa/cortex_pb/CortexStepArtifactSummary';
import type { CortexStepResolveTask as _exa_cortex_pb_CortexStepResolveTask, CortexStepResolveTask__Output as _exa_cortex_pb_CortexStepResolveTask__Output } from '../../exa/cortex_pb/CortexStepResolveTask';
import type { HookExecutionDetail as _exa_cortex_pb_HookExecutionDetail, HookExecutionDetail__Output as _exa_cortex_pb_HookExecutionDetail__Output } from '../../exa/cortex_pb/HookExecutionDetail';
import type { CortexStepTodoList as _exa_cortex_pb_CortexStepTodoList, CortexStepTodoList__Output as _exa_cortex_pb_CortexStepTodoList__Output } from '../../exa/cortex_pb/CortexStepTodoList';
import type { CortexStepBlocking as _exa_cortex_pb_CortexStepBlocking, CortexStepBlocking__Output as _exa_cortex_pb_CortexStepBlocking__Output } from '../../exa/cortex_pb/CortexStepBlocking';
import type { CortexStepExploreResponse as _exa_cortex_pb_CortexStepExploreResponse, CortexStepExploreResponse__Output as _exa_cortex_pb_CortexStepExploreResponse__Output } from '../../exa/cortex_pb/CortexStepExploreResponse';
import type { CortexStepReadNotebook as _exa_cortex_pb_CortexStepReadNotebook, CortexStepReadNotebook__Output as _exa_cortex_pb_CortexStepReadNotebook__Output } from '../../exa/cortex_pb/CortexStepReadNotebook';
import type { CortexStepEditNotebook as _exa_cortex_pb_CortexStepEditNotebook, CortexStepEditNotebook__Output as _exa_cortex_pb_CortexStepEditNotebook__Output } from '../../exa/cortex_pb/CortexStepEditNotebook';
import type { CortexStepCodeMap as _exa_cortex_pb_CortexStepCodeMap, CortexStepCodeMap__Output as _exa_cortex_pb_CortexStepCodeMap__Output } from '../../exa/cortex_pb/CortexStepCodeMap';
import type { CortexStepEditCodeMap as _exa_cortex_pb_CortexStepEditCodeMap, CortexStepEditCodeMap__Output as _exa_cortex_pb_CortexStepEditCodeMap__Output } from '../../exa/cortex_pb/CortexStepEditCodeMap';
import type { CortexStepSupercompleteActiveDoc as _exa_cortex_pb_CortexStepSupercompleteActiveDoc, CortexStepSupercompleteActiveDoc__Output as _exa_cortex_pb_CortexStepSupercompleteActiveDoc__Output } from '../../exa/cortex_pb/CortexStepSupercompleteActiveDoc';
import type { CortexStepFindCodeContext as _exa_cortex_pb_CortexStepFindCodeContext, CortexStepFindCodeContext__Output as _exa_cortex_pb_CortexStepFindCodeContext__Output } from '../../exa/cortex_pb/CortexStepFindCodeContext';
import type { CortexStepSupercompleteFeedback as _exa_cortex_pb_CortexStepSupercompleteFeedback, CortexStepSupercompleteFeedback__Output as _exa_cortex_pb_CortexStepSupercompleteFeedback__Output } from '../../exa/cortex_pb/CortexStepSupercompleteFeedback';
import type { CortexStepLintFixMessage as _exa_cortex_pb_CortexStepLintFixMessage, CortexStepLintFixMessage__Output as _exa_cortex_pb_CortexStepLintFixMessage__Output } from '../../exa/cortex_pb/CortexStepLintFixMessage';
import type { CortexStepGrepSearchV2 as _exa_cortex_pb_CortexStepGrepSearchV2, CortexStepGrepSearchV2__Output as _exa_cortex_pb_CortexStepGrepSearchV2__Output } from '../../exa/cortex_pb/CortexStepGrepSearchV2';
import type { CortexStepUpsertCodemap as _exa_cortex_pb_CortexStepUpsertCodemap, CortexStepUpsertCodemap__Output as _exa_cortex_pb_CortexStepUpsertCodemap__Output } from '../../exa/cortex_pb/CortexStepUpsertCodemap';
import type { CortexStepSuggestCodemap as _exa_cortex_pb_CortexStepSuggestCodemap, CortexStepSuggestCodemap__Output as _exa_cortex_pb_CortexStepSuggestCodemap__Output } from '../../exa/cortex_pb/CortexStepSuggestCodemap';
import type { CortexStepSmartFriend as _exa_cortex_pb_CortexStepSmartFriend, CortexStepSmartFriend__Output as _exa_cortex_pb_CortexStepSmartFriend__Output } from '../../exa/cortex_pb/CortexStepSmartFriend';
import type { CortexStepReportBugs as _exa_cortex_pb_CortexStepReportBugs, CortexStepReportBugs__Output as _exa_cortex_pb_CortexStepReportBugs__Output } from '../../exa/cortex_pb/CortexStepReportBugs';
import type { CortexStepExitPlanMode as _exa_cortex_pb_CortexStepExitPlanMode, CortexStepExitPlanMode__Output as _exa_cortex_pb_CortexStepExitPlanMode__Output } from '../../exa/cortex_pb/CortexStepExitPlanMode';
import type { CortexStepAskUserQuestion as _exa_cortex_pb_CortexStepAskUserQuestion, CortexStepAskUserQuestion__Output as _exa_cortex_pb_CortexStepAskUserQuestion__Output } from '../../exa/cortex_pb/CortexStepAskUserQuestion';
import type { CortexStepSkill as _exa_cortex_pb_CortexStepSkill, CortexStepSkill__Output as _exa_cortex_pb_CortexStepSkill__Output } from '../../exa/cortex_pb/CortexStepSkill';
import type { CortexStepSupercompleteEphemeralFeedback as _exa_cortex_pb_CortexStepSupercompleteEphemeralFeedback, CortexStepSupercompleteEphemeralFeedback__Output as _exa_cortex_pb_CortexStepSupercompleteEphemeralFeedback__Output } from '../../exa/cortex_pb/CortexStepSupercompleteEphemeralFeedback';
import type { CortexStepArenaTrajectoryConverge as _exa_cortex_pb_CortexStepArenaTrajectoryConverge, CortexStepArenaTrajectoryConverge__Output as _exa_cortex_pb_CortexStepArenaTrajectoryConverge__Output } from '../../exa/cortex_pb/CortexStepArenaTrajectoryConverge';

export interface CortexTrajectoryStep {
  'type'?: (_exa_cortex_pb_CortexStepType);
  'status'?: (_exa_cortex_pb_CortexStepStatus);
  'metadata'?: (_exa_cortex_pb_CortexStepMetadata | null);
  'subtrajectory'?: (_exa_cortex_pb_CortexTrajectory | null);
  'dummy'?: (_exa_cortex_pb_CortexStepDummy | null);
  'planInput'?: (_exa_cortex_pb_CortexStepPlanInput | null);
  'mquery'?: (_exa_cortex_pb_CortexStepMquery | null);
  'codeAction'?: (_exa_cortex_pb_CortexStepCodeAction | null);
  'gitCommit'?: (_exa_cortex_pb_CortexStepGitCommit | null);
  'finish'?: (_exa_cortex_pb_CortexStepFinish | null);
  'grepSearch'?: (_exa_cortex_pb_CortexStepGrepSearch | null);
  'viewFile'?: (_exa_cortex_pb_CortexStepViewFile | null);
  'listDirectory'?: (_exa_cortex_pb_CortexStepListDirectory | null);
  'compile'?: (_exa_cortex_pb_CortexStepCompile | null);
  'informPlanner'?: (_exa_cortex_pb_CortexStepInformPlanner | null);
  'userInput'?: (_exa_cortex_pb_CortexStepUserInput | null);
  'plannerResponse'?: (_exa_cortex_pb_CortexStepPlannerResponse | null);
  'fileBreakdown'?: (_exa_cortex_pb_CortexStepFileBreakdown | null);
  'viewCodeItem'?: (_exa_cortex_pb_CortexStepViewCodeItem | null);
  'writeToFile'?: (_exa_cortex_pb_CortexStepWriteToFile | null);
  'errorMessage'?: (_exa_cortex_pb_CortexStepErrorMessage | null);
  'clusterQuery'?: (_exa_cortex_pb_CortexStepClusterQuery | null);
  'listClusters'?: (_exa_cortex_pb_CortexStepListClusters | null);
  'inspectCluster'?: (_exa_cortex_pb_CortexStepInspectCluster | null);
  'runCommand'?: (_exa_cortex_pb_CortexStepRunCommand | null);
  'relatedFiles'?: (_exa_cortex_pb_CortexStepRelatedFiles | null);
  'checkpoint'?: (_exa_cortex_pb_CortexStepCheckpoint | null);
  'error'?: (_exa_cortex_pb_CortexErrorDetails | null);
  'proposeCode'?: (_exa_cortex_pb_CortexStepProposeCode | null);
  'asyncLevelOverride'?: (_exa_cortex_pb_ExecutionAsyncLevel);
  'find'?: (_exa_cortex_pb_CortexStepFind | null);
  'searchKnowledgeBase'?: (_exa_cortex_pb_CortexStepSearchKnowledgeBase | null);
  'suggestedResponses'?: (_exa_cortex_pb_CortexStepSuggestedResponses | null);
  'commandStatus'?: (_exa_cortex_pb_CortexStepCommandStatus | null);
  'memory'?: (_exa_cortex_pb_CortexStepMemory | null);
  'lookupKnowledgeBase'?: (_exa_cortex_pb_CortexStepLookupKnowledgeBase | null);
  'readUrlContent'?: (_exa_cortex_pb_CortexStepReadUrlContent | null);
  'viewContentChunk'?: (_exa_cortex_pb_CortexStepViewContentChunk | null);
  'searchWeb'?: (_exa_cortex_pb_CortexStepSearchWeb | null);
  'retrieveMemory'?: (_exa_cortex_pb_CortexStepRetrieveMemory | null);
  'autoCascadeBroadcast'?: (_exa_cortex_pb_CortexStepAutoCascadeBroadcast | null);
  'customTool'?: (_exa_cortex_pb_CortexStepCustomTool | null);
  'createRecipe'?: (_exa_cortex_pb_CortexStepCreateRecipe | null);
  'mcpTool'?: (_exa_cortex_pb_CortexStepMcpTool | null);
  'managerFeedback'?: (_exa_cortex_pb_CortexStepManagerFeedback | null);
  'toolCallProposal'?: (_exa_cortex_pb_CortexStepToolCallProposal | null);
  'toolCallChoice'?: (_exa_cortex_pb_CortexStepToolCallChoice | null);
  'subtrajectories'?: (_exa_cortex_pb_CortexTrajectory)[];
  'trajectoryChoice'?: (_exa_cortex_pb_CortexStepTrajectoryChoice | null);
  'proxyWebServer'?: (_exa_cortex_pb_CortexStepProxyWebServer | null);
  'deployWebApp'?: (_exa_cortex_pb_CortexStepDeployWebApp | null);
  'clipboard'?: (_exa_cortex_pb_CortexStepClipboard | null);
  'requestedInteraction'?: (_exa_cortex_pb_RequestedInteraction | null);
  'readDeploymentConfig'?: (_exa_cortex_pb_CortexStepReadDeploymentConfig | null);
  'viewFileOutline'?: (_exa_cortex_pb_CortexStepViewFileOutline | null);
  'checkDeployStatus'?: (_exa_cortex_pb_CortexStepCheckDeployStatus | null);
  'postPrReview'?: (_exa_cortex_pb_CortexStepPostPrReview | null);
  'readKnowledgeBaseItem'?: (_exa_cortex_pb_CortexStepReadKnowledgeBaseItem | null);
  'listResources'?: (_exa_cortex_pb_CortexStepListResources | null);
  'readResource'?: (_exa_cortex_pb_CortexStepReadResource | null);
  'lintDiff'?: (_exa_cortex_pb_CortexStepLintDiff | null);
  'findAllReferences'?: (_exa_cortex_pb_CortexStepFindAllReferences | null);
  'brainUpdate'?: (_exa_cortex_pb_CortexStepBrainUpdate | null);
  'runExtensionCode'?: (_exa_cortex_pb_CortexStepRunExtensionCode | null);
  'userAnnotations'?: (_exa_cortex_pb_UserStepAnnotations | null);
  'addAnnotation'?: (_exa_cortex_pb_CortexStepAddAnnotation | null);
  'proposalFeedback'?: (_exa_cortex_pb_CortexStepProposalFeedback | null);
  'trajectorySearch'?: (_exa_cortex_pb_CortexStepTrajectorySearch | null);
  'readTerminal'?: (_exa_cortex_pb_CortexStepReadTerminal | null);
  'artifactSummary'?: (_exa_cortex_pb_CortexStepArtifactSummary | null);
  'resolveTask'?: (_exa_cortex_pb_CortexStepResolveTask | null);
  'preToolUseHooks'?: (_exa_cortex_pb_HookExecutionDetail)[];
  'postToolUseHooks'?: (_exa_cortex_pb_HookExecutionDetail)[];
  'todoList'?: (_exa_cortex_pb_CortexStepTodoList | null);
  'blocking'?: (_exa_cortex_pb_CortexStepBlocking | null);
  'exploreResponse'?: (_exa_cortex_pb_CortexStepExploreResponse | null);
  'readNotebook'?: (_exa_cortex_pb_CortexStepReadNotebook | null);
  'editNotebook'?: (_exa_cortex_pb_CortexStepEditNotebook | null);
  'codeMap'?: (_exa_cortex_pb_CortexStepCodeMap | null);
  'editCodeMap'?: (_exa_cortex_pb_CortexStepEditCodeMap | null);
  'supercompleteActiveDoc'?: (_exa_cortex_pb_CortexStepSupercompleteActiveDoc | null);
  'findCodeContext'?: (_exa_cortex_pb_CortexStepFindCodeContext | null);
  'supercompleteFeedback'?: (_exa_cortex_pb_CortexStepSupercompleteFeedback | null);
  'lintFixMessage'?: (_exa_cortex_pb_CortexStepLintFixMessage | null);
  'grepSearchV2'?: (_exa_cortex_pb_CortexStepGrepSearchV2 | null);
  'upsertCodemap'?: (_exa_cortex_pb_CortexStepUpsertCodemap | null);
  'suggestCodemap'?: (_exa_cortex_pb_CortexStepSuggestCodemap | null);
  'smartFriend'?: (_exa_cortex_pb_CortexStepSmartFriend | null);
  'shieldFromCancellation'?: (boolean);
  'reportBugs'?: (_exa_cortex_pb_CortexStepReportBugs | null);
  'exitPlanMode'?: (_exa_cortex_pb_CortexStepExitPlanMode | null);
  'askUserQuestion'?: (_exa_cortex_pb_CortexStepAskUserQuestion | null);
  'skill'?: (_exa_cortex_pb_CortexStepSkill | null);
  'supercompleteEphemeralFeedback'?: (_exa_cortex_pb_CortexStepSupercompleteEphemeralFeedback | null);
  'arenaTrajectoryConverge'?: (_exa_cortex_pb_CortexStepArenaTrajectoryConverge | null);
  'step'?: "dummy"|"finish"|"planInput"|"mquery"|"codeAction"|"gitCommit"|"grepSearch"|"viewFile"|"listDirectory"|"compile"|"informPlanner"|"userInput"|"plannerResponse"|"fileBreakdown"|"viewCodeItem"|"writeToFile"|"errorMessage"|"clusterQuery"|"listClusters"|"inspectCluster"|"runCommand"|"relatedFiles"|"checkpoint"|"proposeCode"|"find"|"searchKnowledgeBase"|"suggestedResponses"|"commandStatus"|"memory"|"lookupKnowledgeBase"|"readUrlContent"|"viewContentChunk"|"searchWeb"|"retrieveMemory"|"autoCascadeBroadcast"|"customTool"|"createRecipe"|"mcpTool"|"managerFeedback"|"toolCallProposal"|"toolCallChoice"|"trajectoryChoice"|"proxyWebServer"|"deployWebApp"|"clipboard"|"readDeploymentConfig"|"viewFileOutline"|"checkDeployStatus"|"postPrReview"|"readKnowledgeBaseItem"|"listResources"|"readResource"|"lintDiff"|"findAllReferences"|"brainUpdate"|"runExtensionCode"|"addAnnotation"|"proposalFeedback"|"trajectorySearch"|"readTerminal"|"artifactSummary"|"resolveTask"|"todoList"|"blocking"|"exploreResponse"|"readNotebook"|"editNotebook"|"codeMap"|"editCodeMap"|"supercompleteActiveDoc"|"findCodeContext"|"supercompleteFeedback"|"lintFixMessage"|"grepSearchV2"|"upsertCodemap"|"suggestCodemap"|"smartFriend"|"reportBugs"|"exitPlanMode"|"askUserQuestion"|"skill"|"supercompleteEphemeralFeedback"|"arenaTrajectoryConverge";
  '_shieldFromCancellation'?: "shieldFromCancellation";
}

export interface CortexTrajectoryStep__Output {
  'type': (_exa_cortex_pb_CortexStepType__Output);
  'status': (_exa_cortex_pb_CortexStepStatus__Output);
  'metadata': (_exa_cortex_pb_CortexStepMetadata__Output | null);
  'subtrajectory': (_exa_cortex_pb_CortexTrajectory__Output | null);
  'dummy'?: (_exa_cortex_pb_CortexStepDummy__Output | null);
  'planInput'?: (_exa_cortex_pb_CortexStepPlanInput__Output | null);
  'mquery'?: (_exa_cortex_pb_CortexStepMquery__Output | null);
  'codeAction'?: (_exa_cortex_pb_CortexStepCodeAction__Output | null);
  'gitCommit'?: (_exa_cortex_pb_CortexStepGitCommit__Output | null);
  'finish'?: (_exa_cortex_pb_CortexStepFinish__Output | null);
  'grepSearch'?: (_exa_cortex_pb_CortexStepGrepSearch__Output | null);
  'viewFile'?: (_exa_cortex_pb_CortexStepViewFile__Output | null);
  'listDirectory'?: (_exa_cortex_pb_CortexStepListDirectory__Output | null);
  'compile'?: (_exa_cortex_pb_CortexStepCompile__Output | null);
  'informPlanner'?: (_exa_cortex_pb_CortexStepInformPlanner__Output | null);
  'userInput'?: (_exa_cortex_pb_CortexStepUserInput__Output | null);
  'plannerResponse'?: (_exa_cortex_pb_CortexStepPlannerResponse__Output | null);
  'fileBreakdown'?: (_exa_cortex_pb_CortexStepFileBreakdown__Output | null);
  'viewCodeItem'?: (_exa_cortex_pb_CortexStepViewCodeItem__Output | null);
  'writeToFile'?: (_exa_cortex_pb_CortexStepWriteToFile__Output | null);
  'errorMessage'?: (_exa_cortex_pb_CortexStepErrorMessage__Output | null);
  'clusterQuery'?: (_exa_cortex_pb_CortexStepClusterQuery__Output | null);
  'listClusters'?: (_exa_cortex_pb_CortexStepListClusters__Output | null);
  'inspectCluster'?: (_exa_cortex_pb_CortexStepInspectCluster__Output | null);
  'runCommand'?: (_exa_cortex_pb_CortexStepRunCommand__Output | null);
  'relatedFiles'?: (_exa_cortex_pb_CortexStepRelatedFiles__Output | null);
  'checkpoint'?: (_exa_cortex_pb_CortexStepCheckpoint__Output | null);
  'error': (_exa_cortex_pb_CortexErrorDetails__Output | null);
  'proposeCode'?: (_exa_cortex_pb_CortexStepProposeCode__Output | null);
  'asyncLevelOverride': (_exa_cortex_pb_ExecutionAsyncLevel__Output);
  'find'?: (_exa_cortex_pb_CortexStepFind__Output | null);
  'searchKnowledgeBase'?: (_exa_cortex_pb_CortexStepSearchKnowledgeBase__Output | null);
  'suggestedResponses'?: (_exa_cortex_pb_CortexStepSuggestedResponses__Output | null);
  'commandStatus'?: (_exa_cortex_pb_CortexStepCommandStatus__Output | null);
  'memory'?: (_exa_cortex_pb_CortexStepMemory__Output | null);
  'lookupKnowledgeBase'?: (_exa_cortex_pb_CortexStepLookupKnowledgeBase__Output | null);
  'readUrlContent'?: (_exa_cortex_pb_CortexStepReadUrlContent__Output | null);
  'viewContentChunk'?: (_exa_cortex_pb_CortexStepViewContentChunk__Output | null);
  'searchWeb'?: (_exa_cortex_pb_CortexStepSearchWeb__Output | null);
  'retrieveMemory'?: (_exa_cortex_pb_CortexStepRetrieveMemory__Output | null);
  'autoCascadeBroadcast'?: (_exa_cortex_pb_CortexStepAutoCascadeBroadcast__Output | null);
  'customTool'?: (_exa_cortex_pb_CortexStepCustomTool__Output | null);
  'createRecipe'?: (_exa_cortex_pb_CortexStepCreateRecipe__Output | null);
  'mcpTool'?: (_exa_cortex_pb_CortexStepMcpTool__Output | null);
  'managerFeedback'?: (_exa_cortex_pb_CortexStepManagerFeedback__Output | null);
  'toolCallProposal'?: (_exa_cortex_pb_CortexStepToolCallProposal__Output | null);
  'toolCallChoice'?: (_exa_cortex_pb_CortexStepToolCallChoice__Output | null);
  'subtrajectories': (_exa_cortex_pb_CortexTrajectory__Output)[];
  'trajectoryChoice'?: (_exa_cortex_pb_CortexStepTrajectoryChoice__Output | null);
  'proxyWebServer'?: (_exa_cortex_pb_CortexStepProxyWebServer__Output | null);
  'deployWebApp'?: (_exa_cortex_pb_CortexStepDeployWebApp__Output | null);
  'clipboard'?: (_exa_cortex_pb_CortexStepClipboard__Output | null);
  'requestedInteraction': (_exa_cortex_pb_RequestedInteraction__Output | null);
  'readDeploymentConfig'?: (_exa_cortex_pb_CortexStepReadDeploymentConfig__Output | null);
  'viewFileOutline'?: (_exa_cortex_pb_CortexStepViewFileOutline__Output | null);
  'checkDeployStatus'?: (_exa_cortex_pb_CortexStepCheckDeployStatus__Output | null);
  'postPrReview'?: (_exa_cortex_pb_CortexStepPostPrReview__Output | null);
  'readKnowledgeBaseItem'?: (_exa_cortex_pb_CortexStepReadKnowledgeBaseItem__Output | null);
  'listResources'?: (_exa_cortex_pb_CortexStepListResources__Output | null);
  'readResource'?: (_exa_cortex_pb_CortexStepReadResource__Output | null);
  'lintDiff'?: (_exa_cortex_pb_CortexStepLintDiff__Output | null);
  'findAllReferences'?: (_exa_cortex_pb_CortexStepFindAllReferences__Output | null);
  'brainUpdate'?: (_exa_cortex_pb_CortexStepBrainUpdate__Output | null);
  'runExtensionCode'?: (_exa_cortex_pb_CortexStepRunExtensionCode__Output | null);
  'userAnnotations': (_exa_cortex_pb_UserStepAnnotations__Output | null);
  'addAnnotation'?: (_exa_cortex_pb_CortexStepAddAnnotation__Output | null);
  'proposalFeedback'?: (_exa_cortex_pb_CortexStepProposalFeedback__Output | null);
  'trajectorySearch'?: (_exa_cortex_pb_CortexStepTrajectorySearch__Output | null);
  'readTerminal'?: (_exa_cortex_pb_CortexStepReadTerminal__Output | null);
  'artifactSummary'?: (_exa_cortex_pb_CortexStepArtifactSummary__Output | null);
  'resolveTask'?: (_exa_cortex_pb_CortexStepResolveTask__Output | null);
  'preToolUseHooks': (_exa_cortex_pb_HookExecutionDetail__Output)[];
  'postToolUseHooks': (_exa_cortex_pb_HookExecutionDetail__Output)[];
  'todoList'?: (_exa_cortex_pb_CortexStepTodoList__Output | null);
  'blocking'?: (_exa_cortex_pb_CortexStepBlocking__Output | null);
  'exploreResponse'?: (_exa_cortex_pb_CortexStepExploreResponse__Output | null);
  'readNotebook'?: (_exa_cortex_pb_CortexStepReadNotebook__Output | null);
  'editNotebook'?: (_exa_cortex_pb_CortexStepEditNotebook__Output | null);
  'codeMap'?: (_exa_cortex_pb_CortexStepCodeMap__Output | null);
  'editCodeMap'?: (_exa_cortex_pb_CortexStepEditCodeMap__Output | null);
  'supercompleteActiveDoc'?: (_exa_cortex_pb_CortexStepSupercompleteActiveDoc__Output | null);
  'findCodeContext'?: (_exa_cortex_pb_CortexStepFindCodeContext__Output | null);
  'supercompleteFeedback'?: (_exa_cortex_pb_CortexStepSupercompleteFeedback__Output | null);
  'lintFixMessage'?: (_exa_cortex_pb_CortexStepLintFixMessage__Output | null);
  'grepSearchV2'?: (_exa_cortex_pb_CortexStepGrepSearchV2__Output | null);
  'upsertCodemap'?: (_exa_cortex_pb_CortexStepUpsertCodemap__Output | null);
  'suggestCodemap'?: (_exa_cortex_pb_CortexStepSuggestCodemap__Output | null);
  'smartFriend'?: (_exa_cortex_pb_CortexStepSmartFriend__Output | null);
  'shieldFromCancellation'?: (boolean);
  'reportBugs'?: (_exa_cortex_pb_CortexStepReportBugs__Output | null);
  'exitPlanMode'?: (_exa_cortex_pb_CortexStepExitPlanMode__Output | null);
  'askUserQuestion'?: (_exa_cortex_pb_CortexStepAskUserQuestion__Output | null);
  'skill'?: (_exa_cortex_pb_CortexStepSkill__Output | null);
  'supercompleteEphemeralFeedback'?: (_exa_cortex_pb_CortexStepSupercompleteEphemeralFeedback__Output | null);
  'arenaTrajectoryConverge'?: (_exa_cortex_pb_CortexStepArenaTrajectoryConverge__Output | null);
  'step'?: "dummy"|"finish"|"planInput"|"mquery"|"codeAction"|"gitCommit"|"grepSearch"|"viewFile"|"listDirectory"|"compile"|"informPlanner"|"userInput"|"plannerResponse"|"fileBreakdown"|"viewCodeItem"|"writeToFile"|"errorMessage"|"clusterQuery"|"listClusters"|"inspectCluster"|"runCommand"|"relatedFiles"|"checkpoint"|"proposeCode"|"find"|"searchKnowledgeBase"|"suggestedResponses"|"commandStatus"|"memory"|"lookupKnowledgeBase"|"readUrlContent"|"viewContentChunk"|"searchWeb"|"retrieveMemory"|"autoCascadeBroadcast"|"customTool"|"createRecipe"|"mcpTool"|"managerFeedback"|"toolCallProposal"|"toolCallChoice"|"trajectoryChoice"|"proxyWebServer"|"deployWebApp"|"clipboard"|"readDeploymentConfig"|"viewFileOutline"|"checkDeployStatus"|"postPrReview"|"readKnowledgeBaseItem"|"listResources"|"readResource"|"lintDiff"|"findAllReferences"|"brainUpdate"|"runExtensionCode"|"addAnnotation"|"proposalFeedback"|"trajectorySearch"|"readTerminal"|"artifactSummary"|"resolveTask"|"todoList"|"blocking"|"exploreResponse"|"readNotebook"|"editNotebook"|"codeMap"|"editCodeMap"|"supercompleteActiveDoc"|"findCodeContext"|"supercompleteFeedback"|"lintFixMessage"|"grepSearchV2"|"upsertCodemap"|"suggestCodemap"|"smartFriend"|"reportBugs"|"exitPlanMode"|"askUserQuestion"|"skill"|"supercompleteEphemeralFeedback"|"arenaTrajectoryConverge";
  '_shieldFromCancellation'?: "shieldFromCancellation";
}
