// Original file: exa/cortex_pb/cortex.proto

export const CortexStepSource = {
  CORTEX_STEP_SOURCE_UNSPECIFIED: 'CORTEX_STEP_SOURCE_UNSPECIFIED',
  CORTEX_STEP_SOURCE_MANUAL: 'CORTEX_STEP_SOURCE_MANUAL',
  CORTEX_STEP_SOURCE_MODEL: 'CORTEX_STEP_SOURCE_MODEL',
  CORTEX_STEP_SOURCE_USER_IMPLICIT: 'CORTEX_STEP_SOURCE_USER_IMPLICIT',
  CORTEX_STEP_SOURCE_USER_EXPLICIT: 'CORTEX_STEP_SOURCE_USER_EXPLICIT',
  CORTEX_STEP_SOURCE_SYSTEM: 'CORTEX_STEP_SOURCE_SYSTEM',
} as const;

export type CortexStepSource =
  | 'CORTEX_STEP_SOURCE_UNSPECIFIED'
  | 0
  | 'CORTEX_STEP_SOURCE_MANUAL'
  | 1
  | 'CORTEX_STEP_SOURCE_MODEL'
  | 2
  | 'CORTEX_STEP_SOURCE_USER_IMPLICIT'
  | 3
  | 'CORTEX_STEP_SOURCE_USER_EXPLICIT'
  | 4
  | 'CORTEX_STEP_SOURCE_SYSTEM'
  | 5

export type CortexStepSource__Output = typeof CortexStepSource[keyof typeof CortexStepSource]
