// Original file: exa/cortex_pb/cortex.proto

export const CortexTodoListItemPriority = {
  CORTEX_TODO_LIST_ITEM_PRIORITY_UNSPECIFIED: 'CORTEX_TODO_LIST_ITEM_PRIORITY_UNSPECIFIED',
  CORTEX_TODO_LIST_ITEM_PRIORITY_LOW: 'CORTEX_TODO_LIST_ITEM_PRIORITY_LOW',
  CORTEX_TODO_LIST_ITEM_PRIORITY_MEDIUM: 'CORTEX_TODO_LIST_ITEM_PRIORITY_MEDIUM',
  CORTEX_TODO_LIST_ITEM_PRIORITY_HIGH: 'CORTEX_TODO_LIST_ITEM_PRIORITY_HIGH',
} as const;

export type CortexTodoListItemPriority =
  | 'CORTEX_TODO_LIST_ITEM_PRIORITY_UNSPECIFIED'
  | 0
  | 'CORTEX_TODO_LIST_ITEM_PRIORITY_LOW'
  | 1
  | 'CORTEX_TODO_LIST_ITEM_PRIORITY_MEDIUM'
  | 2
  | 'CORTEX_TODO_LIST_ITEM_PRIORITY_HIGH'
  | 3

export type CortexTodoListItemPriority__Output = typeof CortexTodoListItemPriority[keyof typeof CortexTodoListItemPriority]
