// Original file: exa/cortex_pb/cortex.proto

export const CortexMemoryTrigger = {
  CORTEX_MEMORY_TRIGGER_UNSPECIFIED: 'CORTEX_MEMORY_TRIGGER_UNSPECIFIED',
  CORTEX_MEMORY_TRIGGER_ALWAYS_ON: 'CORTEX_MEMORY_TRIGGER_ALWAYS_ON',
  CORTEX_MEMORY_TRIGGER_MODEL_DECISION: 'CORTEX_MEMORY_TRIGGER_MODEL_DECISION',
  CORTEX_MEMORY_TRIGGER_MANUAL: 'CORTEX_MEMORY_TRIGGER_MANUAL',
  CORTEX_MEMORY_TRIGGER_GLOB: 'CORTEX_MEMORY_TRIGGER_GLOB',
} as const;

export type CortexMemoryTrigger =
  | 'CORTEX_MEMORY_TRIGGER_UNSPECIFIED'
  | 0
  | 'CORTEX_MEMORY_TRIGGER_ALWAYS_ON'
  | 1
  | 'CORTEX_MEMORY_TRIGGER_MODEL_DECISION'
  | 2
  | 'CORTEX_MEMORY_TRIGGER_MANUAL'
  | 3
  | 'CORTEX_MEMORY_TRIGGER_GLOB'
  | 4

export type CortexMemoryTrigger__Output = typeof CortexMemoryTrigger[keyof typeof CortexMemoryTrigger]
