// Original file: exa/cortex_pb/cortex.proto

export const DeployWebAppFileUploadStatus = {
  DEPLOY_WEB_APP_FILE_UPLOAD_STATUS_UNSPECIFIED: 'DEPLOY_WEB_APP_FILE_UPLOAD_STATUS_UNSPECIFIED',
  DEPLOY_WEB_APP_FILE_UPLOAD_STATUS_PENDING: 'DEPLOY_WEB_APP_FILE_UPLOAD_STATUS_PENDING',
  DEPLOY_WEB_APP_FILE_UPLOAD_STATUS_IN_PROGRESS: 'DEPLOY_WEB_APP_FILE_UPLOAD_STATUS_IN_PROGRESS',
  DEPLOY_WEB_APP_FILE_UPLOAD_STATUS_SUCCESS: 'DEPLOY_WEB_APP_FILE_UPLOAD_STATUS_SUCCESS',
  DEPLOY_WEB_APP_FILE_UPLOAD_STATUS_FAILURE: 'DEPLOY_WEB_APP_FILE_UPLOAD_STATUS_FAILURE',
} as const;

export type DeployWebAppFileUploadStatus =
  | 'DEPLOY_WEB_APP_FILE_UPLOAD_STATUS_UNSPECIFIED'
  | 0
  | 'DEPLOY_WEB_APP_FILE_UPLOAD_STATUS_PENDING'
  | 1
  | 'DEPLOY_WEB_APP_FILE_UPLOAD_STATUS_IN_PROGRESS'
  | 2
  | 'DEPLOY_WEB_APP_FILE_UPLOAD_STATUS_SUCCESS'
  | 3
  | 'DEPLOY_WEB_APP_FILE_UPLOAD_STATUS_FAILURE'
  | 4

export type DeployWebAppFileUploadStatus__Output = typeof DeployWebAppFileUploadStatus[keyof typeof DeployWebAppFileUploadStatus]
