// Original file: exa/cortex_pb/cortex.proto

export const ExecutionAsyncLevel = {
  EXECUTION_ASYNC_LEVEL_UNSPECIFIED: 'EXECUTION_ASYNC_LEVEL_UNSPECIFIED',
  EXECUTION_ASYNC_LEVEL_INVOCATION_BLOCKING: 'EXECUTION_ASYNC_LEVEL_INVOCATION_BLOCKING',
  EXECUTION_ASYNC_LEVEL_EXECUTOR_BLOCKING: 'EXECUTION_ASYNC_LEVEL_EXECUTOR_BLOCKING',
  EXECUTION_ASYNC_LEVEL_FULL_ASYNC: 'EXECUTION_ASYNC_LEVEL_FULL_ASYNC',
} as const;

export type ExecutionAsyncLevel =
  | 'EXECUTION_ASYNC_LEVEL_UNSPECIFIED'
  | 0
  | 'EXECUTION_ASYNC_LEVEL_INVOCATION_BLOCKING'
  | 1
  | 'EXECUTION_ASYNC_LEVEL_EXECUTOR_BLOCKING'
  | 2
  | 'EXECUTION_ASYNC_LEVEL_FULL_ASYNC'
  | 3

export type ExecutionAsyncLevel__Output = typeof ExecutionAsyncLevel[keyof typeof ExecutionAsyncLevel]
