// Original file: exa/cortex_pb/cortex.proto

export const ExecutorTerminationReason = {
  EXECUTOR_TERMINATION_REASON_UNSPECIFIED: 'EXECUTOR_TERMINATION_REASON_UNSPECIFIED',
  EXECUTOR_TERMINATION_REASON_ERROR: 'EXECUTOR_TERMINATION_REASON_ERROR',
  EXECUTOR_TERMINATION_REASON_USER_CANCELED: 'EXECUTOR_TERMINATION_REASON_USER_CANCELED',
  EXECUTOR_TERMINATION_REASON_MAX_INVOCATIONS: 'EXECUTOR_TERMINATION_REASON_MAX_INVOCATIONS',
  EXECUTOR_TERMINATION_REASON_NO_TOOL_CALL: 'EXECUTOR_TERMINATION_REASON_NO_TOOL_CALL',
  EXECUTOR_TERMINATION_REASON_HALTED_STEP: 'EXECUTOR_TERMINATION_REASON_HALTED_STEP',
  EXECUTOR_TERMINATION_REASON_HOOK_BLOCKED: 'EXECUTOR_TERMINATION_REASON_HOOK_BLOCKED',
  EXECUTOR_TERMINATION_REASON_ARENA_INVOCATION_CAP: 'EXECUTOR_TERMINATION_REASON_ARENA_INVOCATION_CAP',
} as const;

export type ExecutorTerminationReason =
  | 'EXECUTOR_TERMINATION_REASON_UNSPECIFIED'
  | 0
  | 'EXECUTOR_TERMINATION_REASON_ERROR'
  | 1
  | 'EXECUTOR_TERMINATION_REASON_USER_CANCELED'
  | 2
  | 'EXECUTOR_TERMINATION_REASON_MAX_INVOCATIONS'
  | 3
  | 'EXECUTOR_TERMINATION_REASON_NO_TOOL_CALL'
  | 4
  | 'EXECUTOR_TERMINATION_REASON_HALTED_STEP'
  | 5
  | 'EXECUTOR_TERMINATION_REASON_HOOK_BLOCKED'
  | 6
  | 'EXECUTOR_TERMINATION_REASON_ARENA_INVOCATION_CAP'
  | 7

export type ExecutorTerminationReason__Output = typeof ExecutorTerminationReason[keyof typeof ExecutorTerminationReason]
