// Original file: exa/cortex_pb/cortex.proto

export const HookAgentAction = {
  HOOK_AGENT_ACTION_UNSPECIFIED: 'HOOK_AGENT_ACTION_UNSPECIFIED',
  HOOK_AGENT_ACTION_PRE_READ_CODE: 'HOOK_AGENT_ACTION_PRE_READ_CODE',
  HOOK_AGENT_ACTION_POST_READ_CODE: 'HOOK_AGENT_ACTION_POST_READ_CODE',
  HOOK_AGENT_ACTION_PRE_WRITE_CODE: 'HOOK_AGENT_ACTION_PRE_WRITE_CODE',
  HOOK_AGENT_ACTION_POST_WRITE_CODE: 'HOOK_AGENT_ACTION_POST_WRITE_CODE',
  HOOK_AGENT_ACTION_PRE_MCP_TOOL_USE: 'HOOK_AGENT_ACTION_PRE_MCP_TOOL_USE',
  HOOK_AGENT_ACTION_POST_MCP_TOOL_USE: 'HOOK_AGENT_ACTION_POST_MCP_TOOL_USE',
  HOOK_AGENT_ACTION_PRE_RUN_COMMAND: 'HOOK_AGENT_ACTION_PRE_RUN_COMMAND',
  HOOK_AGENT_ACTION_POST_RUN_COMMAND: 'HOOK_AGENT_ACTION_POST_RUN_COMMAND',
  HOOK_AGENT_ACTION_PRE_USER_PROMPT: 'HOOK_AGENT_ACTION_PRE_USER_PROMPT',
  HOOK_AGENT_ACTION_POST_CASCADE_RESPONSE: 'HOOK_AGENT_ACTION_POST_CASCADE_RESPONSE',
  HOOK_AGENT_ACTION_POST_SETUP_WORKTREE: 'HOOK_AGENT_ACTION_POST_SETUP_WORKTREE',
} as const;

export type HookAgentAction =
  | 'HOOK_AGENT_ACTION_UNSPECIFIED'
  | 0
  | 'HOOK_AGENT_ACTION_PRE_READ_CODE'
  | 1
  | 'HOOK_AGENT_ACTION_POST_READ_CODE'
  | 2
  | 'HOOK_AGENT_ACTION_PRE_WRITE_CODE'
  | 3
  | 'HOOK_AGENT_ACTION_POST_WRITE_CODE'
  | 4
  | 'HOOK_AGENT_ACTION_PRE_MCP_TOOL_USE'
  | 5
  | 'HOOK_AGENT_ACTION_POST_MCP_TOOL_USE'
  | 6
  | 'HOOK_AGENT_ACTION_PRE_RUN_COMMAND'
  | 7
  | 'HOOK_AGENT_ACTION_POST_RUN_COMMAND'
  | 8
  | 'HOOK_AGENT_ACTION_PRE_USER_PROMPT'
  | 9
  | 'HOOK_AGENT_ACTION_POST_CASCADE_RESPONSE'
  | 10
  | 'HOOK_AGENT_ACTION_POST_SETUP_WORKTREE'
  | 11

export type HookAgentAction__Output = typeof HookAgentAction[keyof typeof HookAgentAction]
