// Original file: exa/cortex_pb/cortex.proto

export const ReadUrlContentAction = {
  READ_URL_CONTENT_ACTION_UNSPECIFIED: 'READ_URL_CONTENT_ACTION_UNSPECIFIED',
  READ_URL_CONTENT_ACTION_ALLOW_ONCE: 'READ_URL_CONTENT_ACTION_ALLOW_ONCE',
  READ_URL_CONTENT_ACTION_REJECT: 'READ_URL_CONTENT_ACTION_REJECT',
  READ_URL_CONTENT_ACTION_ALWAYS_ALLOW_ORIGIN: 'READ_URL_CONTENT_ACTION_ALWAYS_ALLOW_ORIGIN',
} as const;

export type ReadUrlContentAction =
  | 'READ_URL_CONTENT_ACTION_UNSPECIFIED'
  | 0
  | 'READ_URL_CONTENT_ACTION_ALLOW_ONCE'
  | 1
  | 'READ_URL_CONTENT_ACTION_REJECT'
  | 2
  | 'READ_URL_CONTENT_ACTION_ALWAYS_ALLOW_ORIGIN'
  | 3

export type ReadUrlContentAction__Output = typeof ReadUrlContentAction[keyof typeof ReadUrlContentAction]
