// Original file: exa/cortex_pb/cortex.proto

export const ReplaceToolVariant = {
  REPLACE_TOOL_VARIANT_UNSPECIFIED: 'REPLACE_TOOL_VARIANT_UNSPECIFIED',
  REPLACE_TOOL_VARIANT_REPLACEMENT_CHUNK: 'REPLACE_TOOL_VARIANT_REPLACEMENT_CHUNK',
  REPLACE_TOOL_VARIANT_SEARCH_REPLACE: 'REPLACE_TOOL_VARIANT_SEARCH_REPLACE',
  REPLACE_TOOL_VARIANT_APPLY_PATCH: 'REPLACE_TOOL_VARIANT_APPLY_PATCH',
  REPLACE_TOOL_VARIANT_SINGLE_MULTI: 'REPLACE_TOOL_VARIANT_SINGLE_MULTI',
  REPLACE_TOOL_VARIANT_OPENAI_APPLY_PATCH: 'REPLACE_TOOL_VARIANT_OPENAI_APPLY_PATCH',
} as const;

export type ReplaceToolVariant =
  | 'REPLACE_TOOL_VARIANT_UNSPECIFIED'
  | 0
  | 'REPLACE_TOOL_VARIANT_REPLACEMENT_CHUNK'
  | 1
  | 'REPLACE_TOOL_VARIANT_SEARCH_REPLACE'
  | 2
  | 'REPLACE_TOOL_VARIANT_APPLY_PATCH'
  | 3
  | 'REPLACE_TOOL_VARIANT_SINGLE_MULTI'
  | 4
  | 'REPLACE_TOOL_VARIANT_OPENAI_APPLY_PATCH'
  | 5

export type ReplaceToolVariant__Output = typeof ReplaceToolVariant[keyof typeof ReplaceToolVariant]
