// Original file: exa/cortex_pb/cortex.proto

export const RunExtensionCodeAutoRunDecision = {
  RUN_EXTENSION_CODE_AUTO_RUN_DECISION_UNSPECIFIED: 'RUN_EXTENSION_CODE_AUTO_RUN_DECISION_UNSPECIFIED',
  RUN_EXTENSION_CODE_AUTO_RUN_DECISION_ALLOWED: 'RUN_EXTENSION_CODE_AUTO_RUN_DECISION_ALLOWED',
  RUN_EXTENSION_CODE_AUTO_RUN_DECISION_DENIED: 'RUN_EXTENSION_CODE_AUTO_RUN_DECISION_DENIED',
  RUN_EXTENSION_CODE_AUTO_RUN_DECISION_MODEL_ALLOWED: 'RUN_EXTENSION_CODE_AUTO_RUN_DECISION_MODEL_ALLOWED',
  RUN_EXTENSION_CODE_AUTO_RUN_DECISION_MODEL_DENIED: 'RUN_EXTENSION_CODE_AUTO_RUN_DECISION_MODEL_DENIED',
} as const;

export type RunExtensionCodeAutoRunDecision =
  | 'RUN_EXTENSION_CODE_AUTO_RUN_DECISION_UNSPECIFIED'
  | 0
  | 'RUN_EXTENSION_CODE_AUTO_RUN_DECISION_ALLOWED'
  | 1
  | 'RUN_EXTENSION_CODE_AUTO_RUN_DECISION_DENIED'
  | 2
  | 'RUN_EXTENSION_CODE_AUTO_RUN_DECISION_MODEL_ALLOWED'
  | 3
  | 'RUN_EXTENSION_CODE_AUTO_RUN_DECISION_MODEL_DENIED'
  | 4

export type RunExtensionCodeAutoRunDecision__Output = typeof RunExtensionCodeAutoRunDecision[keyof typeof RunExtensionCodeAutoRunDecision]
