import { z } from 'zod'

import {
  Vulnerability_Report_Issue_State_Enum,
  Vulnerability_Report_Issue_Tag_Enum,
} from '../../generates/client_generates'
import { getIssueTypeCatalogEntry } from './issueTypeCatalog'
import { IssuePartsFp } from './types/issue'

// Defense-in-depth bound for opaque issue-type strings (the closed
// IssueType_Enum allowlist was removed in E-2015). DB/analyzer values are
// UPPER_SNAKE / PascalCase identifiers, so this charset + length holds while
// rejecting injection-shaped input. A bounded value also guarantees the derived
// friendly-label fallback below contains no Markdown metacharacters.
export const SafeIssueTypeStringZ = z
  .string()
  .regex(/^[A-Za-z0-9_]+$/)
  .max(128)

export const getIssueTypeFriendlyString = (
  issueType: string | null | undefined
): string => {
  // Issue types are opaque strings. Prefer the analyzer-served catalog label;
  // fall back to a derived label (the curated issueTypeMap was removed in
  // E-2015 — every runtime hydrates the catalog at its entry point).
  const fromCatalog = getIssueTypeCatalogEntry(issueType)?.label
  if (fromCatalog) {
    return fromCatalog
  }
  return issueType ? issueType.replaceAll('_', ' ') : 'Other'
}

export const statusMap: Record<Vulnerability_Report_Issue_State_Enum, string> =
  {
    [Vulnerability_Report_Issue_State_Enum.Digested]: 'Digested',
    [Vulnerability_Report_Issue_State_Enum.Error]: 'Error',
    [Vulnerability_Report_Issue_State_Enum.FalsePositive]: 'False Positive',
    [Vulnerability_Report_Issue_State_Enum.Filtered]: 'Filtered',
    [Vulnerability_Report_Issue_State_Enum.FilteredAiQuota]:
      'Filtered AI Quota',
    [Vulnerability_Report_Issue_State_Enum.Fixed]: 'Fixable',
    [Vulnerability_Report_Issue_State_Enum.NoFix]: 'No Fix',
    [Vulnerability_Report_Issue_State_Enum.Pending]: 'Pending',
    [Vulnerability_Report_Issue_State_Enum.Unfixable]: 'Unfixable',
    [Vulnerability_Report_Issue_State_Enum.Unsupported]: 'Unsupported',
  } as const

const statusZ = z.enum(Vulnerability_Report_Issue_State_Enum)
export const getStatusFriendlyString = (
  status: string | null | undefined
): string => {
  const statusZParseRes = statusZ.safeParse(status)
  if (!statusZParseRes.success) {
    return status ? status.replaceAll('_', ' ') : 'Unknown'
  }
  return statusMap[statusZParseRes.data]
}

export function prettyName(val: string) {
  return (
    String(val).charAt(0).toUpperCase() +
    String(val).replaceAll('_', ' ').slice(1).toLowerCase()
  )
}

export function getTagTooltip(tag: string) {
  switch (tag) {
    case 'FALSE_POSITIVE':
      return 'Issue was found to be a false positive'
    case 'TEST_CODE':
      return 'Issue found in test files, not production code'
    case 'VENDOR_CODE':
      return 'Issue is in external libraries or dependencies not owned or maintained by your team'
    case 'AUTOGENERATED_CODE':
      return 'Code created by tools or frameworks, not manually written'
    case 'AUXILIARY_CODE':
      return "Issue found in supporting files that don't impact core functionality"
    case 'Filtered':
      return 'Issue was filtered by user in the Fix Policy'
    case 'SUPPRESSED':
      return 'Suppressed in the scan report'
    default:
      return tag
  }
}

export const issueDescription: Record<
  Vulnerability_Report_Issue_Tag_Enum,
  string
> = {
  [Vulnerability_Report_Issue_Tag_Enum.AutogeneratedCode]:
    'The flagged code is generated automatically by tools or frameworks as part of the build or runtime process. This categorization highlights that **the issue resides in non-manual code**, which often requires tool-specific solutions or exemptions.',
  [Vulnerability_Report_Issue_Tag_Enum.AuxiliaryCode]:
    "The flagged code is auxiliary or supporting code, such as configuration files, build scripts, or other non-application logic. This categorization indicates that the issue is not directly related to the application's core functionality.",
  [Vulnerability_Report_Issue_Tag_Enum.FalsePositive]:
    "The flagged code **does not represent an actual vulnerability within the application's context.** This categorization indicates that the issue is either misidentified by the scanner or deemed irrelevant to the application's functionality.",
  [Vulnerability_Report_Issue_Tag_Enum.TestCode]:
    'The flagged code resides in a test-specific path or context. This categorization indicates that **it supports testing scenarios and is isolated from production use**.',
  [Vulnerability_Report_Issue_Tag_Enum.Unfixable]:
    'The flagged code cannot be fixed',
  [Vulnerability_Report_Issue_Tag_Enum.VendorCode]:
    "The flagged code originates from a third-party library or dependency maintained externally. This categorization suggests that **the issue lies outside the application's direct control** and should be addressed by the vendor if necessary.",
  [Vulnerability_Report_Issue_Tag_Enum.Suppressed]:
    'Suppressed in the scan report.',
  [Vulnerability_Report_Issue_Tag_Enum.AgenticRemediationInProgress]:
    'Mobb is currently retrying remediation on this issue. The state will refresh automatically once the run finishes.',
}

type FalsePositiveData = IssuePartsFp['getFalsePositive']

function replaceKeysWithValues(
  fixDescription: string,
  extraContext: { key: string; value: string }[]
): string {
  let result = fixDescription
  extraContext.forEach(({ key, value }) => {
    result = result.replace(`\${${key}}`, value)
  })
  return result
}

export function getParsedFalsePositiveMessage(data: FalsePositiveData): {
  description: string
  contextString: string | null
} {
  const { fixDescription, extraContext } = data

  const containsTemplate = extraContext.some((context) =>
    fixDescription.includes(`\${${context.key}}`)
  )

  const description = containsTemplate
    ? replaceKeysWithValues(fixDescription, extraContext)
    : fixDescription

  const contextString = containsTemplate
    ? null
    : `\`\`\`${extraContext.map(({ value }) => value).join(' ')} \`\`\``

  return { description, contextString }
}
