// Original file: exa/knowledge_base_pb/knowledge_base.proto

import type * as grpc from '@grpc/grpc-js'
import type { MethodDefinition } from '@grpc/proto-loader'
import type { CreateConnectionRequest as _exa_knowledge_base_pb_CreateConnectionRequest, CreateConnectionRequest__Output as _exa_knowledge_base_pb_CreateConnectionRequest__Output } from '../../exa/knowledge_base_pb/CreateConnectionRequest';
import type { CreateConnectionResponse as _exa_knowledge_base_pb_CreateConnectionResponse, CreateConnectionResponse__Output as _exa_knowledge_base_pb_CreateConnectionResponse__Output } from '../../exa/knowledge_base_pb/CreateConnectionResponse';
import type { CreateKnowledgeBaseItemRequest as _exa_knowledge_base_pb_CreateKnowledgeBaseItemRequest, CreateKnowledgeBaseItemRequest__Output as _exa_knowledge_base_pb_CreateKnowledgeBaseItemRequest__Output } from '../../exa/knowledge_base_pb/CreateKnowledgeBaseItemRequest';
import type { CreateKnowledgeBaseItemResponse as _exa_knowledge_base_pb_CreateKnowledgeBaseItemResponse, CreateKnowledgeBaseItemResponse__Output as _exa_knowledge_base_pb_CreateKnowledgeBaseItemResponse__Output } from '../../exa/knowledge_base_pb/CreateKnowledgeBaseItemResponse';
import type { DeleteKnowledgeBaseItemRequest as _exa_knowledge_base_pb_DeleteKnowledgeBaseItemRequest, DeleteKnowledgeBaseItemRequest__Output as _exa_knowledge_base_pb_DeleteKnowledgeBaseItemRequest__Output } from '../../exa/knowledge_base_pb/DeleteKnowledgeBaseItemRequest';
import type { DeleteKnowledgeBaseItemResponse as _exa_knowledge_base_pb_DeleteKnowledgeBaseItemResponse, DeleteKnowledgeBaseItemResponse__Output as _exa_knowledge_base_pb_DeleteKnowledgeBaseItemResponse__Output } from '../../exa/knowledge_base_pb/DeleteKnowledgeBaseItemResponse';
import type { EditKnowledgeBaseItemRequest as _exa_knowledge_base_pb_EditKnowledgeBaseItemRequest, EditKnowledgeBaseItemRequest__Output as _exa_knowledge_base_pb_EditKnowledgeBaseItemRequest__Output } from '../../exa/knowledge_base_pb/EditKnowledgeBaseItemRequest';
import type { EditKnowledgeBaseItemResponse as _exa_knowledge_base_pb_EditKnowledgeBaseItemResponse, EditKnowledgeBaseItemResponse__Output as _exa_knowledge_base_pb_EditKnowledgeBaseItemResponse__Output } from '../../exa/knowledge_base_pb/EditKnowledgeBaseItemResponse';
import type { GetConnectionRequest as _exa_knowledge_base_pb_GetConnectionRequest, GetConnectionRequest__Output as _exa_knowledge_base_pb_GetConnectionRequest__Output } from '../../exa/knowledge_base_pb/GetConnectionRequest';
import type { GetConnectionResponse as _exa_knowledge_base_pb_GetConnectionResponse, GetConnectionResponse__Output as _exa_knowledge_base_pb_GetConnectionResponse__Output } from '../../exa/knowledge_base_pb/GetConnectionResponse';
import type { GetGithubIntegrationStatusRequest as _exa_knowledge_base_pb_GetGithubIntegrationStatusRequest, GetGithubIntegrationStatusRequest__Output as _exa_knowledge_base_pb_GetGithubIntegrationStatusRequest__Output } from '../../exa/knowledge_base_pb/GetGithubIntegrationStatusRequest';
import type { GetGithubIntegrationStatusResponse as _exa_knowledge_base_pb_GetGithubIntegrationStatusResponse, GetGithubIntegrationStatusResponse__Output as _exa_knowledge_base_pb_GetGithubIntegrationStatusResponse__Output } from '../../exa/knowledge_base_pb/GetGithubIntegrationStatusResponse';
import type { GetGithubPullRequestSearchInfoRequest as _exa_knowledge_base_pb_GetGithubPullRequestSearchInfoRequest, GetGithubPullRequestSearchInfoRequest__Output as _exa_knowledge_base_pb_GetGithubPullRequestSearchInfoRequest__Output } from '../../exa/knowledge_base_pb/GetGithubPullRequestSearchInfoRequest';
import type { GetGithubPullRequestSearchInfoResponse as _exa_knowledge_base_pb_GetGithubPullRequestSearchInfoResponse, GetGithubPullRequestSearchInfoResponse__Output as _exa_knowledge_base_pb_GetGithubPullRequestSearchInfoResponse__Output } from '../../exa/knowledge_base_pb/GetGithubPullRequestSearchInfoResponse';
import type { GetKnowledgeBaseItemsForTeamRequest as _exa_knowledge_base_pb_GetKnowledgeBaseItemsForTeamRequest, GetKnowledgeBaseItemsForTeamRequest__Output as _exa_knowledge_base_pb_GetKnowledgeBaseItemsForTeamRequest__Output } from '../../exa/knowledge_base_pb/GetKnowledgeBaseItemsForTeamRequest';
import type { GetKnowledgeBaseItemsForTeamResponse as _exa_knowledge_base_pb_GetKnowledgeBaseItemsForTeamResponse, GetKnowledgeBaseItemsForTeamResponse__Output as _exa_knowledge_base_pb_GetKnowledgeBaseItemsForTeamResponse__Output } from '../../exa/knowledge_base_pb/GetKnowledgeBaseItemsForTeamResponse';
import type { GetKnowledgeBaseItemsRequest as _exa_knowledge_base_pb_GetKnowledgeBaseItemsRequest, GetKnowledgeBaseItemsRequest__Output as _exa_knowledge_base_pb_GetKnowledgeBaseItemsRequest__Output } from '../../exa/knowledge_base_pb/GetKnowledgeBaseItemsRequest';
import type { GetKnowledgeBaseItemsResponse as _exa_knowledge_base_pb_GetKnowledgeBaseItemsResponse, GetKnowledgeBaseItemsResponse__Output as _exa_knowledge_base_pb_GetKnowledgeBaseItemsResponse__Output } from '../../exa/knowledge_base_pb/GetKnowledgeBaseItemsResponse';
import type { ReadKnowledgeBaseItemRequest as _exa_knowledge_base_pb_ReadKnowledgeBaseItemRequest, ReadKnowledgeBaseItemRequest__Output as _exa_knowledge_base_pb_ReadKnowledgeBaseItemRequest__Output } from '../../exa/knowledge_base_pb/ReadKnowledgeBaseItemRequest';
import type { ReadKnowledgeBaseItemResponse as _exa_knowledge_base_pb_ReadKnowledgeBaseItemResponse, ReadKnowledgeBaseItemResponse__Output as _exa_knowledge_base_pb_ReadKnowledgeBaseItemResponse__Output } from '../../exa/knowledge_base_pb/ReadKnowledgeBaseItemResponse';
import type { RemoveConnectionRequest as _exa_knowledge_base_pb_RemoveConnectionRequest, RemoveConnectionRequest__Output as _exa_knowledge_base_pb_RemoveConnectionRequest__Output } from '../../exa/knowledge_base_pb/RemoveConnectionRequest';
import type { RemoveConnectionResponse as _exa_knowledge_base_pb_RemoveConnectionResponse, RemoveConnectionResponse__Output as _exa_knowledge_base_pb_RemoveConnectionResponse__Output } from '../../exa/knowledge_base_pb/RemoveConnectionResponse';

export interface KnowledgeBaseServiceClient extends grpc.Client {
  CreateConnection(argument: _exa_knowledge_base_pb_CreateConnectionRequest, metadata: grpc.Metadata, options: grpc.CallOptions, callback: grpc.requestCallback<_exa_knowledge_base_pb_CreateConnectionResponse__Output>): grpc.ClientUnaryCall;
  CreateConnection(argument: _exa_knowledge_base_pb_CreateConnectionRequest, metadata: grpc.Metadata, callback: grpc.requestCallback<_exa_knowledge_base_pb_CreateConnectionResponse__Output>): grpc.ClientUnaryCall;
  CreateConnection(argument: _exa_knowledge_base_pb_CreateConnectionRequest, options: grpc.CallOptions, callback: grpc.requestCallback<_exa_knowledge_base_pb_CreateConnectionResponse__Output>): grpc.ClientUnaryCall;
  CreateConnection(argument: _exa_knowledge_base_pb_CreateConnectionRequest, callback: grpc.requestCallback<_exa_knowledge_base_pb_CreateConnectionResponse__Output>): grpc.ClientUnaryCall;
  createConnection(argument: _exa_knowledge_base_pb_CreateConnectionRequest, metadata: grpc.Metadata, options: grpc.CallOptions, callback: grpc.requestCallback<_exa_knowledge_base_pb_CreateConnectionResponse__Output>): grpc.ClientUnaryCall;
  createConnection(argument: _exa_knowledge_base_pb_CreateConnectionRequest, metadata: grpc.Metadata, callback: grpc.requestCallback<_exa_knowledge_base_pb_CreateConnectionResponse__Output>): grpc.ClientUnaryCall;
  createConnection(argument: _exa_knowledge_base_pb_CreateConnectionRequest, options: grpc.CallOptions, callback: grpc.requestCallback<_exa_knowledge_base_pb_CreateConnectionResponse__Output>): grpc.ClientUnaryCall;
  createConnection(argument: _exa_knowledge_base_pb_CreateConnectionRequest, callback: grpc.requestCallback<_exa_knowledge_base_pb_CreateConnectionResponse__Output>): grpc.ClientUnaryCall;
  
  CreateKnowledgeBaseItem(argument: _exa_knowledge_base_pb_CreateKnowledgeBaseItemRequest, metadata: grpc.Metadata, options: grpc.CallOptions, callback: grpc.requestCallback<_exa_knowledge_base_pb_CreateKnowledgeBaseItemResponse__Output>): grpc.ClientUnaryCall;
  CreateKnowledgeBaseItem(argument: _exa_knowledge_base_pb_CreateKnowledgeBaseItemRequest, metadata: grpc.Metadata, callback: grpc.requestCallback<_exa_knowledge_base_pb_CreateKnowledgeBaseItemResponse__Output>): grpc.ClientUnaryCall;
  CreateKnowledgeBaseItem(argument: _exa_knowledge_base_pb_CreateKnowledgeBaseItemRequest, options: grpc.CallOptions, callback: grpc.requestCallback<_exa_knowledge_base_pb_CreateKnowledgeBaseItemResponse__Output>): grpc.ClientUnaryCall;
  CreateKnowledgeBaseItem(argument: _exa_knowledge_base_pb_CreateKnowledgeBaseItemRequest, callback: grpc.requestCallback<_exa_knowledge_base_pb_CreateKnowledgeBaseItemResponse__Output>): grpc.ClientUnaryCall;
  createKnowledgeBaseItem(argument: _exa_knowledge_base_pb_CreateKnowledgeBaseItemRequest, metadata: grpc.Metadata, options: grpc.CallOptions, callback: grpc.requestCallback<_exa_knowledge_base_pb_CreateKnowledgeBaseItemResponse__Output>): grpc.ClientUnaryCall;
  createKnowledgeBaseItem(argument: _exa_knowledge_base_pb_CreateKnowledgeBaseItemRequest, metadata: grpc.Metadata, callback: grpc.requestCallback<_exa_knowledge_base_pb_CreateKnowledgeBaseItemResponse__Output>): grpc.ClientUnaryCall;
  createKnowledgeBaseItem(argument: _exa_knowledge_base_pb_CreateKnowledgeBaseItemRequest, options: grpc.CallOptions, callback: grpc.requestCallback<_exa_knowledge_base_pb_CreateKnowledgeBaseItemResponse__Output>): grpc.ClientUnaryCall;
  createKnowledgeBaseItem(argument: _exa_knowledge_base_pb_CreateKnowledgeBaseItemRequest, callback: grpc.requestCallback<_exa_knowledge_base_pb_CreateKnowledgeBaseItemResponse__Output>): grpc.ClientUnaryCall;
  
  DeleteKnowledgeBaseItem(argument: _exa_knowledge_base_pb_DeleteKnowledgeBaseItemRequest, metadata: grpc.Metadata, options: grpc.CallOptions, callback: grpc.requestCallback<_exa_knowledge_base_pb_DeleteKnowledgeBaseItemResponse__Output>): grpc.ClientUnaryCall;
  DeleteKnowledgeBaseItem(argument: _exa_knowledge_base_pb_DeleteKnowledgeBaseItemRequest, metadata: grpc.Metadata, callback: grpc.requestCallback<_exa_knowledge_base_pb_DeleteKnowledgeBaseItemResponse__Output>): grpc.ClientUnaryCall;
  DeleteKnowledgeBaseItem(argument: _exa_knowledge_base_pb_DeleteKnowledgeBaseItemRequest, options: grpc.CallOptions, callback: grpc.requestCallback<_exa_knowledge_base_pb_DeleteKnowledgeBaseItemResponse__Output>): grpc.ClientUnaryCall;
  DeleteKnowledgeBaseItem(argument: _exa_knowledge_base_pb_DeleteKnowledgeBaseItemRequest, callback: grpc.requestCallback<_exa_knowledge_base_pb_DeleteKnowledgeBaseItemResponse__Output>): grpc.ClientUnaryCall;
  deleteKnowledgeBaseItem(argument: _exa_knowledge_base_pb_DeleteKnowledgeBaseItemRequest, metadata: grpc.Metadata, options: grpc.CallOptions, callback: grpc.requestCallback<_exa_knowledge_base_pb_DeleteKnowledgeBaseItemResponse__Output>): grpc.ClientUnaryCall;
  deleteKnowledgeBaseItem(argument: _exa_knowledge_base_pb_DeleteKnowledgeBaseItemRequest, metadata: grpc.Metadata, callback: grpc.requestCallback<_exa_knowledge_base_pb_DeleteKnowledgeBaseItemResponse__Output>): grpc.ClientUnaryCall;
  deleteKnowledgeBaseItem(argument: _exa_knowledge_base_pb_DeleteKnowledgeBaseItemRequest, options: grpc.CallOptions, callback: grpc.requestCallback<_exa_knowledge_base_pb_DeleteKnowledgeBaseItemResponse__Output>): grpc.ClientUnaryCall;
  deleteKnowledgeBaseItem(argument: _exa_knowledge_base_pb_DeleteKnowledgeBaseItemRequest, callback: grpc.requestCallback<_exa_knowledge_base_pb_DeleteKnowledgeBaseItemResponse__Output>): grpc.ClientUnaryCall;
  
  EditKnowledgeBaseItem(argument: _exa_knowledge_base_pb_EditKnowledgeBaseItemRequest, metadata: grpc.Metadata, options: grpc.CallOptions, callback: grpc.requestCallback<_exa_knowledge_base_pb_EditKnowledgeBaseItemResponse__Output>): grpc.ClientUnaryCall;
  EditKnowledgeBaseItem(argument: _exa_knowledge_base_pb_EditKnowledgeBaseItemRequest, metadata: grpc.Metadata, callback: grpc.requestCallback<_exa_knowledge_base_pb_EditKnowledgeBaseItemResponse__Output>): grpc.ClientUnaryCall;
  EditKnowledgeBaseItem(argument: _exa_knowledge_base_pb_EditKnowledgeBaseItemRequest, options: grpc.CallOptions, callback: grpc.requestCallback<_exa_knowledge_base_pb_EditKnowledgeBaseItemResponse__Output>): grpc.ClientUnaryCall;
  EditKnowledgeBaseItem(argument: _exa_knowledge_base_pb_EditKnowledgeBaseItemRequest, callback: grpc.requestCallback<_exa_knowledge_base_pb_EditKnowledgeBaseItemResponse__Output>): grpc.ClientUnaryCall;
  editKnowledgeBaseItem(argument: _exa_knowledge_base_pb_EditKnowledgeBaseItemRequest, metadata: grpc.Metadata, options: grpc.CallOptions, callback: grpc.requestCallback<_exa_knowledge_base_pb_EditKnowledgeBaseItemResponse__Output>): grpc.ClientUnaryCall;
  editKnowledgeBaseItem(argument: _exa_knowledge_base_pb_EditKnowledgeBaseItemRequest, metadata: grpc.Metadata, callback: grpc.requestCallback<_exa_knowledge_base_pb_EditKnowledgeBaseItemResponse__Output>): grpc.ClientUnaryCall;
  editKnowledgeBaseItem(argument: _exa_knowledge_base_pb_EditKnowledgeBaseItemRequest, options: grpc.CallOptions, callback: grpc.requestCallback<_exa_knowledge_base_pb_EditKnowledgeBaseItemResponse__Output>): grpc.ClientUnaryCall;
  editKnowledgeBaseItem(argument: _exa_knowledge_base_pb_EditKnowledgeBaseItemRequest, callback: grpc.requestCallback<_exa_knowledge_base_pb_EditKnowledgeBaseItemResponse__Output>): grpc.ClientUnaryCall;
  
  GetConnection(argument: _exa_knowledge_base_pb_GetConnectionRequest, metadata: grpc.Metadata, options: grpc.CallOptions, callback: grpc.requestCallback<_exa_knowledge_base_pb_GetConnectionResponse__Output>): grpc.ClientUnaryCall;
  GetConnection(argument: _exa_knowledge_base_pb_GetConnectionRequest, metadata: grpc.Metadata, callback: grpc.requestCallback<_exa_knowledge_base_pb_GetConnectionResponse__Output>): grpc.ClientUnaryCall;
  GetConnection(argument: _exa_knowledge_base_pb_GetConnectionRequest, options: grpc.CallOptions, callback: grpc.requestCallback<_exa_knowledge_base_pb_GetConnectionResponse__Output>): grpc.ClientUnaryCall;
  GetConnection(argument: _exa_knowledge_base_pb_GetConnectionRequest, callback: grpc.requestCallback<_exa_knowledge_base_pb_GetConnectionResponse__Output>): grpc.ClientUnaryCall;
  getConnection(argument: _exa_knowledge_base_pb_GetConnectionRequest, metadata: grpc.Metadata, options: grpc.CallOptions, callback: grpc.requestCallback<_exa_knowledge_base_pb_GetConnectionResponse__Output>): grpc.ClientUnaryCall;
  getConnection(argument: _exa_knowledge_base_pb_GetConnectionRequest, metadata: grpc.Metadata, callback: grpc.requestCallback<_exa_knowledge_base_pb_GetConnectionResponse__Output>): grpc.ClientUnaryCall;
  getConnection(argument: _exa_knowledge_base_pb_GetConnectionRequest, options: grpc.CallOptions, callback: grpc.requestCallback<_exa_knowledge_base_pb_GetConnectionResponse__Output>): grpc.ClientUnaryCall;
  getConnection(argument: _exa_knowledge_base_pb_GetConnectionRequest, callback: grpc.requestCallback<_exa_knowledge_base_pb_GetConnectionResponse__Output>): grpc.ClientUnaryCall;
  
  GetGithubIntegrationStatus(argument: _exa_knowledge_base_pb_GetGithubIntegrationStatusRequest, metadata: grpc.Metadata, options: grpc.CallOptions, callback: grpc.requestCallback<_exa_knowledge_base_pb_GetGithubIntegrationStatusResponse__Output>): grpc.ClientUnaryCall;
  GetGithubIntegrationStatus(argument: _exa_knowledge_base_pb_GetGithubIntegrationStatusRequest, metadata: grpc.Metadata, callback: grpc.requestCallback<_exa_knowledge_base_pb_GetGithubIntegrationStatusResponse__Output>): grpc.ClientUnaryCall;
  GetGithubIntegrationStatus(argument: _exa_knowledge_base_pb_GetGithubIntegrationStatusRequest, options: grpc.CallOptions, callback: grpc.requestCallback<_exa_knowledge_base_pb_GetGithubIntegrationStatusResponse__Output>): grpc.ClientUnaryCall;
  GetGithubIntegrationStatus(argument: _exa_knowledge_base_pb_GetGithubIntegrationStatusRequest, callback: grpc.requestCallback<_exa_knowledge_base_pb_GetGithubIntegrationStatusResponse__Output>): grpc.ClientUnaryCall;
  getGithubIntegrationStatus(argument: _exa_knowledge_base_pb_GetGithubIntegrationStatusRequest, metadata: grpc.Metadata, options: grpc.CallOptions, callback: grpc.requestCallback<_exa_knowledge_base_pb_GetGithubIntegrationStatusResponse__Output>): grpc.ClientUnaryCall;
  getGithubIntegrationStatus(argument: _exa_knowledge_base_pb_GetGithubIntegrationStatusRequest, metadata: grpc.Metadata, callback: grpc.requestCallback<_exa_knowledge_base_pb_GetGithubIntegrationStatusResponse__Output>): grpc.ClientUnaryCall;
  getGithubIntegrationStatus(argument: _exa_knowledge_base_pb_GetGithubIntegrationStatusRequest, options: grpc.CallOptions, callback: grpc.requestCallback<_exa_knowledge_base_pb_GetGithubIntegrationStatusResponse__Output>): grpc.ClientUnaryCall;
  getGithubIntegrationStatus(argument: _exa_knowledge_base_pb_GetGithubIntegrationStatusRequest, callback: grpc.requestCallback<_exa_knowledge_base_pb_GetGithubIntegrationStatusResponse__Output>): grpc.ClientUnaryCall;
  
  GetGithubPullRequestSearchInfo(argument: _exa_knowledge_base_pb_GetGithubPullRequestSearchInfoRequest, metadata: grpc.Metadata, options: grpc.CallOptions, callback: grpc.requestCallback<_exa_knowledge_base_pb_GetGithubPullRequestSearchInfoResponse__Output>): grpc.ClientUnaryCall;
  GetGithubPullRequestSearchInfo(argument: _exa_knowledge_base_pb_GetGithubPullRequestSearchInfoRequest, metadata: grpc.Metadata, callback: grpc.requestCallback<_exa_knowledge_base_pb_GetGithubPullRequestSearchInfoResponse__Output>): grpc.ClientUnaryCall;
  GetGithubPullRequestSearchInfo(argument: _exa_knowledge_base_pb_GetGithubPullRequestSearchInfoRequest, options: grpc.CallOptions, callback: grpc.requestCallback<_exa_knowledge_base_pb_GetGithubPullRequestSearchInfoResponse__Output>): grpc.ClientUnaryCall;
  GetGithubPullRequestSearchInfo(argument: _exa_knowledge_base_pb_GetGithubPullRequestSearchInfoRequest, callback: grpc.requestCallback<_exa_knowledge_base_pb_GetGithubPullRequestSearchInfoResponse__Output>): grpc.ClientUnaryCall;
  getGithubPullRequestSearchInfo(argument: _exa_knowledge_base_pb_GetGithubPullRequestSearchInfoRequest, metadata: grpc.Metadata, options: grpc.CallOptions, callback: grpc.requestCallback<_exa_knowledge_base_pb_GetGithubPullRequestSearchInfoResponse__Output>): grpc.ClientUnaryCall;
  getGithubPullRequestSearchInfo(argument: _exa_knowledge_base_pb_GetGithubPullRequestSearchInfoRequest, metadata: grpc.Metadata, callback: grpc.requestCallback<_exa_knowledge_base_pb_GetGithubPullRequestSearchInfoResponse__Output>): grpc.ClientUnaryCall;
  getGithubPullRequestSearchInfo(argument: _exa_knowledge_base_pb_GetGithubPullRequestSearchInfoRequest, options: grpc.CallOptions, callback: grpc.requestCallback<_exa_knowledge_base_pb_GetGithubPullRequestSearchInfoResponse__Output>): grpc.ClientUnaryCall;
  getGithubPullRequestSearchInfo(argument: _exa_knowledge_base_pb_GetGithubPullRequestSearchInfoRequest, callback: grpc.requestCallback<_exa_knowledge_base_pb_GetGithubPullRequestSearchInfoResponse__Output>): grpc.ClientUnaryCall;
  
  GetKnowledgeBaseItems(argument: _exa_knowledge_base_pb_GetKnowledgeBaseItemsRequest, metadata: grpc.Metadata, options: grpc.CallOptions, callback: grpc.requestCallback<_exa_knowledge_base_pb_GetKnowledgeBaseItemsResponse__Output>): grpc.ClientUnaryCall;
  GetKnowledgeBaseItems(argument: _exa_knowledge_base_pb_GetKnowledgeBaseItemsRequest, metadata: grpc.Metadata, callback: grpc.requestCallback<_exa_knowledge_base_pb_GetKnowledgeBaseItemsResponse__Output>): grpc.ClientUnaryCall;
  GetKnowledgeBaseItems(argument: _exa_knowledge_base_pb_GetKnowledgeBaseItemsRequest, options: grpc.CallOptions, callback: grpc.requestCallback<_exa_knowledge_base_pb_GetKnowledgeBaseItemsResponse__Output>): grpc.ClientUnaryCall;
  GetKnowledgeBaseItems(argument: _exa_knowledge_base_pb_GetKnowledgeBaseItemsRequest, callback: grpc.requestCallback<_exa_knowledge_base_pb_GetKnowledgeBaseItemsResponse__Output>): grpc.ClientUnaryCall;
  getKnowledgeBaseItems(argument: _exa_knowledge_base_pb_GetKnowledgeBaseItemsRequest, metadata: grpc.Metadata, options: grpc.CallOptions, callback: grpc.requestCallback<_exa_knowledge_base_pb_GetKnowledgeBaseItemsResponse__Output>): grpc.ClientUnaryCall;
  getKnowledgeBaseItems(argument: _exa_knowledge_base_pb_GetKnowledgeBaseItemsRequest, metadata: grpc.Metadata, callback: grpc.requestCallback<_exa_knowledge_base_pb_GetKnowledgeBaseItemsResponse__Output>): grpc.ClientUnaryCall;
  getKnowledgeBaseItems(argument: _exa_knowledge_base_pb_GetKnowledgeBaseItemsRequest, options: grpc.CallOptions, callback: grpc.requestCallback<_exa_knowledge_base_pb_GetKnowledgeBaseItemsResponse__Output>): grpc.ClientUnaryCall;
  getKnowledgeBaseItems(argument: _exa_knowledge_base_pb_GetKnowledgeBaseItemsRequest, callback: grpc.requestCallback<_exa_knowledge_base_pb_GetKnowledgeBaseItemsResponse__Output>): grpc.ClientUnaryCall;
  
  GetKnowledgeBaseItemsForTeam(argument: _exa_knowledge_base_pb_GetKnowledgeBaseItemsForTeamRequest, metadata: grpc.Metadata, options: grpc.CallOptions, callback: grpc.requestCallback<_exa_knowledge_base_pb_GetKnowledgeBaseItemsForTeamResponse__Output>): grpc.ClientUnaryCall;
  GetKnowledgeBaseItemsForTeam(argument: _exa_knowledge_base_pb_GetKnowledgeBaseItemsForTeamRequest, metadata: grpc.Metadata, callback: grpc.requestCallback<_exa_knowledge_base_pb_GetKnowledgeBaseItemsForTeamResponse__Output>): grpc.ClientUnaryCall;
  GetKnowledgeBaseItemsForTeam(argument: _exa_knowledge_base_pb_GetKnowledgeBaseItemsForTeamRequest, options: grpc.CallOptions, callback: grpc.requestCallback<_exa_knowledge_base_pb_GetKnowledgeBaseItemsForTeamResponse__Output>): grpc.ClientUnaryCall;
  GetKnowledgeBaseItemsForTeam(argument: _exa_knowledge_base_pb_GetKnowledgeBaseItemsForTeamRequest, callback: grpc.requestCallback<_exa_knowledge_base_pb_GetKnowledgeBaseItemsForTeamResponse__Output>): grpc.ClientUnaryCall;
  getKnowledgeBaseItemsForTeam(argument: _exa_knowledge_base_pb_GetKnowledgeBaseItemsForTeamRequest, metadata: grpc.Metadata, options: grpc.CallOptions, callback: grpc.requestCallback<_exa_knowledge_base_pb_GetKnowledgeBaseItemsForTeamResponse__Output>): grpc.ClientUnaryCall;
  getKnowledgeBaseItemsForTeam(argument: _exa_knowledge_base_pb_GetKnowledgeBaseItemsForTeamRequest, metadata: grpc.Metadata, callback: grpc.requestCallback<_exa_knowledge_base_pb_GetKnowledgeBaseItemsForTeamResponse__Output>): grpc.ClientUnaryCall;
  getKnowledgeBaseItemsForTeam(argument: _exa_knowledge_base_pb_GetKnowledgeBaseItemsForTeamRequest, options: grpc.CallOptions, callback: grpc.requestCallback<_exa_knowledge_base_pb_GetKnowledgeBaseItemsForTeamResponse__Output>): grpc.ClientUnaryCall;
  getKnowledgeBaseItemsForTeam(argument: _exa_knowledge_base_pb_GetKnowledgeBaseItemsForTeamRequest, callback: grpc.requestCallback<_exa_knowledge_base_pb_GetKnowledgeBaseItemsForTeamResponse__Output>): grpc.ClientUnaryCall;
  
  ReadKnowledgeBaseItem(argument: _exa_knowledge_base_pb_ReadKnowledgeBaseItemRequest, metadata: grpc.Metadata, options: grpc.CallOptions, callback: grpc.requestCallback<_exa_knowledge_base_pb_ReadKnowledgeBaseItemResponse__Output>): grpc.ClientUnaryCall;
  ReadKnowledgeBaseItem(argument: _exa_knowledge_base_pb_ReadKnowledgeBaseItemRequest, metadata: grpc.Metadata, callback: grpc.requestCallback<_exa_knowledge_base_pb_ReadKnowledgeBaseItemResponse__Output>): grpc.ClientUnaryCall;
  ReadKnowledgeBaseItem(argument: _exa_knowledge_base_pb_ReadKnowledgeBaseItemRequest, options: grpc.CallOptions, callback: grpc.requestCallback<_exa_knowledge_base_pb_ReadKnowledgeBaseItemResponse__Output>): grpc.ClientUnaryCall;
  ReadKnowledgeBaseItem(argument: _exa_knowledge_base_pb_ReadKnowledgeBaseItemRequest, callback: grpc.requestCallback<_exa_knowledge_base_pb_ReadKnowledgeBaseItemResponse__Output>): grpc.ClientUnaryCall;
  readKnowledgeBaseItem(argument: _exa_knowledge_base_pb_ReadKnowledgeBaseItemRequest, metadata: grpc.Metadata, options: grpc.CallOptions, callback: grpc.requestCallback<_exa_knowledge_base_pb_ReadKnowledgeBaseItemResponse__Output>): grpc.ClientUnaryCall;
  readKnowledgeBaseItem(argument: _exa_knowledge_base_pb_ReadKnowledgeBaseItemRequest, metadata: grpc.Metadata, callback: grpc.requestCallback<_exa_knowledge_base_pb_ReadKnowledgeBaseItemResponse__Output>): grpc.ClientUnaryCall;
  readKnowledgeBaseItem(argument: _exa_knowledge_base_pb_ReadKnowledgeBaseItemRequest, options: grpc.CallOptions, callback: grpc.requestCallback<_exa_knowledge_base_pb_ReadKnowledgeBaseItemResponse__Output>): grpc.ClientUnaryCall;
  readKnowledgeBaseItem(argument: _exa_knowledge_base_pb_ReadKnowledgeBaseItemRequest, callback: grpc.requestCallback<_exa_knowledge_base_pb_ReadKnowledgeBaseItemResponse__Output>): grpc.ClientUnaryCall;
  
  RemoveConnection(argument: _exa_knowledge_base_pb_RemoveConnectionRequest, metadata: grpc.Metadata, options: grpc.CallOptions, callback: grpc.requestCallback<_exa_knowledge_base_pb_RemoveConnectionResponse__Output>): grpc.ClientUnaryCall;
  RemoveConnection(argument: _exa_knowledge_base_pb_RemoveConnectionRequest, metadata: grpc.Metadata, callback: grpc.requestCallback<_exa_knowledge_base_pb_RemoveConnectionResponse__Output>): grpc.ClientUnaryCall;
  RemoveConnection(argument: _exa_knowledge_base_pb_RemoveConnectionRequest, options: grpc.CallOptions, callback: grpc.requestCallback<_exa_knowledge_base_pb_RemoveConnectionResponse__Output>): grpc.ClientUnaryCall;
  RemoveConnection(argument: _exa_knowledge_base_pb_RemoveConnectionRequest, callback: grpc.requestCallback<_exa_knowledge_base_pb_RemoveConnectionResponse__Output>): grpc.ClientUnaryCall;
  removeConnection(argument: _exa_knowledge_base_pb_RemoveConnectionRequest, metadata: grpc.Metadata, options: grpc.CallOptions, callback: grpc.requestCallback<_exa_knowledge_base_pb_RemoveConnectionResponse__Output>): grpc.ClientUnaryCall;
  removeConnection(argument: _exa_knowledge_base_pb_RemoveConnectionRequest, metadata: grpc.Metadata, callback: grpc.requestCallback<_exa_knowledge_base_pb_RemoveConnectionResponse__Output>): grpc.ClientUnaryCall;
  removeConnection(argument: _exa_knowledge_base_pb_RemoveConnectionRequest, options: grpc.CallOptions, callback: grpc.requestCallback<_exa_knowledge_base_pb_RemoveConnectionResponse__Output>): grpc.ClientUnaryCall;
  removeConnection(argument: _exa_knowledge_base_pb_RemoveConnectionRequest, callback: grpc.requestCallback<_exa_knowledge_base_pb_RemoveConnectionResponse__Output>): grpc.ClientUnaryCall;
  
}

export interface KnowledgeBaseServiceHandlers extends grpc.UntypedServiceImplementation {
  CreateConnection: grpc.handleUnaryCall<_exa_knowledge_base_pb_CreateConnectionRequest__Output, _exa_knowledge_base_pb_CreateConnectionResponse>;
  
  CreateKnowledgeBaseItem: grpc.handleUnaryCall<_exa_knowledge_base_pb_CreateKnowledgeBaseItemRequest__Output, _exa_knowledge_base_pb_CreateKnowledgeBaseItemResponse>;
  
  DeleteKnowledgeBaseItem: grpc.handleUnaryCall<_exa_knowledge_base_pb_DeleteKnowledgeBaseItemRequest__Output, _exa_knowledge_base_pb_DeleteKnowledgeBaseItemResponse>;
  
  EditKnowledgeBaseItem: grpc.handleUnaryCall<_exa_knowledge_base_pb_EditKnowledgeBaseItemRequest__Output, _exa_knowledge_base_pb_EditKnowledgeBaseItemResponse>;
  
  GetConnection: grpc.handleUnaryCall<_exa_knowledge_base_pb_GetConnectionRequest__Output, _exa_knowledge_base_pb_GetConnectionResponse>;
  
  GetGithubIntegrationStatus: grpc.handleUnaryCall<_exa_knowledge_base_pb_GetGithubIntegrationStatusRequest__Output, _exa_knowledge_base_pb_GetGithubIntegrationStatusResponse>;
  
  GetGithubPullRequestSearchInfo: grpc.handleUnaryCall<_exa_knowledge_base_pb_GetGithubPullRequestSearchInfoRequest__Output, _exa_knowledge_base_pb_GetGithubPullRequestSearchInfoResponse>;
  
  GetKnowledgeBaseItems: grpc.handleUnaryCall<_exa_knowledge_base_pb_GetKnowledgeBaseItemsRequest__Output, _exa_knowledge_base_pb_GetKnowledgeBaseItemsResponse>;
  
  GetKnowledgeBaseItemsForTeam: grpc.handleUnaryCall<_exa_knowledge_base_pb_GetKnowledgeBaseItemsForTeamRequest__Output, _exa_knowledge_base_pb_GetKnowledgeBaseItemsForTeamResponse>;
  
  ReadKnowledgeBaseItem: grpc.handleUnaryCall<_exa_knowledge_base_pb_ReadKnowledgeBaseItemRequest__Output, _exa_knowledge_base_pb_ReadKnowledgeBaseItemResponse>;
  
  RemoveConnection: grpc.handleUnaryCall<_exa_knowledge_base_pb_RemoveConnectionRequest__Output, _exa_knowledge_base_pb_RemoveConnectionResponse>;
  
}

export interface KnowledgeBaseServiceDefinition extends grpc.ServiceDefinition {
  CreateConnection: MethodDefinition<_exa_knowledge_base_pb_CreateConnectionRequest, _exa_knowledge_base_pb_CreateConnectionResponse, _exa_knowledge_base_pb_CreateConnectionRequest__Output, _exa_knowledge_base_pb_CreateConnectionResponse__Output>
  CreateKnowledgeBaseItem: MethodDefinition<_exa_knowledge_base_pb_CreateKnowledgeBaseItemRequest, _exa_knowledge_base_pb_CreateKnowledgeBaseItemResponse, _exa_knowledge_base_pb_CreateKnowledgeBaseItemRequest__Output, _exa_knowledge_base_pb_CreateKnowledgeBaseItemResponse__Output>
  DeleteKnowledgeBaseItem: MethodDefinition<_exa_knowledge_base_pb_DeleteKnowledgeBaseItemRequest, _exa_knowledge_base_pb_DeleteKnowledgeBaseItemResponse, _exa_knowledge_base_pb_DeleteKnowledgeBaseItemRequest__Output, _exa_knowledge_base_pb_DeleteKnowledgeBaseItemResponse__Output>
  EditKnowledgeBaseItem: MethodDefinition<_exa_knowledge_base_pb_EditKnowledgeBaseItemRequest, _exa_knowledge_base_pb_EditKnowledgeBaseItemResponse, _exa_knowledge_base_pb_EditKnowledgeBaseItemRequest__Output, _exa_knowledge_base_pb_EditKnowledgeBaseItemResponse__Output>
  GetConnection: MethodDefinition<_exa_knowledge_base_pb_GetConnectionRequest, _exa_knowledge_base_pb_GetConnectionResponse, _exa_knowledge_base_pb_GetConnectionRequest__Output, _exa_knowledge_base_pb_GetConnectionResponse__Output>
  GetGithubIntegrationStatus: MethodDefinition<_exa_knowledge_base_pb_GetGithubIntegrationStatusRequest, _exa_knowledge_base_pb_GetGithubIntegrationStatusResponse, _exa_knowledge_base_pb_GetGithubIntegrationStatusRequest__Output, _exa_knowledge_base_pb_GetGithubIntegrationStatusResponse__Output>
  GetGithubPullRequestSearchInfo: MethodDefinition<_exa_knowledge_base_pb_GetGithubPullRequestSearchInfoRequest, _exa_knowledge_base_pb_GetGithubPullRequestSearchInfoResponse, _exa_knowledge_base_pb_GetGithubPullRequestSearchInfoRequest__Output, _exa_knowledge_base_pb_GetGithubPullRequestSearchInfoResponse__Output>
  GetKnowledgeBaseItems: MethodDefinition<_exa_knowledge_base_pb_GetKnowledgeBaseItemsRequest, _exa_knowledge_base_pb_GetKnowledgeBaseItemsResponse, _exa_knowledge_base_pb_GetKnowledgeBaseItemsRequest__Output, _exa_knowledge_base_pb_GetKnowledgeBaseItemsResponse__Output>
  GetKnowledgeBaseItemsForTeam: MethodDefinition<_exa_knowledge_base_pb_GetKnowledgeBaseItemsForTeamRequest, _exa_knowledge_base_pb_GetKnowledgeBaseItemsForTeamResponse, _exa_knowledge_base_pb_GetKnowledgeBaseItemsForTeamRequest__Output, _exa_knowledge_base_pb_GetKnowledgeBaseItemsForTeamResponse__Output>
  ReadKnowledgeBaseItem: MethodDefinition<_exa_knowledge_base_pb_ReadKnowledgeBaseItemRequest, _exa_knowledge_base_pb_ReadKnowledgeBaseItemResponse, _exa_knowledge_base_pb_ReadKnowledgeBaseItemRequest__Output, _exa_knowledge_base_pb_ReadKnowledgeBaseItemResponse__Output>
  RemoveConnection: MethodDefinition<_exa_knowledge_base_pb_RemoveConnectionRequest, _exa_knowledge_base_pb_RemoveConnectionResponse, _exa_knowledge_base_pb_RemoveConnectionRequest__Output, _exa_knowledge_base_pb_RemoveConnectionResponse__Output>
}
