// Original file: exa/codeium_common_pb/codeium_common.proto

export const AttributionStatus = {
  ATTRIBUTION_STATUS_UNSPECIFIED: 'ATTRIBUTION_STATUS_UNSPECIFIED',
  ATTRIBUTION_STATUS_NEW_CODE: 'ATTRIBUTION_STATUS_NEW_CODE',
  ATTRIBUTION_STATUS_NO_LICENSE: 'ATTRIBUTION_STATUS_NO_LICENSE',
  ATTRIBUTION_STATUS_NONPERMISSIVE: 'ATTRIBUTION_STATUS_NONPERMISSIVE',
  ATTRIBUTION_STATUS_PERMISSIVE: 'ATTRIBUTION_STATUS_PERMISSIVE',
  ATTRIBUTION_STATUS_PERMISSIVE_BLOCKED: 'ATTRIBUTION_STATUS_PERMISSIVE_BLOCKED',
} as const;

export type AttributionStatus =
  | 'ATTRIBUTION_STATUS_UNSPECIFIED'
  | 0
  | 'ATTRIBUTION_STATUS_NEW_CODE'
  | 1
  | 'ATTRIBUTION_STATUS_NO_LICENSE'
  | 2
  | 'ATTRIBUTION_STATUS_NONPERMISSIVE'
  | 3
  | 'ATTRIBUTION_STATUS_PERMISSIVE'
  | 4
  | 'ATTRIBUTION_STATUS_PERMISSIVE_BLOCKED'
  | 5

export type AttributionStatus__Output = typeof AttributionStatus[keyof typeof AttributionStatus]
