// Original file: exa/codeium_common_pb/codeium_common.proto

export const AuthSource = {
  AUTH_SOURCE_CODEIUM: 'AUTH_SOURCE_CODEIUM',
  AUTH_SOURCE_DEEPNOTE: 'AUTH_SOURCE_DEEPNOTE',
  AUTH_SOURCE_CODESANDBOX: 'AUTH_SOURCE_CODESANDBOX',
  AUTH_SOURCE_STACKBLITZ: 'AUTH_SOURCE_STACKBLITZ',
  AUTH_SOURCE_VALTOWN: 'AUTH_SOURCE_VALTOWN',
  AUTH_SOURCE_HEX: 'AUTH_SOURCE_HEX',
  AUTH_SOURCE_ZAPIER: 'AUTH_SOURCE_ZAPIER',
  AUTH_SOURCE_SUPERBLOCKS: 'AUTH_SOURCE_SUPERBLOCKS',
  AUTH_SOURCE_EMBARCADERO: 'AUTH_SOURCE_EMBARCADERO',
} as const;

export type AuthSource =
  | 'AUTH_SOURCE_CODEIUM'
  | 0
  | 'AUTH_SOURCE_DEEPNOTE'
  | 1
  | 'AUTH_SOURCE_CODESANDBOX'
  | 2
  | 'AUTH_SOURCE_STACKBLITZ'
  | 3
  | 'AUTH_SOURCE_VALTOWN'
  | 4
  | 'AUTH_SOURCE_HEX'
  | 5
  | 'AUTH_SOURCE_ZAPIER'
  | 6
  | 'AUTH_SOURCE_SUPERBLOCKS'
  | 7
  | 'AUTH_SOURCE_EMBARCADERO'
  | 8

export type AuthSource__Output = typeof AuthSource[keyof typeof AuthSource]
