// Original file: exa/codeium_common_pb/codeium_common.proto

export const BrowserInstallationStatus = {
  BROWSER_INSTALLATION_STATUS_UNSPECIFIED: 'BROWSER_INSTALLATION_STATUS_UNSPECIFIED',
  BROWSER_INSTALLATION_STATUS_NOT_INSTALLED: 'BROWSER_INSTALLATION_STATUS_NOT_INSTALLED',
  BROWSER_INSTALLATION_STATUS_IN_PROGRESS: 'BROWSER_INSTALLATION_STATUS_IN_PROGRESS',
  BROWSER_INSTALLATION_STATUS_COMPLETE: 'BROWSER_INSTALLATION_STATUS_COMPLETE',
  BROWSER_INSTALLATION_STATUS_ERROR: 'BROWSER_INSTALLATION_STATUS_ERROR',
} as const;

export type BrowserInstallationStatus =
  | 'BROWSER_INSTALLATION_STATUS_UNSPECIFIED'
  | 0
  | 'BROWSER_INSTALLATION_STATUS_NOT_INSTALLED'
  | 1
  | 'BROWSER_INSTALLATION_STATUS_IN_PROGRESS'
  | 2
  | 'BROWSER_INSTALLATION_STATUS_COMPLETE'
  | 3
  | 'BROWSER_INSTALLATION_STATUS_ERROR'
  | 4

export type BrowserInstallationStatus__Output = typeof BrowserInstallationStatus[keyof typeof BrowserInstallationStatus]
