// Original file: exa/codeium_common_pb/codeium_common.proto

export const CascadeCommandsAutoExecution = {
  CASCADE_COMMANDS_AUTO_EXECUTION_UNSPECIFIED: 'CASCADE_COMMANDS_AUTO_EXECUTION_UNSPECIFIED',
  CASCADE_COMMANDS_AUTO_EXECUTION_OFF: 'CASCADE_COMMANDS_AUTO_EXECUTION_OFF',
  CASCADE_COMMANDS_AUTO_EXECUTION_AUTO: 'CASCADE_COMMANDS_AUTO_EXECUTION_AUTO',
  CASCADE_COMMANDS_AUTO_EXECUTION_EAGER: 'CASCADE_COMMANDS_AUTO_EXECUTION_EAGER',
  CASCADE_COMMANDS_AUTO_EXECUTION_DISABLED: 'CASCADE_COMMANDS_AUTO_EXECUTION_DISABLED',
} as const;

export type CascadeCommandsAutoExecution =
  | 'CASCADE_COMMANDS_AUTO_EXECUTION_UNSPECIFIED'
  | 0
  | 'CASCADE_COMMANDS_AUTO_EXECUTION_OFF'
  | 1
  | 'CASCADE_COMMANDS_AUTO_EXECUTION_AUTO'
  | 2
  | 'CASCADE_COMMANDS_AUTO_EXECUTION_EAGER'
  | 3
  | 'CASCADE_COMMANDS_AUTO_EXECUTION_DISABLED'
  | 4

export type CascadeCommandsAutoExecution__Output = typeof CascadeCommandsAutoExecution[keyof typeof CascadeCommandsAutoExecution]
