// Original file: exa/codeium_common_pb/codeium_common.proto

export const CascadeNUXLocation = {
  CASCADE_NUX_LOCATION_UNSPECIFIED: 'CASCADE_NUX_LOCATION_UNSPECIFIED',
  CASCADE_NUX_LOCATION_CASCADE_INPUT: 'CASCADE_NUX_LOCATION_CASCADE_INPUT',
  CASCADE_NUX_LOCATION_MODEL_SELECTOR: 'CASCADE_NUX_LOCATION_MODEL_SELECTOR',
  CASCADE_NUX_LOCATION_RULES_TAB: 'CASCADE_NUX_LOCATION_RULES_TAB',
  CASCADE_NUX_LOCATION_REVERT_STEP: 'CASCADE_NUX_LOCATION_REVERT_STEP',
  CASCADE_NUX_LOCATION_PLAN_MODE: 'CASCADE_NUX_LOCATION_PLAN_MODE',
  CASCADE_NUX_LOCATION_WRITE_CHAT_MODE: 'CASCADE_NUX_LOCATION_WRITE_CHAT_MODE',
  CASCADE_NUX_LOCATION_TOOLBAR: 'CASCADE_NUX_LOCATION_TOOLBAR',
} as const;

export type CascadeNUXLocation =
  | 'CASCADE_NUX_LOCATION_UNSPECIFIED'
  | 0
  | 'CASCADE_NUX_LOCATION_CASCADE_INPUT'
  | 1
  | 'CASCADE_NUX_LOCATION_MODEL_SELECTOR'
  | 2
  | 'CASCADE_NUX_LOCATION_RULES_TAB'
  | 4
  | 'CASCADE_NUX_LOCATION_REVERT_STEP'
  | 6
  | 'CASCADE_NUX_LOCATION_PLAN_MODE'
  | 7
  | 'CASCADE_NUX_LOCATION_WRITE_CHAT_MODE'
  | 8
  | 'CASCADE_NUX_LOCATION_TOOLBAR'
  | 9

export type CascadeNUXLocation__Output = typeof CascadeNUXLocation[keyof typeof CascadeNUXLocation]
