// Original file: exa/codeium_common_pb/codeium_common.proto

export const CascadeNUXEvent = {
  CASCADE_NUX_EVENT_UNSPECIFIED: 'CASCADE_NUX_EVENT_UNSPECIFIED',
  CASCADE_NUX_EVENT_DIFF_OVERVIEW: 'CASCADE_NUX_EVENT_DIFF_OVERVIEW',
  CASCADE_NUX_EVENT_WEB_SEARCH: 'CASCADE_NUX_EVENT_WEB_SEARCH',
  CASCADE_NUX_EVENT_NEW_MODELS_WAVE2: 'CASCADE_NUX_EVENT_NEW_MODELS_WAVE2',
  CASCADE_NUX_EVENT_TOOL_CALL: 'CASCADE_NUX_EVENT_TOOL_CALL',
  CASCADE_NUX_EVENT_MODEL_SELECTOR_NUX: 'CASCADE_NUX_EVENT_MODEL_SELECTOR_NUX',
  CASCADE_NUX_EVENT_TOOL_CALL_PRICING_NUX: 'CASCADE_NUX_EVENT_TOOL_CALL_PRICING_NUX',
  CASCADE_NUX_EVENT_WRITE_CHAT_MODE: 'CASCADE_NUX_EVENT_WRITE_CHAT_MODE',
  CASCADE_NUX_EVENT_REVERT_STEP: 'CASCADE_NUX_EVENT_REVERT_STEP',
  CASCADE_NUX_EVENT_RULES: 'CASCADE_NUX_EVENT_RULES',
  CASCADE_NUX_EVENT_WEB_MENTION: 'CASCADE_NUX_EVENT_WEB_MENTION',
  CASCADE_NUX_EVENT_BACKGROUND_CASCADE: 'CASCADE_NUX_EVENT_BACKGROUND_CASCADE',
  CASCADE_NUX_EVENT_ANTHROPIC_API_PRICING: 'CASCADE_NUX_EVENT_ANTHROPIC_API_PRICING',
  CASCADE_NUX_EVENT_PLAN_MODE: 'CASCADE_NUX_EVENT_PLAN_MODE',
  CASCADE_NUX_EVENT_OPEN_BROWSER_URL: 'CASCADE_NUX_EVENT_OPEN_BROWSER_URL',
} as const;

export type CascadeNUXEvent =
  | 'CASCADE_NUX_EVENT_UNSPECIFIED'
  | 0
  | 'CASCADE_NUX_EVENT_DIFF_OVERVIEW'
  | 1
  | 'CASCADE_NUX_EVENT_WEB_SEARCH'
  | 2
  | 'CASCADE_NUX_EVENT_NEW_MODELS_WAVE2'
  | 3
  | 'CASCADE_NUX_EVENT_TOOL_CALL'
  | 4
  | 'CASCADE_NUX_EVENT_MODEL_SELECTOR_NUX'
  | 5
  | 'CASCADE_NUX_EVENT_TOOL_CALL_PRICING_NUX'
  | 6
  | 'CASCADE_NUX_EVENT_WRITE_CHAT_MODE'
  | 7
  | 'CASCADE_NUX_EVENT_REVERT_STEP'
  | 8
  | 'CASCADE_NUX_EVENT_RULES'
  | 9
  | 'CASCADE_NUX_EVENT_WEB_MENTION'
  | 10
  | 'CASCADE_NUX_EVENT_BACKGROUND_CASCADE'
  | 11
  | 'CASCADE_NUX_EVENT_ANTHROPIC_API_PRICING'
  | 12
  | 'CASCADE_NUX_EVENT_PLAN_MODE'
  | 13
  | 'CASCADE_NUX_EVENT_OPEN_BROWSER_URL'
  | 14

export type CascadeNUXEvent__Output = typeof CascadeNUXEvent[keyof typeof CascadeNUXEvent]
