// Original file: exa/codeium_common_pb/codeium_common.proto

export const CascadeNUXTrigger = {
  CASCADE_NUX_TRIGGER_UNSPECIFIED: 'CASCADE_NUX_TRIGGER_UNSPECIFIED',
  CASCADE_NUX_TRIGGER_PRODUCED_CODE_DIFF: 'CASCADE_NUX_TRIGGER_PRODUCED_CODE_DIFF',
  CASCADE_NUX_TRIGGER_OPEN_BROWSER_URL: 'CASCADE_NUX_TRIGGER_OPEN_BROWSER_URL',
  CASCADE_NUX_TRIGGER_WEB_SEARCH: 'CASCADE_NUX_TRIGGER_WEB_SEARCH',
} as const;

export type CascadeNUXTrigger =
  | 'CASCADE_NUX_TRIGGER_UNSPECIFIED'
  | 0
  | 'CASCADE_NUX_TRIGGER_PRODUCED_CODE_DIFF'
  | 1
  | 'CASCADE_NUX_TRIGGER_OPEN_BROWSER_URL'
  | 3
  | 'CASCADE_NUX_TRIGGER_WEB_SEARCH'
  | 4

export type CascadeNUXTrigger__Output = typeof CascadeNUXTrigger[keyof typeof CascadeNUXTrigger]
