// Original file: exa/codeium_common_pb/codeium_common.proto

export const CascadeWebRequestsAutoExecution = {
  CASCADE_WEB_REQUESTS_AUTO_EXECUTION_UNSPECIFIED: 'CASCADE_WEB_REQUESTS_AUTO_EXECUTION_UNSPECIFIED',
  CASCADE_WEB_REQUESTS_AUTO_EXECUTION_DISABLED: 'CASCADE_WEB_REQUESTS_AUTO_EXECUTION_DISABLED',
  CASCADE_WEB_REQUESTS_AUTO_EXECUTION_ALLOWLIST: 'CASCADE_WEB_REQUESTS_AUTO_EXECUTION_ALLOWLIST',
  CASCADE_WEB_REQUESTS_AUTO_EXECUTION_TURBO: 'CASCADE_WEB_REQUESTS_AUTO_EXECUTION_TURBO',
} as const;

export type CascadeWebRequestsAutoExecution =
  | 'CASCADE_WEB_REQUESTS_AUTO_EXECUTION_UNSPECIFIED'
  | 0
  | 'CASCADE_WEB_REQUESTS_AUTO_EXECUTION_DISABLED'
  | 1
  | 'CASCADE_WEB_REQUESTS_AUTO_EXECUTION_ALLOWLIST'
  | 2
  | 'CASCADE_WEB_REQUESTS_AUTO_EXECUTION_TURBO'
  | 3

export type CascadeWebRequestsAutoExecution__Output = typeof CascadeWebRequestsAutoExecution[keyof typeof CascadeWebRequestsAutoExecution]
