// Original file: exa/codeium_common_pb/codeium_common.proto

export const CodeContextSource = {
  CODE_CONTEXT_SOURCE_UNSPECIFIED: 'CODE_CONTEXT_SOURCE_UNSPECIFIED',
  CODE_CONTEXT_SOURCE_OPEN_DOCS: 'CODE_CONTEXT_SOURCE_OPEN_DOCS',
  CODE_CONTEXT_SOURCE_SEARCH_RESULT: 'CODE_CONTEXT_SOURCE_SEARCH_RESULT',
  CODE_CONTEXT_SOURCE_IMPORT: 'CODE_CONTEXT_SOURCE_IMPORT',
  CODE_CONTEXT_SOURCE_LOCAL_DIRECTORY: 'CODE_CONTEXT_SOURCE_LOCAL_DIRECTORY',
  CODE_CONTEXT_SOURCE_LAST_ACTIVE_DOC: 'CODE_CONTEXT_SOURCE_LAST_ACTIVE_DOC',
  CODE_CONTEXT_SOURCE_ORACLE_ITEMS: 'CODE_CONTEXT_SOURCE_ORACLE_ITEMS',
  CODE_CONTEXT_SOURCE_PINNED_CONTEXT: 'CODE_CONTEXT_SOURCE_PINNED_CONTEXT',
  CODE_CONTEXT_SOURCE_RESEARCH_STATE: 'CODE_CONTEXT_SOURCE_RESEARCH_STATE',
  CODE_CONTEXT_SOURCE_GROUND_TRUTH_PLAN_EDIT: 'CODE_CONTEXT_SOURCE_GROUND_TRUTH_PLAN_EDIT',
  CODE_CONTEXT_SOURCE_COMMIT_GRAPH: 'CODE_CONTEXT_SOURCE_COMMIT_GRAPH',
} as const;

export type CodeContextSource =
  | 'CODE_CONTEXT_SOURCE_UNSPECIFIED'
  | 0
  | 'CODE_CONTEXT_SOURCE_OPEN_DOCS'
  | 1
  | 'CODE_CONTEXT_SOURCE_SEARCH_RESULT'
  | 2
  | 'CODE_CONTEXT_SOURCE_IMPORT'
  | 3
  | 'CODE_CONTEXT_SOURCE_LOCAL_DIRECTORY'
  | 4
  | 'CODE_CONTEXT_SOURCE_LAST_ACTIVE_DOC'
  | 5
  | 'CODE_CONTEXT_SOURCE_ORACLE_ITEMS'
  | 6
  | 'CODE_CONTEXT_SOURCE_PINNED_CONTEXT'
  | 7
  | 'CODE_CONTEXT_SOURCE_RESEARCH_STATE'
  | 8
  | 'CODE_CONTEXT_SOURCE_GROUND_TRUTH_PLAN_EDIT'
  | 9
  | 'CODE_CONTEXT_SOURCE_COMMIT_GRAPH'
  | 10

export type CodeContextSource__Output = typeof CodeContextSource[keyof typeof CodeContextSource]
