// Original file: exa/codeium_common_pb/codeium_common.proto

export const CodeContextType = {
  CODE_CONTEXT_TYPE_UNSPECIFIED: 'CODE_CONTEXT_TYPE_UNSPECIFIED',
  CODE_CONTEXT_TYPE_FUNCTION: 'CODE_CONTEXT_TYPE_FUNCTION',
  CODE_CONTEXT_TYPE_CLASS: 'CODE_CONTEXT_TYPE_CLASS',
  CODE_CONTEXT_TYPE_IMPORT: 'CODE_CONTEXT_TYPE_IMPORT',
  CODE_CONTEXT_TYPE_NAIVE_LINECHUNK: 'CODE_CONTEXT_TYPE_NAIVE_LINECHUNK',
  CODE_CONTEXT_TYPE_REFERENCE_FUNCTION: 'CODE_CONTEXT_TYPE_REFERENCE_FUNCTION',
  CODE_CONTEXT_TYPE_REFERENCE_CLASS: 'CODE_CONTEXT_TYPE_REFERENCE_CLASS',
  CODE_CONTEXT_TYPE_FILE: 'CODE_CONTEXT_TYPE_FILE',
  CODE_CONTEXT_TYPE_TERMINAL: 'CODE_CONTEXT_TYPE_TERMINAL',
  CODE_CONTEXT_TYPE_DIRECTORY: 'CODE_CONTEXT_TYPE_DIRECTORY',
} as const;

export type CodeContextType =
  | 'CODE_CONTEXT_TYPE_UNSPECIFIED'
  | 0
  | 'CODE_CONTEXT_TYPE_FUNCTION'
  | 1
  | 'CODE_CONTEXT_TYPE_CLASS'
  | 2
  | 'CODE_CONTEXT_TYPE_IMPORT'
  | 3
  | 'CODE_CONTEXT_TYPE_NAIVE_LINECHUNK'
  | 4
  | 'CODE_CONTEXT_TYPE_REFERENCE_FUNCTION'
  | 5
  | 'CODE_CONTEXT_TYPE_REFERENCE_CLASS'
  | 6
  | 'CODE_CONTEXT_TYPE_FILE'
  | 7
  | 'CODE_CONTEXT_TYPE_TERMINAL'
  | 8
  | 'CODE_CONTEXT_TYPE_DIRECTORY'
  | 9

export type CodeContextType__Output = typeof CodeContextType[keyof typeof CodeContextType]
