// Original file: exa/codeium_common_pb/codeium_common.proto

export const CommandRequestSource = {
  COMMAND_REQUEST_SOURCE_UNSPECIFIED: 'COMMAND_REQUEST_SOURCE_UNSPECIFIED',
  COMMAND_REQUEST_SOURCE_DEFAULT: 'COMMAND_REQUEST_SOURCE_DEFAULT',
  COMMAND_REQUEST_SOURCE_FUNCTION_CODE_LENS: 'COMMAND_REQUEST_SOURCE_FUNCTION_CODE_LENS',
  COMMAND_REQUEST_SOURCE_CLASS_CODE_LENS: 'COMMAND_REQUEST_SOURCE_CLASS_CODE_LENS',
  COMMAND_REQUEST_SOURCE_RIGHT_CLICK_REFACTOR: 'COMMAND_REQUEST_SOURCE_RIGHT_CLICK_REFACTOR',
  COMMAND_REQUEST_SOURCE_SELECTION_HINT_CODE_LENS: 'COMMAND_REQUEST_SOURCE_SELECTION_HINT_CODE_LENS',
  COMMAND_REQUEST_SOURCE_LINE_HINT_CODE_LENS: 'COMMAND_REQUEST_SOURCE_LINE_HINT_CODE_LENS',
  COMMAND_REQUEST_SOURCE_PLAN: 'COMMAND_REQUEST_SOURCE_PLAN',
  COMMAND_REQUEST_SOURCE_FOLLOWUP: 'COMMAND_REQUEST_SOURCE_FOLLOWUP',
  COMMAND_REQUEST_SOURCE_PASTE_AND_TRANSLATE: 'COMMAND_REQUEST_SOURCE_PASTE_AND_TRANSLATE',
  COMMAND_REQUEST_SOURCE_SUPERCOMPLETE: 'COMMAND_REQUEST_SOURCE_SUPERCOMPLETE',
  COMMAND_REQUEST_SOURCE_FUNCTION_DOCSTRING: 'COMMAND_REQUEST_SOURCE_FUNCTION_DOCSTRING',
  COMMAND_REQUEST_SOURCE_FAST_APPLY: 'COMMAND_REQUEST_SOURCE_FAST_APPLY',
  COMMAND_REQUEST_SOURCE_TERMINAL: 'COMMAND_REQUEST_SOURCE_TERMINAL',
  COMMAND_REQUEST_SOURCE_TAB_JUMP: 'COMMAND_REQUEST_SOURCE_TAB_JUMP',
} as const;

export type CommandRequestSource =
  | 'COMMAND_REQUEST_SOURCE_UNSPECIFIED'
  | 0
  | 'COMMAND_REQUEST_SOURCE_DEFAULT'
  | 1
  | 'COMMAND_REQUEST_SOURCE_FUNCTION_CODE_LENS'
  | 2
  | 'COMMAND_REQUEST_SOURCE_CLASS_CODE_LENS'
  | 3
  | 'COMMAND_REQUEST_SOURCE_RIGHT_CLICK_REFACTOR'
  | 4
  | 'COMMAND_REQUEST_SOURCE_SELECTION_HINT_CODE_LENS'
  | 5
  | 'COMMAND_REQUEST_SOURCE_LINE_HINT_CODE_LENS'
  | 6
  | 'COMMAND_REQUEST_SOURCE_PLAN'
  | 7
  | 'COMMAND_REQUEST_SOURCE_FOLLOWUP'
  | 8
  | 'COMMAND_REQUEST_SOURCE_PASTE_AND_TRANSLATE'
  | 9
  | 'COMMAND_REQUEST_SOURCE_SUPERCOMPLETE'
  | 10
  | 'COMMAND_REQUEST_SOURCE_FUNCTION_DOCSTRING'
  | 11
  | 'COMMAND_REQUEST_SOURCE_FAST_APPLY'
  | 12
  | 'COMMAND_REQUEST_SOURCE_TERMINAL'
  | 13
  | 'COMMAND_REQUEST_SOURCE_TAB_JUMP'
  | 14

export type CommandRequestSource__Output = typeof CommandRequestSource[keyof typeof CommandRequestSource]
