// Original file: exa/codeium_common_pb/codeium_common.proto

export const ConversationalPlannerMode = {
  CONVERSATIONAL_PLANNER_MODE_UNSPECIFIED: 'CONVERSATIONAL_PLANNER_MODE_UNSPECIFIED',
  CONVERSATIONAL_PLANNER_MODE_DEFAULT: 'CONVERSATIONAL_PLANNER_MODE_DEFAULT',
  CONVERSATIONAL_PLANNER_MODE_READ_ONLY: 'CONVERSATIONAL_PLANNER_MODE_READ_ONLY',
  CONVERSATIONAL_PLANNER_MODE_NO_TOOL: 'CONVERSATIONAL_PLANNER_MODE_NO_TOOL',
  CONVERSATIONAL_PLANNER_MODE_EXPLORE: 'CONVERSATIONAL_PLANNER_MODE_EXPLORE',
  CONVERSATIONAL_PLANNER_MODE_PLANNING: 'CONVERSATIONAL_PLANNER_MODE_PLANNING',
  CONVERSATIONAL_PLANNER_MODE_AUTO: 'CONVERSATIONAL_PLANNER_MODE_AUTO',
} as const;

export type ConversationalPlannerMode =
  | 'CONVERSATIONAL_PLANNER_MODE_UNSPECIFIED'
  | 0
  | 'CONVERSATIONAL_PLANNER_MODE_DEFAULT'
  | 1
  | 'CONVERSATIONAL_PLANNER_MODE_READ_ONLY'
  | 2
  | 'CONVERSATIONAL_PLANNER_MODE_NO_TOOL'
  | 3
  | 'CONVERSATIONAL_PLANNER_MODE_EXPLORE'
  | 4
  | 'CONVERSATIONAL_PLANNER_MODE_PLANNING'
  | 5
  | 'CONVERSATIONAL_PLANNER_MODE_AUTO'
  | 6

export type ConversationalPlannerMode__Output = typeof ConversationalPlannerMode[keyof typeof ConversationalPlannerMode]
