// Original file: exa/codeium_common_pb/codeium_common.proto

export const DeepWikiModelType = {
  DEEP_WIKI_MODEL_TYPE_UNSPECIFIED: 'DEEP_WIKI_MODEL_TYPE_UNSPECIFIED',
  DEEP_WIKI_MODEL_TYPE_CAPACITY_FALLBACK: 'DEEP_WIKI_MODEL_TYPE_CAPACITY_FALLBACK',
  DEEP_WIKI_MODEL_TYPE_LITE_FREE: 'DEEP_WIKI_MODEL_TYPE_LITE_FREE',
  DEEP_WIKI_MODEL_TYPE_LITE_PAID: 'DEEP_WIKI_MODEL_TYPE_LITE_PAID',
  DEEP_WIKI_MODEL_TYPE_PREMIUM: 'DEEP_WIKI_MODEL_TYPE_PREMIUM',
} as const;

export type DeepWikiModelType =
  | 'DEEP_WIKI_MODEL_TYPE_UNSPECIFIED'
  | 0
  | 'DEEP_WIKI_MODEL_TYPE_CAPACITY_FALLBACK'
  | 1
  | 'DEEP_WIKI_MODEL_TYPE_LITE_FREE'
  | 2
  | 'DEEP_WIKI_MODEL_TYPE_LITE_PAID'
  | 3
  | 'DEEP_WIKI_MODEL_TYPE_PREMIUM'
  | 4

export type DeepWikiModelType__Output = typeof DeepWikiModelType[keyof typeof DeepWikiModelType]
