// Original file: exa/codeium_common_pb/codeium_common.proto

export const DeploymentBuildStatus = {
  DEPLOYMENT_BUILD_STATUS_UNSPECIFIED: 'DEPLOYMENT_BUILD_STATUS_UNSPECIFIED',
  DEPLOYMENT_BUILD_STATUS_QUEUED: 'DEPLOYMENT_BUILD_STATUS_QUEUED',
  DEPLOYMENT_BUILD_STATUS_INITIALIZING: 'DEPLOYMENT_BUILD_STATUS_INITIALIZING',
  DEPLOYMENT_BUILD_STATUS_BUILDING: 'DEPLOYMENT_BUILD_STATUS_BUILDING',
  DEPLOYMENT_BUILD_STATUS_ERROR: 'DEPLOYMENT_BUILD_STATUS_ERROR',
  DEPLOYMENT_BUILD_STATUS_READY: 'DEPLOYMENT_BUILD_STATUS_READY',
  DEPLOYMENT_BUILD_STATUS_CANCELED: 'DEPLOYMENT_BUILD_STATUS_CANCELED',
} as const;

export type DeploymentBuildStatus =
  | 'DEPLOYMENT_BUILD_STATUS_UNSPECIFIED'
  | 0
  | 'DEPLOYMENT_BUILD_STATUS_QUEUED'
  | 1
  | 'DEPLOYMENT_BUILD_STATUS_INITIALIZING'
  | 2
  | 'DEPLOYMENT_BUILD_STATUS_BUILDING'
  | 3
  | 'DEPLOYMENT_BUILD_STATUS_ERROR'
  | 4
  | 'DEPLOYMENT_BUILD_STATUS_READY'
  | 5
  | 'DEPLOYMENT_BUILD_STATUS_CANCELED'
  | 6

export type DeploymentBuildStatus__Output = typeof DeploymentBuildStatus[keyof typeof DeploymentBuildStatus]
