// Original file: exa/codeium_common_pb/codeium_common.proto

export const DocumentType = {
  DOCUMENT_TYPE_UNSPECIFIED: 'DOCUMENT_TYPE_UNSPECIFIED',
  DOCUMENT_TYPE_SLACK_MESSAGE: 'DOCUMENT_TYPE_SLACK_MESSAGE',
  DOCUMENT_TYPE_SLACK_CHANNEL: 'DOCUMENT_TYPE_SLACK_CHANNEL',
  DOCUMENT_TYPE_GITHUB_ISSUE: 'DOCUMENT_TYPE_GITHUB_ISSUE',
  DOCUMENT_TYPE_GITHUB_ISSUE_COMMENT: 'DOCUMENT_TYPE_GITHUB_ISSUE_COMMENT',
  DOCUMENT_TYPE_GITHUB_REPO: 'DOCUMENT_TYPE_GITHUB_REPO',
  DOCUMENT_TYPE_GOOGLE_DRIVE_FILE: 'DOCUMENT_TYPE_GOOGLE_DRIVE_FILE',
  DOCUMENT_TYPE_GOOGLE_DRIVE_FOLDER: 'DOCUMENT_TYPE_GOOGLE_DRIVE_FOLDER',
  DOCUMENT_TYPE_JIRA_ISSUE: 'DOCUMENT_TYPE_JIRA_ISSUE',
  DOCUMENT_TYPE_CCI: 'DOCUMENT_TYPE_CCI',
} as const;

export type DocumentType =
  | 'DOCUMENT_TYPE_UNSPECIFIED'
  | 0
  | 'DOCUMENT_TYPE_SLACK_MESSAGE'
  | 1
  | 'DOCUMENT_TYPE_SLACK_CHANNEL'
  | 2
  | 'DOCUMENT_TYPE_GITHUB_ISSUE'
  | 3
  | 'DOCUMENT_TYPE_GITHUB_ISSUE_COMMENT'
  | 4
  | 'DOCUMENT_TYPE_GITHUB_REPO'
  | 8
  | 'DOCUMENT_TYPE_GOOGLE_DRIVE_FILE'
  | 5
  | 'DOCUMENT_TYPE_GOOGLE_DRIVE_FOLDER'
  | 6
  | 'DOCUMENT_TYPE_JIRA_ISSUE'
  | 7
  | 'DOCUMENT_TYPE_CCI'
  | 9

export type DocumentType__Output = typeof DocumentType[keyof typeof DocumentType]
