// Original file: exa/codeium_common_pb/codeium_common.proto

export const EmbeddingPrefix = {
  EMBEDDING_PREFIX_UNSPECIFIED: 'EMBEDDING_PREFIX_UNSPECIFIED',
  EMBEDDING_PREFIX_NOMIC_DOCUMENT: 'EMBEDDING_PREFIX_NOMIC_DOCUMENT',
  EMBEDDING_PREFIX_NOMIC_SEARCH: 'EMBEDDING_PREFIX_NOMIC_SEARCH',
  EMBEDDING_PREFIX_NOMIC_CLASSIFICATION: 'EMBEDDING_PREFIX_NOMIC_CLASSIFICATION',
  EMBEDDING_PREFIX_NOMIC_CLUSTERING: 'EMBEDDING_PREFIX_NOMIC_CLUSTERING',
} as const;

export type EmbeddingPrefix =
  | 'EMBEDDING_PREFIX_UNSPECIFIED'
  | 0
  | 'EMBEDDING_PREFIX_NOMIC_DOCUMENT'
  | 1
  | 'EMBEDDING_PREFIX_NOMIC_SEARCH'
  | 2
  | 'EMBEDDING_PREFIX_NOMIC_CLASSIFICATION'
  | 3
  | 'EMBEDDING_PREFIX_NOMIC_CLUSTERING'
  | 4

export type EmbeddingPrefix__Output = typeof EmbeddingPrefix[keyof typeof EmbeddingPrefix]
