// Original file: exa/codeium_common_pb/codeium_common.proto

export const EmbedType = {
  EMBED_TYPE_UNSPECIFIED: 'EMBED_TYPE_UNSPECIFIED',
  EMBED_TYPE_RAW_SOURCE: 'EMBED_TYPE_RAW_SOURCE',
  EMBED_TYPE_DOCSTRING: 'EMBED_TYPE_DOCSTRING',
  EMBED_TYPE_FUNCTION: 'EMBED_TYPE_FUNCTION',
  EMBED_TYPE_NODEPATH: 'EMBED_TYPE_NODEPATH',
  EMBED_TYPE_DECLARATION: 'EMBED_TYPE_DECLARATION',
  EMBED_TYPE_NAIVE_CHUNK: 'EMBED_TYPE_NAIVE_CHUNK',
  EMBED_TYPE_SIGNATURE: 'EMBED_TYPE_SIGNATURE',
} as const;

export type EmbedType =
  | 'EMBED_TYPE_UNSPECIFIED'
  | 0
  | 'EMBED_TYPE_RAW_SOURCE'
  | 1
  | 'EMBED_TYPE_DOCSTRING'
  | 2
  | 'EMBED_TYPE_FUNCTION'
  | 3
  | 'EMBED_TYPE_NODEPATH'
  | 4
  | 'EMBED_TYPE_DECLARATION'
  | 5
  | 'EMBED_TYPE_NAIVE_CHUNK'
  | 6
  | 'EMBED_TYPE_SIGNATURE'
  | 7

export type EmbedType__Output = typeof EmbedType[keyof typeof EmbedType]
