// Original file: exa/codeium_common_pb/codeium_common.proto

export const EventType = {
  EVENT_TYPE_UNSPECIFIED: 'EVENT_TYPE_UNSPECIFIED',
  EVENT_TYPE_ENABLE_CODEIUM: 'EVENT_TYPE_ENABLE_CODEIUM',
  EVENT_TYPE_DISABLE_CODEIUM: 'EVENT_TYPE_DISABLE_CODEIUM',
  EVENT_TYPE_SHOW_PREVIOUS_COMPLETION: 'EVENT_TYPE_SHOW_PREVIOUS_COMPLETION',
  EVENT_TYPE_SHOW_NEXT_COMPLETION: 'EVENT_TYPE_SHOW_NEXT_COMPLETION',
  EVENT_TYPE_COPILOT_STATUS: 'EVENT_TYPE_COPILOT_STATUS',
  EVENT_TYPE_COMPLETION_SUPPRESSED: 'EVENT_TYPE_COMPLETION_SUPPRESSED',
  EVENT_TYPE_MEMORY_STATS: 'EVENT_TYPE_MEMORY_STATS',
  EVENT_TYPE_LOCAL_CONTEXT_RELEVANCE_CHECK: 'EVENT_TYPE_LOCAL_CONTEXT_RELEVANCE_CHECK',
  EVENT_TYPE_ACTIVE_EDITOR_CHANGED: 'EVENT_TYPE_ACTIVE_EDITOR_CHANGED',
  EVENT_TYPE_SHOW_PREVIOUS_CORTEX_STEP: 'EVENT_TYPE_SHOW_PREVIOUS_CORTEX_STEP',
  EVENT_TYPE_SHOW_NEXT_CORTEX_STEP: 'EVENT_TYPE_SHOW_NEXT_CORTEX_STEP',
  EVENT_TYPE_INDEXER_STATS: 'EVENT_TYPE_INDEXER_STATS',
  EVENT_TYPE_SYSTEM_METRICS_TELEMETRY: 'EVENT_TYPE_SYSTEM_METRICS_TELEMETRY',
} as const;

export type EventType =
  | 'EVENT_TYPE_UNSPECIFIED'
  | 0
  | 'EVENT_TYPE_ENABLE_CODEIUM'
  | 1
  | 'EVENT_TYPE_DISABLE_CODEIUM'
  | 2
  | 'EVENT_TYPE_SHOW_PREVIOUS_COMPLETION'
  | 3
  | 'EVENT_TYPE_SHOW_NEXT_COMPLETION'
  | 4
  | 'EVENT_TYPE_COPILOT_STATUS'
  | 5
  | 'EVENT_TYPE_COMPLETION_SUPPRESSED'
  | 6
  | 'EVENT_TYPE_MEMORY_STATS'
  | 8
  | 'EVENT_TYPE_LOCAL_CONTEXT_RELEVANCE_CHECK'
  | 9
  | 'EVENT_TYPE_ACTIVE_EDITOR_CHANGED'
  | 10
  | 'EVENT_TYPE_SHOW_PREVIOUS_CORTEX_STEP'
  | 11
  | 'EVENT_TYPE_SHOW_NEXT_CORTEX_STEP'
  | 12
  | 'EVENT_TYPE_INDEXER_STATS'
  | 13
  | 'EVENT_TYPE_SYSTEM_METRICS_TELEMETRY'
  | 14

export type EventType__Output = typeof EventType[keyof typeof EventType]
