// Original file: exa/codeium_common_pb/codeium_common.proto

export const ExtensionPanelTab = {
  EXTENSION_PANEL_TAB_UNSPECIFIED: 'EXTENSION_PANEL_TAB_UNSPECIFIED',
  EXTENSION_PANEL_TAB_CHAT: 'EXTENSION_PANEL_TAB_CHAT',
  EXTENSION_PANEL_TAB_PROFILE: 'EXTENSION_PANEL_TAB_PROFILE',
  EXTENSION_PANEL_TAB_BRAIN: 'EXTENSION_PANEL_TAB_BRAIN',
  EXTENSION_PANEL_TAB_COMMAND: 'EXTENSION_PANEL_TAB_COMMAND',
  EXTENSION_PANEL_TAB_CORTEX: 'EXTENSION_PANEL_TAB_CORTEX',
  EXTENSION_PANEL_TAB_DEBUG: 'EXTENSION_PANEL_TAB_DEBUG',
} as const;

export type ExtensionPanelTab =
  | 'EXTENSION_PANEL_TAB_UNSPECIFIED'
  | 0
  | 'EXTENSION_PANEL_TAB_CHAT'
  | 1
  | 'EXTENSION_PANEL_TAB_PROFILE'
  | 2
  | 'EXTENSION_PANEL_TAB_BRAIN'
  | 4
  | 'EXTENSION_PANEL_TAB_COMMAND'
  | 5
  | 'EXTENSION_PANEL_TAB_CORTEX'
  | 6
  | 'EXTENSION_PANEL_TAB_DEBUG'
  | 7

export type ExtensionPanelTab__Output = typeof ExtensionPanelTab[keyof typeof ExtensionPanelTab]
