// Original file: exa/codeium_common_pb/codeium_common.proto

export const FeatureUsageType = {
  FEATURE_USAGE_TYPE_UNSPECIFIED: 'FEATURE_USAGE_TYPE_UNSPECIFIED',
  FEATURE_USAGE_TYPE_CASCADE_BROWSER: 'FEATURE_USAGE_TYPE_CASCADE_BROWSER',
  FEATURE_USAGE_TYPE_CASCADE_WEB_AT_MENTION: 'FEATURE_USAGE_TYPE_CASCADE_WEB_AT_MENTION',
  FEATURE_USAGE_TYPE_CASCADE_REVERT_TO_STEP: 'FEATURE_USAGE_TYPE_CASCADE_REVERT_TO_STEP',
  FEATURE_USAGE_TYPE_CASCADE_CLICK_MODEL_SELECTOR: 'FEATURE_USAGE_TYPE_CASCADE_CLICK_MODEL_SELECTOR',
  FEATURE_USAGE_TYPE_CASCADE_MESSAGE_FEEDBACK: 'FEATURE_USAGE_TYPE_CASCADE_MESSAGE_FEEDBACK',
} as const;

export type FeatureUsageType =
  | 'FEATURE_USAGE_TYPE_UNSPECIFIED'
  | 0
  | 'FEATURE_USAGE_TYPE_CASCADE_BROWSER'
  | 1
  | 'FEATURE_USAGE_TYPE_CASCADE_WEB_AT_MENTION'
  | 2
  | 'FEATURE_USAGE_TYPE_CASCADE_REVERT_TO_STEP'
  | 3
  | 'FEATURE_USAGE_TYPE_CASCADE_CLICK_MODEL_SELECTOR'
  | 4
  | 'FEATURE_USAGE_TYPE_CASCADE_MESSAGE_FEEDBACK'
  | 5

export type FeatureUsageType__Output = typeof FeatureUsageType[keyof typeof FeatureUsageType]
