// Original file: exa/codeium_common_pb/codeium_common.proto

export const FilterReason = {
  FILTER_REASON_NONE: 'FILTER_REASON_NONE',
  FILTER_REASON_INCOMPLETE: 'FILTER_REASON_INCOMPLETE',
  FILTER_REASON_EMPTY: 'FILTER_REASON_EMPTY',
  FILTER_REASON_REPETITIVE: 'FILTER_REASON_REPETITIVE',
  FILTER_REASON_DUPLICATE: 'FILTER_REASON_DUPLICATE',
  FILTER_REASON_LONG_LINE: 'FILTER_REASON_LONG_LINE',
  FILTER_REASON_COMPLETIONS_CUTOFF: 'FILTER_REASON_COMPLETIONS_CUTOFF',
  FILTER_REASON_ATTRIBUTION: 'FILTER_REASON_ATTRIBUTION',
  FILTER_REASON_NON_MATCHING: 'FILTER_REASON_NON_MATCHING',
  FILTER_REASON_NON_INSERTION: 'FILTER_REASON_NON_INSERTION',
} as const;

export type FilterReason =
  | 'FILTER_REASON_NONE'
  | 0
  | 'FILTER_REASON_INCOMPLETE'
  | 1
  | 'FILTER_REASON_EMPTY'
  | 2
  | 'FILTER_REASON_REPETITIVE'
  | 3
  | 'FILTER_REASON_DUPLICATE'
  | 4
  | 'FILTER_REASON_LONG_LINE'
  | 5
  | 'FILTER_REASON_COMPLETIONS_CUTOFF'
  | 6
  | 'FILTER_REASON_ATTRIBUTION'
  | 7
  | 'FILTER_REASON_NON_MATCHING'
  | 8
  | 'FILTER_REASON_NON_INSERTION'
  | 9

export type FilterReason__Output = typeof FilterReason[keyof typeof FilterReason]
