// Original file: exa/codeium_common_pb/codeium_common.proto

export const IndexChoice = {
  INDEX_CHOICE_UNSPECIFIED: 'INDEX_CHOICE_UNSPECIFIED',
  INDEX_CHOICE_GITHUB_BASE: 'INDEX_CHOICE_GITHUB_BASE',
  INDEX_CHOICE_SLACK_BASE: 'INDEX_CHOICE_SLACK_BASE',
  INDEX_CHOICE_SLACK_AGGREGATE: 'INDEX_CHOICE_SLACK_AGGREGATE',
  INDEX_CHOICE_GOOGLE_DRIVE_BASE: 'INDEX_CHOICE_GOOGLE_DRIVE_BASE',
  INDEX_CHOICE_JIRA_BASE: 'INDEX_CHOICE_JIRA_BASE',
  INDEX_CHOICE_SCM: 'INDEX_CHOICE_SCM',
} as const;

export type IndexChoice =
  | 'INDEX_CHOICE_UNSPECIFIED'
  | 0
  | 'INDEX_CHOICE_GITHUB_BASE'
  | 1
  | 'INDEX_CHOICE_SLACK_BASE'
  | 2
  | 'INDEX_CHOICE_SLACK_AGGREGATE'
  | 3
  | 'INDEX_CHOICE_GOOGLE_DRIVE_BASE'
  | 4
  | 'INDEX_CHOICE_JIRA_BASE'
  | 5
  | 'INDEX_CHOICE_SCM'
  | 6

export type IndexChoice__Output = typeof IndexChoice[keyof typeof IndexChoice]
