// Original file: exa/codeium_common_pb/codeium_common.proto

export const LastUpdateType = {
  LAST_UPDATE_TYPE_UNSPECIFIED: 'LAST_UPDATE_TYPE_UNSPECIFIED',
  LAST_UPDATE_TYPE_OVERALL: 'LAST_UPDATE_TYPE_OVERALL',
  LAST_UPDATE_TYPE_LAST_AUTOCOMPLETE_USAGE_TIME: 'LAST_UPDATE_TYPE_LAST_AUTOCOMPLETE_USAGE_TIME',
  LAST_UPDATE_TYPE_LAST_CHAT_USAGE_TIME: 'LAST_UPDATE_TYPE_LAST_CHAT_USAGE_TIME',
  LAST_UPDATE_TYPE_LAST_COMMAND_USAGE_TIME: 'LAST_UPDATE_TYPE_LAST_COMMAND_USAGE_TIME',
} as const;

export type LastUpdateType =
  | 'LAST_UPDATE_TYPE_UNSPECIFIED'
  | 0
  | 'LAST_UPDATE_TYPE_OVERALL'
  | 1
  | 'LAST_UPDATE_TYPE_LAST_AUTOCOMPLETE_USAGE_TIME'
  | 2
  | 'LAST_UPDATE_TYPE_LAST_CHAT_USAGE_TIME'
  | 3
  | 'LAST_UPDATE_TYPE_LAST_COMMAND_USAGE_TIME'
  | 4

export type LastUpdateType__Output = typeof LastUpdateType[keyof typeof LastUpdateType]
