// Original file: exa/codeium_common_pb/codeium_common.proto

export const MarkdownNodeType = {
  MARKDOWN_NODE_TYPE_UNSPECIFIED: 'MARKDOWN_NODE_TYPE_UNSPECIFIED',
  MARKDOWN_NODE_TYPE_HEADER_1: 'MARKDOWN_NODE_TYPE_HEADER_1',
  MARKDOWN_NODE_TYPE_HEADER_2: 'MARKDOWN_NODE_TYPE_HEADER_2',
  MARKDOWN_NODE_TYPE_HEADER_3: 'MARKDOWN_NODE_TYPE_HEADER_3',
  MARKDOWN_NODE_TYPE_HEADER_4: 'MARKDOWN_NODE_TYPE_HEADER_4',
  MARKDOWN_NODE_TYPE_HEADER_5: 'MARKDOWN_NODE_TYPE_HEADER_5',
  MARKDOWN_NODE_TYPE_HEADER_6: 'MARKDOWN_NODE_TYPE_HEADER_6',
} as const;

export type MarkdownNodeType =
  | 'MARKDOWN_NODE_TYPE_UNSPECIFIED'
  | 0
  | 'MARKDOWN_NODE_TYPE_HEADER_1'
  | 1
  | 'MARKDOWN_NODE_TYPE_HEADER_2'
  | 2
  | 'MARKDOWN_NODE_TYPE_HEADER_3'
  | 3
  | 'MARKDOWN_NODE_TYPE_HEADER_4'
  | 4
  | 'MARKDOWN_NODE_TYPE_HEADER_5'
  | 5
  | 'MARKDOWN_NODE_TYPE_HEADER_6'
  | 6

export type MarkdownNodeType__Output = typeof MarkdownNodeType[keyof typeof MarkdownNodeType]
