// Original file: exa/codeium_common_pb/codeium_common.proto

export const ModelProvider = {
  MODEL_PROVIDER_UNSPECIFIED: 'MODEL_PROVIDER_UNSPECIFIED',
  MODEL_PROVIDER_WINDSURF: 'MODEL_PROVIDER_WINDSURF',
  MODEL_PROVIDER_OPENAI: 'MODEL_PROVIDER_OPENAI',
  MODEL_PROVIDER_ANTHROPIC: 'MODEL_PROVIDER_ANTHROPIC',
  MODEL_PROVIDER_GOOGLE: 'MODEL_PROVIDER_GOOGLE',
  MODEL_PROVIDER_XAI: 'MODEL_PROVIDER_XAI',
  MODEL_PROVIDER_DEEPSEEK: 'MODEL_PROVIDER_DEEPSEEK',
  MODEL_PROVIDER_MOONSHOT: 'MODEL_PROVIDER_MOONSHOT',
  MODEL_PROVIDER_QWEN: 'MODEL_PROVIDER_QWEN',
} as const;

export type ModelProvider =
  | 'MODEL_PROVIDER_UNSPECIFIED'
  | 0
  | 'MODEL_PROVIDER_WINDSURF'
  | 1
  | 'MODEL_PROVIDER_OPENAI'
  | 2
  | 'MODEL_PROVIDER_ANTHROPIC'
  | 3
  | 'MODEL_PROVIDER_GOOGLE'
  | 4
  | 'MODEL_PROVIDER_XAI'
  | 5
  | 'MODEL_PROVIDER_DEEPSEEK'
  | 6
  | 'MODEL_PROVIDER_MOONSHOT'
  | 7
  | 'MODEL_PROVIDER_QWEN'
  | 8

export type ModelProvider__Output = typeof ModelProvider[keyof typeof ModelProvider]
