// Original file: exa/codeium_common_pb/codeium_common.proto

export const PromptElementKind = {
  PROMPT_ELEMENT_KIND_UNSPECIFIED: 'PROMPT_ELEMENT_KIND_UNSPECIFIED',
  PROMPT_ELEMENT_KIND_FILE_MARKER: 'PROMPT_ELEMENT_KIND_FILE_MARKER',
  PROMPT_ELEMENT_KIND_OTHER_DOCUMENT: 'PROMPT_ELEMENT_KIND_OTHER_DOCUMENT',
  PROMPT_ELEMENT_KIND_BEFORE_CURSOR: 'PROMPT_ELEMENT_KIND_BEFORE_CURSOR',
  PROMPT_ELEMENT_KIND_AFTER_CURSOR: 'PROMPT_ELEMENT_KIND_AFTER_CURSOR',
  PROMPT_ELEMENT_KIND_FIM: 'PROMPT_ELEMENT_KIND_FIM',
  PROMPT_ELEMENT_KIND_SOT: 'PROMPT_ELEMENT_KIND_SOT',
  PROMPT_ELEMENT_KIND_EOT: 'PROMPT_ELEMENT_KIND_EOT',
  PROMPT_ELEMENT_KIND_CODE_CONTEXT_ITEM: 'PROMPT_ELEMENT_KIND_CODE_CONTEXT_ITEM',
  PROMPT_ELEMENT_KIND_INSTRUCTION: 'PROMPT_ELEMENT_KIND_INSTRUCTION',
  PROMPT_ELEMENT_KIND_SELECTION: 'PROMPT_ELEMENT_KIND_SELECTION',
  PROMPT_ELEMENT_KIND_TRAJECTORY_STEP: 'PROMPT_ELEMENT_KIND_TRAJECTORY_STEP',
  PROMPT_ELEMENT_KIND_ACTIVE_DOCUMENT: 'PROMPT_ELEMENT_KIND_ACTIVE_DOCUMENT',
  PROMPT_ELEMENT_KIND_CACHED_MESSAGE: 'PROMPT_ELEMENT_KIND_CACHED_MESSAGE',
} as const;

export type PromptElementKind =
  | 'PROMPT_ELEMENT_KIND_UNSPECIFIED'
  | 0
  | 'PROMPT_ELEMENT_KIND_FILE_MARKER'
  | 2
  | 'PROMPT_ELEMENT_KIND_OTHER_DOCUMENT'
  | 4
  | 'PROMPT_ELEMENT_KIND_BEFORE_CURSOR'
  | 5
  | 'PROMPT_ELEMENT_KIND_AFTER_CURSOR'
  | 7
  | 'PROMPT_ELEMENT_KIND_FIM'
  | 8
  | 'PROMPT_ELEMENT_KIND_SOT'
  | 9
  | 'PROMPT_ELEMENT_KIND_EOT'
  | 10
  | 'PROMPT_ELEMENT_KIND_CODE_CONTEXT_ITEM'
  | 13
  | 'PROMPT_ELEMENT_KIND_INSTRUCTION'
  | 14
  | 'PROMPT_ELEMENT_KIND_SELECTION'
  | 15
  | 'PROMPT_ELEMENT_KIND_TRAJECTORY_STEP'
  | 16
  | 'PROMPT_ELEMENT_KIND_ACTIVE_DOCUMENT'
  | 17
  | 'PROMPT_ELEMENT_KIND_CACHED_MESSAGE'
  | 18

export type PromptElementKind__Output = typeof PromptElementKind[keyof typeof PromptElementKind]
