// Original file: exa/codeium_common_pb/codeium_common.proto

export const PromptTemplaterType = {
  PROMPT_TEMPLATER_TYPE_UNSPECIFIED: 'PROMPT_TEMPLATER_TYPE_UNSPECIFIED',
  PROMPT_TEMPLATER_TYPE_LLAMA_2: 'PROMPT_TEMPLATER_TYPE_LLAMA_2',
  PROMPT_TEMPLATER_TYPE_LLAMA_3: 'PROMPT_TEMPLATER_TYPE_LLAMA_3',
  PROMPT_TEMPLATER_TYPE_CHATML: 'PROMPT_TEMPLATER_TYPE_CHATML',
  PROMPT_TEMPLATER_TYPE_CHAT_TRANSCRIPT: 'PROMPT_TEMPLATER_TYPE_CHAT_TRANSCRIPT',
  PROMPT_TEMPLATER_TYPE_DEEPSEEK_V2: 'PROMPT_TEMPLATER_TYPE_DEEPSEEK_V2',
  PROMPT_TEMPLATER_TYPE_DEEPSEEK_V3: 'PROMPT_TEMPLATER_TYPE_DEEPSEEK_V3',
  PROMPT_TEMPLATER_TYPE_KIMI: 'PROMPT_TEMPLATER_TYPE_KIMI',
} as const;

export type PromptTemplaterType =
  | 'PROMPT_TEMPLATER_TYPE_UNSPECIFIED'
  | 0
  | 'PROMPT_TEMPLATER_TYPE_LLAMA_2'
  | 1
  | 'PROMPT_TEMPLATER_TYPE_LLAMA_3'
  | 2
  | 'PROMPT_TEMPLATER_TYPE_CHATML'
  | 3
  | 'PROMPT_TEMPLATER_TYPE_CHAT_TRANSCRIPT'
  | 4
  | 'PROMPT_TEMPLATER_TYPE_DEEPSEEK_V2'
  | 5
  | 'PROMPT_TEMPLATER_TYPE_DEEPSEEK_V3'
  | 6
  | 'PROMPT_TEMPLATER_TYPE_KIMI'
  | 7

export type PromptTemplaterType__Output = typeof PromptTemplaterType[keyof typeof PromptTemplaterType]
