// Original file: exa/codeium_common_pb/codeium_common.proto

export const ProviderSource = {
  PROVIDER_SOURCE_UNSPECIFIED: 'PROVIDER_SOURCE_UNSPECIFIED',
  PROVIDER_SOURCE_AUTOCOMPLETE: 'PROVIDER_SOURCE_AUTOCOMPLETE',
  PROVIDER_SOURCE_CHAT: 'PROVIDER_SOURCE_CHAT',
  PROVIDER_SOURCE_COMMAND_GENERATE: 'PROVIDER_SOURCE_COMMAND_GENERATE',
  PROVIDER_SOURCE_COMMAND_EDIT: 'PROVIDER_SOURCE_COMMAND_EDIT',
  PROVIDER_SOURCE_SUPERCOMPLETE: 'PROVIDER_SOURCE_SUPERCOMPLETE',
  PROVIDER_SOURCE_COMMAND_PLAN: 'PROVIDER_SOURCE_COMMAND_PLAN',
  PROVIDER_SOURCE_QUERY: 'PROVIDER_SOURCE_QUERY',
  PROVIDER_SOURCE_FAST_APPLY: 'PROVIDER_SOURCE_FAST_APPLY',
  PROVIDER_SOURCE_COMMAND_TERMINAL: 'PROVIDER_SOURCE_COMMAND_TERMINAL',
  PROVIDER_SOURCE_TAB_JUMP: 'PROVIDER_SOURCE_TAB_JUMP',
  PROVIDER_SOURCE_CASCADE: 'PROVIDER_SOURCE_CASCADE',
} as const;

export type ProviderSource =
  | 'PROVIDER_SOURCE_UNSPECIFIED'
  | 0
  | 'PROVIDER_SOURCE_AUTOCOMPLETE'
  | 1
  | 'PROVIDER_SOURCE_CHAT'
  | 2
  | 'PROVIDER_SOURCE_COMMAND_GENERATE'
  | 4
  | 'PROVIDER_SOURCE_COMMAND_EDIT'
  | 5
  | 'PROVIDER_SOURCE_SUPERCOMPLETE'
  | 6
  | 'PROVIDER_SOURCE_COMMAND_PLAN'
  | 7
  | 'PROVIDER_SOURCE_QUERY'
  | 8
  | 'PROVIDER_SOURCE_FAST_APPLY'
  | 9
  | 'PROVIDER_SOURCE_COMMAND_TERMINAL'
  | 10
  | 'PROVIDER_SOURCE_TAB_JUMP'
  | 11
  | 'PROVIDER_SOURCE_CASCADE'
  | 12

export type ProviderSource__Output = typeof ProviderSource[keyof typeof ProviderSource]
