// Original file: exa/codeium_common_pb/codeium_common.proto

export const RefreshCustomizationType = {
  REFRESH_CUSTOMIZATION_TYPE_UNSPECIFIED: 'REFRESH_CUSTOMIZATION_TYPE_UNSPECIFIED',
  REFRESH_CUSTOMIZATION_TYPE_RULE: 'REFRESH_CUSTOMIZATION_TYPE_RULE',
  REFRESH_CUSTOMIZATION_TYPE_WORKFLOW: 'REFRESH_CUSTOMIZATION_TYPE_WORKFLOW',
  REFRESH_CUSTOMIZATION_TYPE_USER_MEMORY: 'REFRESH_CUSTOMIZATION_TYPE_USER_MEMORY',
  REFRESH_CUSTOMIZATION_TYPE_SKILL: 'REFRESH_CUSTOMIZATION_TYPE_SKILL',
  REFRESH_CUSTOMIZATION_TYPE_PLAN: 'REFRESH_CUSTOMIZATION_TYPE_PLAN',
  REFRESH_CUSTOMIZATION_TYPE_MCP: 'REFRESH_CUSTOMIZATION_TYPE_MCP',
} as const;

export type RefreshCustomizationType =
  | 'REFRESH_CUSTOMIZATION_TYPE_UNSPECIFIED'
  | 0
  | 'REFRESH_CUSTOMIZATION_TYPE_RULE'
  | 1
  | 'REFRESH_CUSTOMIZATION_TYPE_WORKFLOW'
  | 2
  | 'REFRESH_CUSTOMIZATION_TYPE_USER_MEMORY'
  | 3
  | 'REFRESH_CUSTOMIZATION_TYPE_SKILL'
  | 4
  | 'REFRESH_CUSTOMIZATION_TYPE_PLAN'
  | 5
  | 'REFRESH_CUSTOMIZATION_TYPE_MCP'
  | 6

export type RefreshCustomizationType__Output = typeof RefreshCustomizationType[keyof typeof RefreshCustomizationType]
