// Original file: exa/codeium_common_pb/codeium_common.proto

export const StopReason = {
  STOP_REASON_UNSPECIFIED: 'STOP_REASON_UNSPECIFIED',
  STOP_REASON_INCOMPLETE: 'STOP_REASON_INCOMPLETE',
  STOP_REASON_STOP_PATTERN: 'STOP_REASON_STOP_PATTERN',
  STOP_REASON_MAX_TOKENS: 'STOP_REASON_MAX_TOKENS',
  STOP_REASON_MIN_LOG_PROB: 'STOP_REASON_MIN_LOG_PROB',
  STOP_REASON_MAX_NEWLINES: 'STOP_REASON_MAX_NEWLINES',
  STOP_REASON_EXIT_SCOPE: 'STOP_REASON_EXIT_SCOPE',
  STOP_REASON_NONFINITE_LOGIT_OR_PROB: 'STOP_REASON_NONFINITE_LOGIT_OR_PROB',
  STOP_REASON_FIRST_NON_WHITESPACE_LINE: 'STOP_REASON_FIRST_NON_WHITESPACE_LINE',
  STOP_REASON_PARTIAL: 'STOP_REASON_PARTIAL',
  STOP_REASON_FUNCTION_CALL: 'STOP_REASON_FUNCTION_CALL',
  STOP_REASON_CONTENT_FILTER: 'STOP_REASON_CONTENT_FILTER',
  STOP_REASON_NON_INSERTION: 'STOP_REASON_NON_INSERTION',
  STOP_REASON_ERROR: 'STOP_REASON_ERROR',
} as const;

export type StopReason =
  | 'STOP_REASON_UNSPECIFIED'
  | 0
  | 'STOP_REASON_INCOMPLETE'
  | 1
  | 'STOP_REASON_STOP_PATTERN'
  | 2
  | 'STOP_REASON_MAX_TOKENS'
  | 3
  | 'STOP_REASON_MIN_LOG_PROB'
  | 4
  | 'STOP_REASON_MAX_NEWLINES'
  | 5
  | 'STOP_REASON_EXIT_SCOPE'
  | 6
  | 'STOP_REASON_NONFINITE_LOGIT_OR_PROB'
  | 7
  | 'STOP_REASON_FIRST_NON_WHITESPACE_LINE'
  | 8
  | 'STOP_REASON_PARTIAL'
  | 9
  | 'STOP_REASON_FUNCTION_CALL'
  | 10
  | 'STOP_REASON_CONTENT_FILTER'
  | 11
  | 'STOP_REASON_NON_INSERTION'
  | 12
  | 'STOP_REASON_ERROR'
  | 13

export type StopReason__Output = typeof StopReason[keyof typeof StopReason]
