// Original file: exa/codeium_common_pb/codeium_common.proto

export const SupercompleteTriggerCondition = {
  SUPERCOMPLETE_TRIGGER_CONDITION_UNSPECIFIED: 'SUPERCOMPLETE_TRIGGER_CONDITION_UNSPECIFIED',
  SUPERCOMPLETE_TRIGGER_CONDITION_AUTOCOMPLETE_ACCEPT: 'SUPERCOMPLETE_TRIGGER_CONDITION_AUTOCOMPLETE_ACCEPT',
  SUPERCOMPLETE_TRIGGER_CONDITION_CURSOR_LINE_NAVIGATION: 'SUPERCOMPLETE_TRIGGER_CONDITION_CURSOR_LINE_NAVIGATION',
  SUPERCOMPLETE_TRIGGER_CONDITION_TYPING: 'SUPERCOMPLETE_TRIGGER_CONDITION_TYPING',
  SUPERCOMPLETE_TRIGGER_CONDITION_FORCED: 'SUPERCOMPLETE_TRIGGER_CONDITION_FORCED',
  SUPERCOMPLETE_TRIGGER_CONDITION_TAB_JUMP_ACCEPT: 'SUPERCOMPLETE_TRIGGER_CONDITION_TAB_JUMP_ACCEPT',
  SUPERCOMPLETE_TRIGGER_CONDITION_SUPERCOMPLETE_ACCEPT: 'SUPERCOMPLETE_TRIGGER_CONDITION_SUPERCOMPLETE_ACCEPT',
  SUPERCOMPLETE_TRIGGER_CONDITION_TAB_JUMP_PREDICTIVE: 'SUPERCOMPLETE_TRIGGER_CONDITION_TAB_JUMP_PREDICTIVE',
  SUPERCOMPLETE_TRIGGER_CONDITION_AUTOCOMPLETE_PREDICTIVE: 'SUPERCOMPLETE_TRIGGER_CONDITION_AUTOCOMPLETE_PREDICTIVE',
  SUPERCOMPLETE_TRIGGER_CONDITION_SUPERCOMPLETE_PREDICTIVE: 'SUPERCOMPLETE_TRIGGER_CONDITION_SUPERCOMPLETE_PREDICTIVE',
  SUPERCOMPLETE_TRIGGER_CONDITION_TAB_JUMP_EDIT: 'SUPERCOMPLETE_TRIGGER_CONDITION_TAB_JUMP_EDIT',
} as const;

export type SupercompleteTriggerCondition =
  | 'SUPERCOMPLETE_TRIGGER_CONDITION_UNSPECIFIED'
  | 0
  | 'SUPERCOMPLETE_TRIGGER_CONDITION_AUTOCOMPLETE_ACCEPT'
  | 1
  | 'SUPERCOMPLETE_TRIGGER_CONDITION_CURSOR_LINE_NAVIGATION'
  | 2
  | 'SUPERCOMPLETE_TRIGGER_CONDITION_TYPING'
  | 3
  | 'SUPERCOMPLETE_TRIGGER_CONDITION_FORCED'
  | 4
  | 'SUPERCOMPLETE_TRIGGER_CONDITION_TAB_JUMP_ACCEPT'
  | 5
  | 'SUPERCOMPLETE_TRIGGER_CONDITION_SUPERCOMPLETE_ACCEPT'
  | 6
  | 'SUPERCOMPLETE_TRIGGER_CONDITION_TAB_JUMP_PREDICTIVE'
  | 7
  | 'SUPERCOMPLETE_TRIGGER_CONDITION_AUTOCOMPLETE_PREDICTIVE'
  | 8
  | 'SUPERCOMPLETE_TRIGGER_CONDITION_SUPERCOMPLETE_PREDICTIVE'
  | 9
  | 'SUPERCOMPLETE_TRIGGER_CONDITION_TAB_JUMP_EDIT'
  | 10

export type SupercompleteTriggerCondition__Output = typeof SupercompleteTriggerCondition[keyof typeof SupercompleteTriggerCondition]
