// Original file: exa/codeium_common_pb/codeium_common.proto

export const TeamsFeatures = {
  TEAMS_FEATURES_UNSPECIFIED: 'TEAMS_FEATURES_UNSPECIFIED',
  TEAMS_FEATURES_SSO: 'TEAMS_FEATURES_SSO',
  TEAMS_FEATURES_ATTRIBUTION: 'TEAMS_FEATURES_ATTRIBUTION',
  TEAMS_FEATURES_PHI: 'TEAMS_FEATURES_PHI',
  TEAMS_FEATURES_CORTEX: 'TEAMS_FEATURES_CORTEX',
  TEAMS_FEATURES_OPENAI_DISABLED: 'TEAMS_FEATURES_OPENAI_DISABLED',
  TEAMS_FEATURES_REMOTE_INDEXING_DISABLED: 'TEAMS_FEATURES_REMOTE_INDEXING_DISABLED',
  TEAMS_FEATURES_API_KEY_ENABLED: 'TEAMS_FEATURES_API_KEY_ENABLED',
} as const;

export type TeamsFeatures =
  | 'TEAMS_FEATURES_UNSPECIFIED'
  | 0
  | 'TEAMS_FEATURES_SSO'
  | 1
  | 'TEAMS_FEATURES_ATTRIBUTION'
  | 2
  | 'TEAMS_FEATURES_PHI'
  | 3
  | 'TEAMS_FEATURES_CORTEX'
  | 4
  | 'TEAMS_FEATURES_OPENAI_DISABLED'
  | 5
  | 'TEAMS_FEATURES_REMOTE_INDEXING_DISABLED'
  | 6
  | 'TEAMS_FEATURES_API_KEY_ENABLED'
  | 7

export type TeamsFeatures__Output = typeof TeamsFeatures[keyof typeof TeamsFeatures]
