// Original file: exa/codeium_common_pb/codeium_common.proto

export const TeamsTier = {
  TEAMS_TIER_UNSPECIFIED: 'TEAMS_TIER_UNSPECIFIED',
  TEAMS_TIER_TEAMS: 'TEAMS_TIER_TEAMS',
  TEAMS_TIER_PRO: 'TEAMS_TIER_PRO',
  TEAMS_TIER_TRIAL: 'TEAMS_TIER_TRIAL',
  TEAMS_TIER_ENTERPRISE_SAAS: 'TEAMS_TIER_ENTERPRISE_SAAS',
  TEAMS_TIER_HYBRID: 'TEAMS_TIER_HYBRID',
  TEAMS_TIER_ENTERPRISE_SELF_HOSTED: 'TEAMS_TIER_ENTERPRISE_SELF_HOSTED',
  TEAMS_TIER_ENTERPRISE_SELF_SERVE: 'TEAMS_TIER_ENTERPRISE_SELF_SERVE',
  TEAMS_TIER_DEVIN_ENTERPRISE: 'TEAMS_TIER_DEVIN_ENTERPRISE',
  TEAMS_TIER_WAITLIST_PRO: 'TEAMS_TIER_WAITLIST_PRO',
  TEAMS_TIER_TEAMS_ULTIMATE: 'TEAMS_TIER_TEAMS_ULTIMATE',
  TEAMS_TIER_PRO_ULTIMATE: 'TEAMS_TIER_PRO_ULTIMATE',
  TEAMS_TIER_ENTERPRISE_SAAS_POOLED: 'TEAMS_TIER_ENTERPRISE_SAAS_POOLED',
} as const;

export type TeamsTier =
  | 'TEAMS_TIER_UNSPECIFIED'
  | 0
  | 'TEAMS_TIER_TEAMS'
  | 1
  | 'TEAMS_TIER_PRO'
  | 2
  | 'TEAMS_TIER_TRIAL'
  | 9
  | 'TEAMS_TIER_ENTERPRISE_SAAS'
  | 3
  | 'TEAMS_TIER_HYBRID'
  | 4
  | 'TEAMS_TIER_ENTERPRISE_SELF_HOSTED'
  | 5
  | 'TEAMS_TIER_ENTERPRISE_SELF_SERVE'
  | 10
  | 'TEAMS_TIER_DEVIN_ENTERPRISE'
  | 12
  | 'TEAMS_TIER_WAITLIST_PRO'
  | 6
  | 'TEAMS_TIER_TEAMS_ULTIMATE'
  | 7
  | 'TEAMS_TIER_PRO_ULTIMATE'
  | 8
  | 'TEAMS_TIER_ENTERPRISE_SAAS_POOLED'
  | 11

export type TeamsTier__Output = typeof TeamsTier[keyof typeof TeamsTier]
