// Original file: exa/codeium_common_pb/codeium_common.proto

export const ToolFormatterType = {
  TOOL_FORMATTER_TYPE_UNSPECIFIED: 'TOOL_FORMATTER_TYPE_UNSPECIFIED',
  TOOL_FORMATTER_TYPE_LLAMA_3: 'TOOL_FORMATTER_TYPE_LLAMA_3',
  TOOL_FORMATTER_TYPE_HERMES: 'TOOL_FORMATTER_TYPE_HERMES',
  TOOL_FORMATTER_TYPE_XML: 'TOOL_FORMATTER_TYPE_XML',
  TOOL_FORMATTER_TYPE_CHAT_TRANSCRIPT: 'TOOL_FORMATTER_TYPE_CHAT_TRANSCRIPT',
  TOOL_FORMATTER_TYPE_KIMI: 'TOOL_FORMATTER_TYPE_KIMI',
  TOOL_FORMATTER_TYPE_QWENCODER: 'TOOL_FORMATTER_TYPE_QWENCODER',
  TOOL_FORMATTER_TYPE_SUPERCOMPLETE: 'TOOL_FORMATTER_TYPE_SUPERCOMPLETE',
} as const;

export type ToolFormatterType =
  | 'TOOL_FORMATTER_TYPE_UNSPECIFIED'
  | 0
  | 'TOOL_FORMATTER_TYPE_LLAMA_3'
  | 1
  | 'TOOL_FORMATTER_TYPE_HERMES'
  | 2
  | 'TOOL_FORMATTER_TYPE_XML'
  | 3
  | 'TOOL_FORMATTER_TYPE_CHAT_TRANSCRIPT'
  | 4
  | 'TOOL_FORMATTER_TYPE_KIMI'
  | 5
  | 'TOOL_FORMATTER_TYPE_QWENCODER'
  | 6
  | 'TOOL_FORMATTER_TYPE_SUPERCOMPLETE'
  | 7

export type ToolFormatterType__Output = typeof ToolFormatterType[keyof typeof ToolFormatterType]
