// Original file: exa/codeium_common_pb/codeium_common.proto

export const TransactionStatus = {
  TRANSACTION_STATUS_UNSPECIFIED: 'TRANSACTION_STATUS_UNSPECIFIED',
  TRANSACTION_STATUS_SUCCEEDED: 'TRANSACTION_STATUS_SUCCEEDED',
  TRANSACTION_STATUS_PROCESSING: 'TRANSACTION_STATUS_PROCESSING',
  TRANSACTION_STATUS_FAILED: 'TRANSACTION_STATUS_FAILED',
  TRANSACTION_STATUS_NO_ACTIVE: 'TRANSACTION_STATUS_NO_ACTIVE',
} as const;

export type TransactionStatus =
  | 'TRANSACTION_STATUS_UNSPECIFIED'
  | 0
  | 'TRANSACTION_STATUS_SUCCEEDED'
  | 1
  | 'TRANSACTION_STATUS_PROCESSING'
  | 2
  | 'TRANSACTION_STATUS_FAILED'
  | 3
  | 'TRANSACTION_STATUS_NO_ACTIVE'
  | 4

export type TransactionStatus__Output = typeof TransactionStatus[keyof typeof TransactionStatus]
