// Original file: exa/codeium_common_pb/codeium_common.proto

import type { Model as _exa_codeium_common_pb_Model, Model__Output as _exa_codeium_common_pb_Model__Output } from '../../exa/codeium_common_pb/Model';
import type { ThemePreference as _exa_codeium_common_pb_ThemePreference, ThemePreference__Output as _exa_codeium_common_pb_ThemePreference__Output } from '../../exa/codeium_common_pb/ThemePreference';
import type { ExtensionPanelTab as _exa_codeium_common_pb_ExtensionPanelTab, ExtensionPanelTab__Output as _exa_codeium_common_pb_ExtensionPanelTab__Output } from '../../exa/codeium_common_pb/ExtensionPanelTab';
import type { FontSize as _exa_codeium_common_pb_FontSize, FontSize__Output as _exa_codeium_common_pb_FontSize__Output } from '../../exa/codeium_common_pb/FontSize';
import type { AutocompleteSpeed as _exa_codeium_common_pb_AutocompleteSpeed, AutocompleteSpeed__Output as _exa_codeium_common_pb_AutocompleteSpeed__Output } from '../../exa/codeium_common_pb/AutocompleteSpeed';
import type { RememberLastModelSelection as _exa_codeium_common_pb_RememberLastModelSelection, RememberLastModelSelection__Output as _exa_codeium_common_pb_RememberLastModelSelection__Output } from '../../exa/codeium_common_pb/RememberLastModelSelection';
import type { CascadeNUXState as _exa_codeium_common_pb_CascadeNUXState, CascadeNUXState__Output as _exa_codeium_common_pb_CascadeNUXState__Output } from '../../exa/codeium_common_pb/CascadeNUXState';
import type { ConversationalPlannerMode as _exa_codeium_common_pb_ConversationalPlannerMode, ConversationalPlannerMode__Output as _exa_codeium_common_pb_ConversationalPlannerMode__Output } from '../../exa/codeium_common_pb/ConversationalPlannerMode';
import type { UserNUXState as _exa_codeium_common_pb_UserNUXState, UserNUXState__Output as _exa_codeium_common_pb_UserNUXState__Output } from '../../exa/codeium_common_pb/UserNUXState';
import type { CascadeCommandsAutoExecution as _exa_codeium_common_pb_CascadeCommandsAutoExecution, CascadeCommandsAutoExecution__Output as _exa_codeium_common_pb_CascadeCommandsAutoExecution__Output } from '../../exa/codeium_common_pb/CascadeCommandsAutoExecution';
import type { ModelOrAlias as _exa_codeium_common_pb_ModelOrAlias, ModelOrAlias__Output as _exa_codeium_common_pb_ModelOrAlias__Output } from '../../exa/codeium_common_pb/ModelOrAlias';
import type { TabToJump as _exa_codeium_common_pb_TabToJump, TabToJump__Output as _exa_codeium_common_pb_TabToJump__Output } from '../../exa/codeium_common_pb/TabToJump';
import type { CascadeWebSearchTool as _exa_codeium_common_pb_CascadeWebSearchTool, CascadeWebSearchTool__Output as _exa_codeium_common_pb_CascadeWebSearchTool__Output } from '../../exa/codeium_common_pb/CascadeWebSearchTool';
import type { FeatureUsageData as _exa_codeium_common_pb_FeatureUsageData, FeatureUsageData__Output as _exa_codeium_common_pb_FeatureUsageData__Output } from '../../exa/codeium_common_pb/FeatureUsageData';
import type { ConversationBrainConfig as _exa_codeium_common_pb_ConversationBrainConfig, ConversationBrainConfig__Output as _exa_codeium_common_pb_ConversationBrainConfig__Output } from '../../exa/codeium_common_pb/ConversationBrainConfig';
import type { ClientModelConfig as _exa_codeium_common_pb_ClientModelConfig, ClientModelConfig__Output as _exa_codeium_common_pb_ClientModelConfig__Output } from '../../exa/codeium_common_pb/ClientModelConfig';
import type { ClientModelSort as _exa_codeium_common_pb_ClientModelSort, ClientModelSort__Output as _exa_codeium_common_pb_ClientModelSort__Output } from '../../exa/codeium_common_pb/ClientModelSort';
import type { PlanMode as _exa_codeium_common_pb_PlanMode, PlanMode__Output as _exa_codeium_common_pb_PlanMode__Output } from '../../exa/codeium_common_pb/PlanMode';
import type { AutoContinueOnMaxGeneratorInvocations as _exa_codeium_common_pb_AutoContinueOnMaxGeneratorInvocations, AutoContinueOnMaxGeneratorInvocations__Output as _exa_codeium_common_pb_AutoContinueOnMaxGeneratorInvocations__Output } from '../../exa/codeium_common_pb/AutoContinueOnMaxGeneratorInvocations';
import type { AnnotationsConfig as _exa_codeium_common_pb_AnnotationsConfig, AnnotationsConfig__Output as _exa_codeium_common_pb_AnnotationsConfig__Output } from '../../exa/codeium_common_pb/AnnotationsConfig';
import type { BrowserExperimentalFeaturesConfig as _exa_codeium_common_pb_BrowserExperimentalFeaturesConfig, BrowserExperimentalFeaturesConfig__Output as _exa_codeium_common_pb_BrowserExperimentalFeaturesConfig__Output } from '../../exa/codeium_common_pb/BrowserExperimentalFeaturesConfig';
import type { CommandPopupAutocomplete as _exa_codeium_common_pb_CommandPopupAutocomplete, CommandPopupAutocomplete__Output as _exa_codeium_common_pb_CommandPopupAutocomplete__Output } from '../../exa/codeium_common_pb/CommandPopupAutocomplete';
import type { CompletionMode as _exa_codeium_common_pb_CompletionMode, CompletionMode__Output as _exa_codeium_common_pb_CompletionMode__Output } from '../../exa/codeium_common_pb/CompletionMode';
import type { CascadeWebRequestsAutoExecution as _exa_codeium_common_pb_CascadeWebRequestsAutoExecution, CascadeWebRequestsAutoExecution__Output as _exa_codeium_common_pb_CascadeWebRequestsAutoExecution__Output } from '../../exa/codeium_common_pb/CascadeWebRequestsAutoExecution';

export interface UserSettings {
  'openMostRecentChatConversation'?: (boolean);
  'lastSelectedModel'?: (_exa_codeium_common_pb_Model);
  'themePreference'?: (_exa_codeium_common_pb_ThemePreference);
  'extensionPanelTab'?: (_exa_codeium_common_pb_ExtensionPanelTab);
  'fontSize'?: (_exa_codeium_common_pb_FontSize);
  'autocompleteSpeed'?: (_exa_codeium_common_pb_AutocompleteSpeed);
  'rememberLastModelSelection'?: (_exa_codeium_common_pb_RememberLastModelSelection);
  'lastSelectedModelName'?: (string);
  'lastSelectedCascadeModelDeprecated'?: (_exa_codeium_common_pb_Model);
  'cascadeNuxStates'?: (_exa_codeium_common_pb_CascadeNUXState)[];
  'cascadePlannerMode'?: (_exa_codeium_common_pb_ConversationalPlannerMode);
  'cascadeAllowedCommandsPrefix'?: (string)[];
  'cascadeDeniedCommandsPrefix'?: (string)[];
  'userNuxStates'?: (_exa_codeium_common_pb_UserNUXState)[];
  'cascadeWebSearchDisabled'?: (boolean);
  'disableAutocomplete'?: (boolean);
  'disableSupercomplete'?: (boolean);
  'disableSelectionPopup'?: (boolean);
  'disableExplainProblemInlayHint'?: (boolean);
  'disableInlayHintShortcuts'?: (boolean);
  'disableOpenCascadeOnReload'?: (boolean);
  'disableAutoOpenEditedFiles'?: (boolean);
  'disableTabToJump'?: (boolean);
  'cascadeAutoExecutionPolicy'?: (_exa_codeium_common_pb_CascadeCommandsAutoExecution);
  'lastSelectedCascadeId'?: (string);
  'explainAndFixInCurrentConversation'?: (boolean);
  'lastSelectedCascadeModelOrAliasDeprecated'?: (_exa_codeium_common_pb_ModelOrAlias | null);
  'allowCascadeAccessGitignoreFiles'?: (boolean);
  'disableCascadeAutoFixLints'?: (boolean);
  'disableCascadeBrowserPreviews'?: (boolean);
  'detectProxy'?: (boolean);
  'disableTabToImport'?: (boolean);
  'useClipboardForCompletions'?: (boolean);
  'disableHighlightAfterAccept'?: (boolean);
  'lastSelectedNewConvoTab'?: (string);
  'disableAutoGenerateMemories'?: (boolean);
  'enableSoundsForSpecialEvents'?: (boolean);
  'enableTabSounds'?: (boolean);
  'allowCascadeInBackground'?: (boolean);
  'tabToJump'?: (_exa_codeium_common_pb_TabToJump);
  'cascadeWebSearch'?: (_exa_codeium_common_pb_CascadeWebSearchTool);
  'enableTerminalCompletion'?: (boolean);
  'lastModelOverride'?: (_exa_codeium_common_pb_Model);
  'featureUsageData'?: ({[key: string]: _exa_codeium_common_pb_FeatureUsageData});
  'disableCascadeInBackground'?: (boolean);
  'enableCommandCascadeMode'?: (boolean);
  'customWorkspace'?: (string)[];
  'conversationBrainConfigs'?: ({[key: string]: _exa_codeium_common_pb_ConversationBrainConfig});
  'cachedCascadeModelConfigs'?: (_exa_codeium_common_pb_ClientModelConfig)[];
  'cachedCascadeModelSorts'?: (_exa_codeium_common_pb_ClientModelSort)[];
  'globalPlanModePreference'?: (_exa_codeium_common_pb_PlanMode);
  'isSnoozed'?: (boolean);
  'lastModelDefaultOverrideVersionId'?: (string);
  'autoContinueOnMaxGeneratorInvocations'?: (_exa_codeium_common_pb_AutoContinueOnMaxGeneratorInvocations);
  'seenNuxUids'?: ({[key: number]: boolean});
  'recentlyUsedCascadeModels'?: (string)[];
  'cascadeDismissedSuggestionWorkspaces'?: (string)[];
  'annotationsConfig'?: (_exa_codeium_common_pb_AnnotationsConfig);
  'enableAutomaticScreenshot'?: (boolean);
  'browserExperimentalFeaturesConfig'?: (_exa_codeium_common_pb_BrowserExperimentalFeaturesConfig);
  'commandPopupAutocomplete'?: (_exa_codeium_common_pb_CommandPopupAutocomplete);
  'enableInstantContextAgent'?: (boolean);
  'disableInstantContextAgent'?: (boolean);
  'lastSelectedSmartFriendModelDeprecated'?: (_exa_codeium_common_pb_Model);
  'enableCascadeCompletionNotifications'?: (boolean);
  'enableCascadeAlwaysNotifyOnFinish'?: (boolean);
  'completionMode'?: (_exa_codeium_common_pb_CompletionMode);
  'enableInlayHintShortcuts'?: (boolean);
  'cascadeAllowedCommands'?: (string)[];
  'cascadeDeniedCommands'?: (string)[];
  'cascadeModelExplicitlySet'?: (boolean);
  'cascadeUserAllowedWebOrigins'?: (string)[];
  'cascadeRemovedDefaultWebOrigins'?: (string)[];
  'cascadeWebRequestsAutoExecutionPolicy'?: (_exa_codeium_common_pb_CascadeWebRequestsAutoExecution);
  'lastSelectedCascadeModelUid'?: (string);
  'lastSelectedSmartFriendModelUid'?: (string);
  'lastSpecificArenaModelUids'?: (string)[];
  '_lastSelectedCascadeModelDeprecated'?: "lastSelectedCascadeModelDeprecated";
  '_lastSelectedCascadeModelOrAliasDeprecated'?: "lastSelectedCascadeModelOrAliasDeprecated";
  '_lastSelectedCascadeModelUid'?: "lastSelectedCascadeModelUid";
  '_cascadePlannerMode'?: "cascadePlannerMode";
  '_lastModelOverride'?: "lastModelOverride";
  '_lastModelDefaultOverrideVersionId'?: "lastModelDefaultOverrideVersionId";
  '_cascadeModelExplicitlySet'?: "cascadeModelExplicitlySet";
  '_lastSelectedCascadeId'?: "lastSelectedCascadeId";
  '_lastSelectedSmartFriendModelDeprecated'?: "lastSelectedSmartFriendModelDeprecated";
  '_lastSelectedSmartFriendModelUid'?: "lastSelectedSmartFriendModelUid";
}

export interface UserSettings__Output {
  'openMostRecentChatConversation': (boolean);
  'lastSelectedModel': (_exa_codeium_common_pb_Model__Output);
  'themePreference': (_exa_codeium_common_pb_ThemePreference__Output);
  'extensionPanelTab': (_exa_codeium_common_pb_ExtensionPanelTab__Output);
  'fontSize': (_exa_codeium_common_pb_FontSize__Output);
  'autocompleteSpeed': (_exa_codeium_common_pb_AutocompleteSpeed__Output);
  'rememberLastModelSelection': (_exa_codeium_common_pb_RememberLastModelSelection__Output);
  'lastSelectedModelName': (string);
  'lastSelectedCascadeModelDeprecated'?: (_exa_codeium_common_pb_Model__Output);
  'cascadeNuxStates': (_exa_codeium_common_pb_CascadeNUXState__Output)[];
  'cascadePlannerMode'?: (_exa_codeium_common_pb_ConversationalPlannerMode__Output);
  'cascadeAllowedCommandsPrefix': (string)[];
  'cascadeDeniedCommandsPrefix': (string)[];
  'userNuxStates': (_exa_codeium_common_pb_UserNUXState__Output)[];
  'cascadeWebSearchDisabled': (boolean);
  'disableAutocomplete': (boolean);
  'disableSupercomplete': (boolean);
  'disableSelectionPopup': (boolean);
  'disableExplainProblemInlayHint': (boolean);
  'disableInlayHintShortcuts': (boolean);
  'disableOpenCascadeOnReload': (boolean);
  'disableAutoOpenEditedFiles': (boolean);
  'disableTabToJump': (boolean);
  'cascadeAutoExecutionPolicy': (_exa_codeium_common_pb_CascadeCommandsAutoExecution__Output);
  'lastSelectedCascadeId'?: (string);
  'explainAndFixInCurrentConversation': (boolean);
  'lastSelectedCascadeModelOrAliasDeprecated'?: (_exa_codeium_common_pb_ModelOrAlias__Output | null);
  'allowCascadeAccessGitignoreFiles': (boolean);
  'disableCascadeAutoFixLints': (boolean);
  'disableCascadeBrowserPreviews': (boolean);
  'detectProxy': (boolean);
  'disableTabToImport': (boolean);
  'useClipboardForCompletions': (boolean);
  'disableHighlightAfterAccept': (boolean);
  'lastSelectedNewConvoTab': (string);
  'disableAutoGenerateMemories': (boolean);
  'enableSoundsForSpecialEvents': (boolean);
  'enableTabSounds': (boolean);
  'allowCascadeInBackground': (boolean);
  'tabToJump': (_exa_codeium_common_pb_TabToJump__Output);
  'cascadeWebSearch': (_exa_codeium_common_pb_CascadeWebSearchTool__Output);
  'enableTerminalCompletion': (boolean);
  'lastModelOverride'?: (_exa_codeium_common_pb_Model__Output);
  'featureUsageData': ({[key: string]: _exa_codeium_common_pb_FeatureUsageData__Output});
  'disableCascadeInBackground': (boolean);
  'enableCommandCascadeMode': (boolean);
  'customWorkspace': (string)[];
  'conversationBrainConfigs': ({[key: string]: _exa_codeium_common_pb_ConversationBrainConfig__Output});
  'cachedCascadeModelConfigs': (_exa_codeium_common_pb_ClientModelConfig__Output)[];
  'cachedCascadeModelSorts': (_exa_codeium_common_pb_ClientModelSort__Output)[];
  'globalPlanModePreference': (_exa_codeium_common_pb_PlanMode__Output);
  'isSnoozed': (boolean);
  'lastModelDefaultOverrideVersionId'?: (string);
  'autoContinueOnMaxGeneratorInvocations': (_exa_codeium_common_pb_AutoContinueOnMaxGeneratorInvocations__Output);
  'seenNuxUids': ({[key: number]: boolean});
  'recentlyUsedCascadeModels': (string)[];
  'cascadeDismissedSuggestionWorkspaces': (string)[];
  'annotationsConfig': (_exa_codeium_common_pb_AnnotationsConfig__Output);
  'enableAutomaticScreenshot': (boolean);
  'browserExperimentalFeaturesConfig': (_exa_codeium_common_pb_BrowserExperimentalFeaturesConfig__Output);
  'commandPopupAutocomplete': (_exa_codeium_common_pb_CommandPopupAutocomplete__Output);
  'enableInstantContextAgent': (boolean);
  'disableInstantContextAgent': (boolean);
  'lastSelectedSmartFriendModelDeprecated'?: (_exa_codeium_common_pb_Model__Output);
  'enableCascadeCompletionNotifications': (boolean);
  'enableCascadeAlwaysNotifyOnFinish': (boolean);
  'completionMode': (_exa_codeium_common_pb_CompletionMode__Output);
  'enableInlayHintShortcuts': (boolean);
  'cascadeAllowedCommands': (string)[];
  'cascadeDeniedCommands': (string)[];
  'cascadeModelExplicitlySet'?: (boolean);
  'cascadeUserAllowedWebOrigins': (string)[];
  'cascadeRemovedDefaultWebOrigins': (string)[];
  'cascadeWebRequestsAutoExecutionPolicy': (_exa_codeium_common_pb_CascadeWebRequestsAutoExecution__Output);
  'lastSelectedCascadeModelUid'?: (string);
  'lastSelectedSmartFriendModelUid'?: (string);
  'lastSpecificArenaModelUids': (string)[];
  '_lastSelectedCascadeModelDeprecated'?: "lastSelectedCascadeModelDeprecated";
  '_lastSelectedCascadeModelOrAliasDeprecated'?: "lastSelectedCascadeModelOrAliasDeprecated";
  '_lastSelectedCascadeModelUid'?: "lastSelectedCascadeModelUid";
  '_cascadePlannerMode'?: "cascadePlannerMode";
  '_lastModelOverride'?: "lastModelOverride";
  '_lastModelDefaultOverrideVersionId'?: "lastModelDefaultOverrideVersionId";
  '_cascadeModelExplicitlySet'?: "cascadeModelExplicitlySet";
  '_lastSelectedCascadeId'?: "lastSelectedCascadeId";
  '_lastSelectedSmartFriendModelDeprecated'?: "lastSelectedSmartFriendModelDeprecated";
  '_lastSelectedSmartFriendModelUid'?: "lastSelectedSmartFriendModelUid";
}
