import { MAX_UPLOAD_FILE_SIZE_MB } from '../../features/analysis/scm/env'

// Base GraphQL endpoint for MCP operations
export const MCP_DEFAULT_API_URL = 'https://api.mobb.ai/v1/graphql'

// HTTP header name used to transmit a user-provided MOBB API key
export const MCP_API_KEY_HEADER_NAME = 'x-mobb-key'

// Maximum time (ms) to wait for the user to complete browser-based login flow before aborting
export const MCP_LOGIN_MAX_WAIT = 2 * 60 * 1000 // 2 minutes

// Interval (ms) between successive polling attempts while waiting for login to complete
export const MCP_LOGIN_CHECK_DELAY = 2 * 1000 // 2 seconds

// Timeout (ms) for digesting vulnerability report data received from the backend
export const MCP_VUL_REPORT_DIGEST_TIMEOUT_MS = 5 * 60 * 1000 // 5 minutes

// Maximum size (bytes) of a single source file that will be packed and uploaded for analysis
export const MCP_MAX_FILE_SIZE = MAX_UPLOAD_FILE_SIZE_MB * 1024 * 1024 // 5 MB

// Interval (ms) for periodic background checks that look for new fixes generated by MCP
export const MCP_PERIODIC_CHECK_INTERVAL = 15 * 60 * 1000 // 15 minutes

// Maximum number of files to scan
export const MCP_DEFAULT_MAX_FILES_TO_SCAN = 10

// Time (ms) after which a fix report ID is considered expired (2 hours)
export const MCP_REPORT_ID_EXPIRATION_MS = 2 * 60 * 60 * 1000 // 2 hours

// Time (ms) after which a browser can be opened again after a previous open
export const MCP_TOOLS_BROWSER_COOLDOWN_MS = 24 * 60 * 60 * 1000 // 24 hours

// Default limit for paginated responses
export const MCP_DEFAULT_LIMIT = 3
