// Original file: exa/language_server_pb/language_server.proto

export const CustomizationFileType = {
  CUSTOMIZATION_FILE_TYPE_UNSPECIFIED: 'CUSTOMIZATION_FILE_TYPE_UNSPECIFIED',
  CUSTOMIZATION_FILE_TYPE_RULES: 'CUSTOMIZATION_FILE_TYPE_RULES',
  CUSTOMIZATION_FILE_TYPE_WORKFLOWS: 'CUSTOMIZATION_FILE_TYPE_WORKFLOWS',
  CUSTOMIZATION_FILE_TYPE_GLOBAL_WORKFLOWS: 'CUSTOMIZATION_FILE_TYPE_GLOBAL_WORKFLOWS',
  CUSTOMIZATION_FILE_TYPE_SKILLS: 'CUSTOMIZATION_FILE_TYPE_SKILLS',
  CUSTOMIZATION_FILE_TYPE_GLOBAL_SKILLS: 'CUSTOMIZATION_FILE_TYPE_GLOBAL_SKILLS',
} as const;

export type CustomizationFileType =
  | 'CUSTOMIZATION_FILE_TYPE_UNSPECIFIED'
  | 0
  | 'CUSTOMIZATION_FILE_TYPE_RULES'
  | 1
  | 'CUSTOMIZATION_FILE_TYPE_WORKFLOWS'
  | 2
  | 'CUSTOMIZATION_FILE_TYPE_GLOBAL_WORKFLOWS'
  | 3
  | 'CUSTOMIZATION_FILE_TYPE_SKILLS'
  | 4
  | 'CUSTOMIZATION_FILE_TYPE_GLOBAL_SKILLS'
  | 5

export type CustomizationFileType__Output = typeof CustomizationFileType[keyof typeof CustomizationFileType]
