// Original file: exa/language_server_pb/language_server.proto

export const EditSource = {
  EDIT_SOURCE_UNSPECIFIED: 'EDIT_SOURCE_UNSPECIFIED',
  EDIT_SOURCE_USER_TYPED: 'EDIT_SOURCE_USER_TYPED',
  EDIT_SOURCE_USER_PASTED: 'EDIT_SOURCE_USER_PASTED',
  EDIT_SOURCE_USER_UNDO: 'EDIT_SOURCE_USER_UNDO',
  EDIT_SOURCE_USER_REDO: 'EDIT_SOURCE_USER_REDO',
  EDIT_SOURCE_USER_CUT: 'EDIT_SOURCE_USER_CUT',
  EDIT_SOURCE_USER_DRAG_DROP: 'EDIT_SOURCE_USER_DRAG_DROP',
  EDIT_SOURCE_USER_TAB: 'EDIT_SOURCE_USER_TAB',
  EDIT_SOURCE_USER_REFACTORING: 'EDIT_SOURCE_USER_REFACTORING',
  EDIT_SOURCE_USER_FORMATTING: 'EDIT_SOURCE_USER_FORMATTING',
  EDIT_SOURCE_CASCADE_GENERATED: 'EDIT_SOURCE_CASCADE_GENERATED',
  EDIT_SOURCE_DISK_CHANGE: 'EDIT_SOURCE_DISK_CHANGE',
  EDIT_SOURCE_USER_OTHER: 'EDIT_SOURCE_USER_OTHER',
} as const;

export type EditSource =
  | 'EDIT_SOURCE_UNSPECIFIED'
  | 0
  | 'EDIT_SOURCE_USER_TYPED'
  | 1
  | 'EDIT_SOURCE_USER_PASTED'
  | 2
  | 'EDIT_SOURCE_USER_UNDO'
  | 3
  | 'EDIT_SOURCE_USER_REDO'
  | 4
  | 'EDIT_SOURCE_USER_CUT'
  | 5
  | 'EDIT_SOURCE_USER_DRAG_DROP'
  | 6
  | 'EDIT_SOURCE_USER_TAB'
  | 7
  | 'EDIT_SOURCE_USER_REFACTORING'
  | 8
  | 'EDIT_SOURCE_USER_FORMATTING'
  | 9
  | 'EDIT_SOURCE_CASCADE_GENERATED'
  | 10
  | 'EDIT_SOURCE_DISK_CHANGE'
  | 11
  | 'EDIT_SOURCE_USER_OTHER'
  | 12

export type EditSource__Output = typeof EditSource[keyof typeof EditSource]
