// Original file: exa/language_server_pb/language_server.proto

export const IdeAction = {
  IDE_ACTION_UNSPECIFIED: 'IDE_ACTION_UNSPECIFIED',
  IDE_ACTION_SAVE: 'IDE_ACTION_SAVE',
  IDE_ACTION_SELECTION_CHANGED: 'IDE_ACTION_SELECTION_CHANGED',
  IDE_ACTION_VISIBLE_RANGES_CHANGED: 'IDE_ACTION_VISIBLE_RANGES_CHANGED',
  IDE_ACTION_ACTIVE_EDITOR_CHANGED: 'IDE_ACTION_ACTIVE_EDITOR_CHANGED',
  IDE_ACTION_STARTUP: 'IDE_ACTION_STARTUP',
} as const;

export type IdeAction =
  | 'IDE_ACTION_UNSPECIFIED'
  | 0
  | 'IDE_ACTION_SAVE'
  | 1
  | 'IDE_ACTION_SELECTION_CHANGED'
  | 2
  | 'IDE_ACTION_VISIBLE_RANGES_CHANGED'
  | 3
  | 'IDE_ACTION_ACTIVE_EDITOR_CHANGED'
  | 4
  | 'IDE_ACTION_STARTUP'
  | 5

export type IdeAction__Output = typeof IdeAction[keyof typeof IdeAction]
