// Original file: exa/language_server_pb/language_server.proto

export const UnifiedDiffChangeType = {
  UNIFIED_DIFF_CHANGE_TYPE_UNSPECIFIED: 'UNIFIED_DIFF_CHANGE_TYPE_UNSPECIFIED',
  UNIFIED_DIFF_CHANGE_TYPE_INSERT: 'UNIFIED_DIFF_CHANGE_TYPE_INSERT',
  UNIFIED_DIFF_CHANGE_TYPE_DELETE: 'UNIFIED_DIFF_CHANGE_TYPE_DELETE',
  UNIFIED_DIFF_CHANGE_TYPE_UNCHANGED: 'UNIFIED_DIFF_CHANGE_TYPE_UNCHANGED',
} as const;

export type UnifiedDiffChangeType =
  | 'UNIFIED_DIFF_CHANGE_TYPE_UNSPECIFIED'
  | 0
  | 'UNIFIED_DIFF_CHANGE_TYPE_INSERT'
  | 1
  | 'UNIFIED_DIFF_CHANGE_TYPE_DELETE'
  | 2
  | 'UNIFIED_DIFF_CHANGE_TYPE_UNCHANGED'
  | 3

export type UnifiedDiffChangeType__Output = typeof UnifiedDiffChangeType[keyof typeof UnifiedDiffChangeType]
