import fs from 'node:fs'
import path from 'node:path'

import { GQLClient } from '@mobb/bugsy/features/analysis/graphql'
import {
  MOBB_ICON_IMG,
  REPORT_DEFAULT_FILE_NAME,
  scmCloudUrl,
  ScmType,
} from '@mobb/bugsy/features/analysis/scm'
import * as dotenv from 'dotenv'
import { beforeEach } from 'vitest'
import { z } from 'zod'

import { AuthManager } from '../src/commands/AuthManager'

// Configure dotenv — load monorepo-level .env first, then local cli .env
// (later calls don't overwrite existing vars, so cli/.env fills in gaps)
dotenv.config({
  path: path.join(__dirname, '../../../__tests__/.env'),
})
dotenv.config({
  path: path.join(__dirname, '../.env'),
})

// Reduce login timeout for integration tests: 30s instead of 10 minutes.
// This lets each test attempt login but fail fast when the backend is unavailable,
// instead of hanging for 10 minutes per test in the waitForAuthentication polling loop.
AuthManager.loginMaxWait = 2 * 60 * 1000

// Fake timers configuration (to be imported by test files)

// GitHub test token - uses PLAYWRIGHT_GH_CLOUD_PAT which is set by the
// "Select GitHub PAT with Available Quota" CI action to the token with most quota remaining
export const TEST_GITHUB_TOKEN = z
  .string()
  .parse(process.env['PLAYWRIGHT_GH_CLOUD_PAT'])

// Parse token from environment
export const token = z.string().parse(process.env['TOKEN'])

// Mock factory functions for creating mock implementations
// Note: The actual vi.mock() calls must remain at the top level of test files due to hoisting
export const createOpenMockImplementation = () => {
  return async (url: string) => {
    const match = url.match(/\/(cli-login|mvs-login)\/(.*?)\?.*$/)
    if (!match || match.length !== 3) {
      return
    }
    const loginId = match[2] as string
    try {
      const gqlClient = new GQLClient({
        token,
        type: 'token',
      })
      await gqlClient.createCommunityUser()
      // Emulate "Authenticate" button click in the Web UI.
      await gqlClient._clientSdk.performCliLogin({ loginId })
      await gqlClient.updateScmToken({
        scmType: ScmType.GitHub,
        url: scmCloudUrl.GitHub,
        org: undefined,
        refreshToken: undefined,
        token: TEST_GITHUB_TOKEN,
      })
    } catch (error) {
      console.error(
        '[open mock] login failed:',
        error instanceof Error ? error.message : String(error)
      )
    }
  }
}

export const createSnykMockImplementation = () => {
  return async (reportPath: string) => {
    fs.copyFileSync(path.join(__dirname, REPORT_DEFAULT_FILE_NAME), reportPath)
    return true
  }
}

// Common beforeEach setup function
export function setupCommonBeforeEach() {
  beforeEach(async () => {
    // Import vi at runtime to avoid hoisting issues
    const { vi } = await import('vitest')
    vi.clearAllMocks() // Clear all spy calls
    AuthManager.resetCooldown() // Prevent browser cooldown leaking between tests
  })
}

// UUID regex for analysis URLs
export const uuidRegex =
  '[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}'
export const analysisRegex = new RegExp(
  `organization/${uuidRegex}/project/${uuidRegex}/report/${uuidRegex}`
)

// Common message content
export const insecureCookieFixMessageContent = `# ![image](${MOBB_ICON_IMG}) Insecure Cookie fix is ready`
export const irrelevantIssueMessageContent = `# ![image](${MOBB_ICON_IMG}) Irrelevant issues were spotted - no action required`

// Mobb-Fixer-Demo-Fortify + mobb-3591-insecure-cookie branch.
// The branch introduces server.js with Express `res.cookie(...)` calls missing
// the `{ secure: true }` flag. Snyk's `javascript/WebCookieSecureDisabledByDefault`
// rule flags this; it maps to JS/INSECURE_COOKIE in
// pycommon/pycommon/report/supported_issues.json (IS_IO_BOUND=false),
// routing through the algorithmic fixer at
// consumers/analyzer/analyzer/fixes/js/insecure_cookie/ — no LLM call involved.
// Used by tests that want to exercise the app flow without LLM flakiness.
export const MOBB_FIXER_DEMO_FORTIFY_INSECURE_COOKIE = {
  URL: 'https://github.com/mobbcitestjob/Mobb-Fixer-Demo-Fortify',
  COMMIT_HASH: 'da2386de5798cf84889aa85bb6e358702c3000ee',
  REF: 'mobb-3591-insecure-cookie',
} as const

// Same fixture (server.js with insecure-cookie pattern) placed under a
// glob-matching path per irrelevance category. The path triggers the
// deterministic glob-based classifier in
// consumers/report_init/report_init/organization_files_matching_settings.py,
// tagging the issue as AUTOGENERATED / TEST / AUXILIARY / VENDOR respectively.
// The fix generator (JS/INSECURE_COOKIE, IS_IO_BOUND=false) is still
// algorithmic — so these tests exercise glob classification + algo fixer
// without any LLM call.
export const MOBB_FIXER_DEMO_FORTIFY_IRRELEVANT_AUTO_GENERATED = {
  URL: 'https://github.com/mobbcitestjob/Mobb-Fixer-Demo-Fortify',
  COMMIT_HASH: '29f3d7fceae5341d31f5ff655ffcecfdab99cfce',
  REF: 'mobb-3591-irrelevant-autogenerated',
} as const

export const MOBB_FIXER_DEMO_FORTIFY_IRRELEVANT_TEST_CODE = {
  URL: 'https://github.com/mobbcitestjob/Mobb-Fixer-Demo-Fortify',
  COMMIT_HASH: '617f51123d6631523439a9a89572f94a0c1ec4b6',
  REF: 'mobb-3591-irrelevant-test-code',
} as const

export const MOBB_FIXER_DEMO_FORTIFY_IRRELEVANT_AUXILIARY = {
  URL: 'https://github.com/mobbcitestjob/Mobb-Fixer-Demo-Fortify',
  COMMIT_HASH: '835ff29fa3a9d8141d77951993f8366b23ff8b64',
  REF: 'mobb-3591-irrelevant-auxiliary',
} as const

export const MOBB_FIXER_DEMO_FORTIFY_IRRELEVANT_VENDOR = {
  URL: 'https://github.com/mobbcitestjob/Mobb-Fixer-Demo-Fortify',
  COMMIT_HASH: '7d1618e41b4c1a13ce4c4a48ea298d1127c5f7bf',
  REF: 'mobb-3591-irrelevant-vendor',
} as const

export const GITHUB_FIXER_REPO_NOT_FIXABLE_IRRELEVANT_FALSE_POSITIVE_ISSUE = {
  URL: 'https://github.com/mobbcitestjob/gh-fixer',
  COMMIT_HASH: 'ecdaf4d681dcdbb54ca60e209e22010140cfd77e',
  REF: 'vul-pr-not-fixable-irrelevant-false-positive-llm',
} as const
